Update AM-INSTALLER
The function to install "AM" will use the "INSTALL" script.

diff --git a/AM-INSTALLER b/AM-INSTALLER
--- a/AM-INSTALLER
+++ b/AM-INSTALLER
@@ -18,113 +18,14 @@ arch=$(uname -m)
 currentuser="${LOGNAME:-${USERNAME:-${USER}}}"
 
 _check_dependency() {
-    program="$1"
-    _away_all command -v "$program" || { echo "For Installation to work, install \"$program\" first!" && exit 1; }
+	program="$1"
+	_away_all command -v "$program" || { echo "For Installation to work, install \"$program\" first!" && exit 1; }
 }
 
 _check_dependency 'wget'
 _check_dependency 'curl'
 
-# INSTALL "AM" SYSTEM-WIDE
-_install_am() {
-	# CREATING THE MAIN DIRECTORY FOR "AM"
-	mkdir -p /opt/am/.cache /opt/am/modules /usr/local/bin
-	cd /opt/am
-
-	# CREATE THE SCRIPT NEEDED TO UNINSTALL "AM"
-	printf '#!/bin/sh\n\nset -e\n' > /opt/am/remove
-	printf '\n%s\n' 'if [ "$(id -u)" -ne 0 ]; then echo "Permission denied"; exit 1; fi' >> /opt/am/remove
-	printf '%s\n' 'rm -f /usr/local/bin/am /etc/bash_completion.d/am-completion.sh' >> /opt/am/remove
-	printf '%s\n' 'rm -R -f /opt/am' >> /opt/am/remove
-	chmod a+x /opt/am/remove
-
-	# DOWNLOAD AND LINK THE MAIN SCRIPT
-	wget -q https://raw.githubusercontent.com/ivan-hc/AM/main/APP-MANAGER
-	chmod a+x /opt/am/APP-MANAGER
-	ln -s /opt/am/APP-MANAGER /usr/local/bin/am || echo "WARNING: Couldn't link am to \"/usr/local/bin/am\"!"
-
-	# DOWNLOAD THE LIST OF THE AVAILABLE PROGRAMS
-	wget -q "https://raw.githubusercontent.com/ivan-hc/AM/main/programs/$arch-apps" || exit 1
-
-	# DOWNLOAD MODULES
-	MODULES=$(curl -Ls https://api.github.com/repos/ivan-hc/AM/contents/modules | sed 's/[()",{}]/ /g; s/ /\n/g' \
-		| grep -o 'https.*raw.*modules.*am$' | grep -v "sync\|update" )
-	cd /opt/am/modules
-	echo "$MODULES" > modules.urls
-	wget -qi modules.urls
-	chmod a+x ./*.am
-	rm -f modules.urls
-
-	# ENABLE NON-ROOT PERMISSIONS TO THE MAIN DIRECTORY FOR THE CURRENT USER
-	chown -R $currentuser /opt/am 2> /dev/null
-
-	# ADD THE BASH COMPLETION SCRIPT
-	echo '#!/usr/bin/env bash' > /opt/am/am-completion.sh
-	echo 'complete -W "$(cat /opt/am/list 2>/dev/null)" am' >> /opt/am/am-completion.sh
-	chmod a+x /opt/am/am-completion.sh
-
-	if test -f /etc/bash_completion.d; then
-		mv /opt/am/am-completion.sh /etc/bash_completion.d/
-	else
-		mkdir -p /etc/bash_completion.d
-		sudo mv /opt/am/am-completion.sh /etc/bash_completion.d/
-	fi
-}
-
-# INSTALL "AM" LOCALLY, AS "APPMAN"
-_install_appman() {
-	ZPROFILE="${ZDOTDIR:-$HOME}/.zprofile"
-	BINDIR="${XDG_BIN_HOME:-$HOME/.local/bin}"
-	mkdir -p "$BINDIR"
-	if [ -e ~/.bash_profile ] && ! grep "$BINDIR" ~/.bash_profile; then
-		printf '\n%s\n' 'export PATH="$PATH:"$BINDIR""' >> ~/.bash_profile
-	elif [ -e ~/.profile ] && ! grep "$BINDIR" ~/.profile; then
-		printf '\n%s\n' 'export PATH="$PATH:"$BINDIR""' >> ~/.profile
-	fi
-	if [ -e "$ZPROFILE" ] && ! grep "$BINDIR" "$ZPROFILE"; then
-		printf '\n%s\n' "export PATH=\""'$PATH'":$BINDIR\"" >> "$ZPROFILE"
-	fi	
-	wget https://raw.githubusercontent.com/ivan-hc/AM/main/APP-MANAGER -O "$BINDIR"/appman && chmod a+x "$BINDIR"/appman
-}
-
-# CHOOSE BETWEEN "AM" AND "APPMAN"
-printf " Choose how to install \"AM\" and all its managed applications.
-
- 1) As \"${RED}AM\033[0m\", command \"${Green}am\033[0m\", this is a system-wide installation:
-   - the command is a symlink /usr/local/bin/am for /opt/am/APP-MANAGER
-   - all programs and \"AM\" itself in /opt, into dedicated directories
-   - a \"sudo\" password is required for this installation
-   - also installing/removing apps require a \"sudo\" password
-   - you are the owner and administrator of \"AM\" and all installed progems
-   - you have read-write permissions to update/remove \"AM\" and the apps
-   - other users can still use the \"AppMan mode\", but they can't update \"AM\"
-   - all system's users will be able to use programs you've installed
-
- 2) As \"${LightBlue}AppMan\033[0m\", command \"${Green}appman\033[0m\", local installation:
-   - the command is the script ~/.local/bin/appman
-   - choose wherever you want to install all the apps, in your HOME
-   - no \"sudo\" required at all
-   - you can replicate your configurations on every system you want
-   - each configuration is custom and personal
-   - other system's users cannot use your programs
-   - more storage space required, if more users use \"AppMan\"
-
-"
-read -r -p "Choose between \"AM\" (type 1) and \"AppMan\" (2), or leave blank to exit: " response
-case "$response" in
-	1)	AMCLI="am"
-		sh -c 'sudo _install_am' || exit 1
-		echo '--------------------------------------------------------------------------'
-		;;
-	2)	AMCLI="appman"
-		_install_appman || exit 1
-		echo '--------------------------------------------------------------------------'
-		;;
-	''|*)	echo "Installation aborted, exiting." && exit 1
-		;;
-esac
-
-# SHOW THE MESSAGE
+_final_message() {
 echo '
                _____                    _____
               /\    \                  /\    \		   A	   A
@@ -163,3 +64,60 @@ echo '
              Run "'"$AMCLI"' -h" to see the list of the options
  ##########################################################################
 '
+}
+
+# INSTALL "AM" SYSTEM-WIDE
+_install_am() {
+	wget -q https://raw.githubusercontent.com/ivan-hc/AM/main/INSTALL -O INSTALL-AM.sh && chmod a+x ./INSTALL-AM.sh || exit 1
+	sudo ./INSTALL-AM.sh && rm -f ./INSTALL-AM.sh
+}
+
+# INSTALL "AM" LOCALLY, AS "APPMAN"
+_install_appman() {
+	ZPROFILE="${ZDOTDIR:-$HOME}/.zprofile"
+	BINDIR="${XDG_BIN_HOME:-$HOME/.local/bin}"
+	mkdir -p "$BINDIR"
+	if [ -e ~/.bash_profile ] && ! grep "$BINDIR" ~/.bash_profile; then
+		printf '\n%s\n' 'export PATH="$PATH:"$BINDIR""' >> ~/.bash_profile
+	elif [ -e ~/.profile ] && ! grep "$BINDIR" ~/.profile; then
+		printf '\n%s\n' 'export PATH="$PATH:"$BINDIR""' >> ~/.profile
+	fi
+	if [ -e "$ZPROFILE" ] && ! grep "$BINDIR" "$ZPROFILE"; then
+		printf '\n%s\n' "export PATH=\""'$PATH'":$BINDIR\"" >> "$ZPROFILE"
+	fi	
+	wget -q https://raw.githubusercontent.com/ivan-hc/AM/main/APP-MANAGER -O "$BINDIR"/appman && chmod a+x "$BINDIR"/appman
+}
+
+# CHOOSE BETWEEN "AM" AND "APPMAN"
+printf " Choose how to install \"AM\" and all its managed applications.
+
+ 1) As \"${RED}AM\033[0m\", command \"${Green}am\033[0m\", this is a system-wide installation:
+   - the command is a symlink /usr/local/bin/am for /opt/am/APP-MANAGER
+   - all programs will be installed in /opt, into dedicated directories
+   - a \"sudo\" password is required both here and to install/remove apps
+   - you are the one with read-write permissions for \"AM\" and all programs
+   - other users can only use programs you have installed, nothing else
+   - other users can still use \"AppMan mode\" for their rootless configurations
+
+ 2) As \"${LightBlue}AppMan\033[0m\", command \"${Green}appman\033[0m\", local installation:
+   - the command is the script ~/.local/bin/appman
+   - choose wherever you want to install all the apps, in your HOME
+   - no \"sudo\" required at all
+   - you can replicate your configurations on every system you want
+   - more storage space required, if more users use \"AppMan\"
+
+"
+read -r -p "Choose between \"AM\" (type 1) and \"AppMan\" (2), or leave blank to exit: " response
+case "$response" in
+	1)	AMCLI="am"
+		_install_am || exit 1
+		;;
+	2)	AMCLI="appman"
+		_install_appman || exit 1
+		echo '--------------------------------------------------------------------------'
+		_final_message
+		echo '--------------------------------------------------------------------------'
+		;;
+	''|*)	echo "Installation aborted, exiting." && exit 1
+		;;
+esac
