allow translation

diff --git a/AM-INSTALLER b/AM-INSTALLER
--- a/AM-INSTALLER
+++ b/AM-INSTALLER
@@ -8,12 +8,16 @@ RED='\033[0;31m'; LightBlue='\033[1;34m'; Green='\033[0;32m'
 # For developers
 AM_BRANCH="main"
 
+# Use translations
+export TEXTDOMAIN=am
+export TEXTDOMAINDIR=/usr/share/locale
+
 # Check dependencies for this script
 _check_dependency() {
 	AMDEPENDENCES="chmod chown curl grep wget"
 	for dependency in $AMDEPENDENCES; do
 		if ! command -v "$dependency" >/dev/null 2>&1; then
-			printf "\n %b💀 ERROR! MISSING ESSENTIAL COMMAND \033[0m: %b\n\n Install the above and try again! \n\n" "${RED}" "$dependency"
+			printf $"\n %b💀 ERROR! MISSING ESSENTIAL COMMAND \033[0m: %b\n\n Install the above and try again! \n\n" "${RED}" "$dependency"
 			exit 1
 		fi
 	done
@@ -24,7 +28,7 @@ _check_dependency
 # Function to check online connections (uses github.com by default, as the database and CLI itself are stored/hosted there)
 _online_check() {
 	if ! wget -q --tries=3 --timeout=10 --spider https://github.com; then
-		printf "\n Installer wouldn't work offline\n\n Please check your internet connection and try again\n\n"
+		printf $"\n Installer wouldn't work offline\n\n Please check your internet connection and try again\n\n"
 		exit 1
 	fi
 }
@@ -43,7 +47,7 @@ _install_am() {
 	elif command -v doas >/dev/null 2>&1; then
 		SUDOCMD="doas"
 	else
-		echo 'ERROR: No sudo or doas found'
+		echo $'ERROR: No sudo or doas found'
 		exit 1
 	fi
 	$SUDOCMD "$CACHEDIR"/INSTALL-AM.sh && rm -f "$CACHEDIR"/INSTALL-AM.sh
@@ -56,8 +60,8 @@ _install_appman() {
 	mkdir -p "$BINDIR"
 	if ! echo $PATH | grep "$BINDIR" >/dev/null 2>&1; then 
 		echo '--------------------------------------------------------------------------'
-		echo " Adding $BINDIR to PATH, you might need to"
-		echo " close and reopen the terminal for this to take effect."
+		echo $" Adding $BINDIR to PATH, you might need to"
+		echo $" close and reopen the terminal for this to take effect."
 		if [ -e ~/.bashrc ] && ! grep 'PATH="$PATH:$BINDIR"' ~/.bashrc >/dev/null 2>&1; then
 			printf '\n%s\n' 'BINDIR="${XDG_BIN_HOME:-$HOME/.local/bin}"' >> ~/.bashrc
 			printf '\n%s\n' 'if ! echo $PATH | grep "$BINDIR" >/dev/null 2>&1; then' >> ~/.bashrc
@@ -73,7 +77,7 @@ _install_appman() {
 }
 
 # CHOOSE BETWEEN "AM" AND "APPMAN"
-printf " Choose how to install \"AM\" and all its managed applications.
+printf $" Choose how to install \"AM\" and all its managed applications.
 
  1) As \"${RED}AM\033[0m\", command \"${Green}am\033[0m\", this is a system-wide installation:
    - the command is a symlink /usr/local/bin/am for /opt/am/APP-MANAGER
@@ -97,10 +101,10 @@ case "$response" in
 		;;
 	2)	_install_appman || exit 1
 		echo '--------------------------------------------------------------------------'
-		printf " ${Green}\"AppMan\" has been successfully installed!\033[0m\n"
-		printf " Please, run \"${LightBlue}appman -h\033[0m\" to see the list of the options.\n"
+		printf $" ${Green}\"AppMan\" has been successfully installed!\033[0m\n"
+		printf $" Please, run \"${LightBlue}appman -h\033[0m\" to see the list of the options.\n"
 		echo '--------------------------------------------------------------------------'
 		;;
-	''|*)	echo "Installation aborted, exiting." && exit 1
+	''|*)	echo $"Installation aborted, exiting." && exit 1
 		;;
 esac
