AM-INSTALLER: Support for non-interactive installation via flag (#2509)
* Update AM-INSTALLER

Support for non-interactive installation via flag -i, --install or install

fix https://github.com/ivan-hc/AM/issues/2490

* Update README.md

diff --git a/AM-INSTALLER b/AM-INSTALLER
--- a/AM-INSTALLER
+++ b/AM-INSTALLER
@@ -150,14 +150,32 @@ Choose how to install \"AM\" and its managed applications:
 - Others    : can have separate configs or replicate yours
 \n" "${RED}" "${Green}" "${LightBlue}" "${Green}" "$HOME" "$HOME" | _fit
 
-read -r -p " Choose between \"AM\" (type 1) and \"AppMan\" (2), or leave blank to exit: " response
-case "$response" in
-	1)	_install_am || exit 1
+case "$1" in
+	'')
+		read -r -p " Choose between \"AM\" (type 1) and \"AppMan\" (2), or leave blank to exit: " response
+		case "$response" in
+			1)	_install_am || exit 1
+				;;
+			2)	_install_appman || exit 1
+				;;
+			''|*)
+				echo "$DIVIDING_LINE"
+				echo "Installation aborted, exiting." && echo "$DIVIDING_LINE" && exit 1
+				;;
+		esac
 		;;
-	2)	_install_appman || exit 1
-		;;
-	''|*)
-		echo "$DIVIDING_LINE"
-		echo "Installation aborted, exiting." && echo "$DIVIDING_LINE" && exit 1
+	'--install'|'-i'|'install')
+		case "$2" in
+			'')	echo "$DIVIDING_LINE" && echo "ERROR, $1 require an argument between \"am\" and \"appman\"" | _fit && echo "$DIVIDING_LINE" && exit 1
+				;;
+			'am')
+				_install_am || exit 1
+				;;
+			'appman')
+				_install_appman || exit 1
+				;;
+			*)	echo "$DIVIDING_LINE" && echo "Invalid argument \"$2\", $1 only allows one between \"am\" and \"appman\"" | _fit && echo "$DIVIDING_LINE" && exit 1
+				;;
+		esac
 		;;
 esac
