Use static binaries as a fallback solution if missing dependencies

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-AMVERSION="10.1-4"
+AMVERSION="10.1-5"
 
 # Determine main repository and branch
 AMREPO="https://raw.githubusercontent.com/ivan-hc/AM/main"
@@ -491,10 +491,41 @@ _validate_and_download_lists_of_archived_and_obsolete_apps() {
 
 # SAFETY CHECKS
 
+# Use static binaries as a fallback solution in case there are no dependencies
+AM_core_dependencies="cat chmod chown curl grep sed wget"
+AM_opt_dependencies="7z ar column file md5sum sha1sum sha256sum sha512sum tar unzip xz"
+_deps_dl() {
+	if command -v curl >/dev/null 2>&1; then
+		curl -Lo "$CACHEDIR"/AMCACHEPATH/"$name" "$AM_UTILS_SOURCE/$name-$ARCH-static" 2>/dev/null
+	elif command -v wget >/dev/null 2>&1; then
+		wget -q "$AM_UTILS_SOURCE/$name-$ARCH-static" -O "$CACHEDIR"/AMCACHEPATH/"$name"
+	else
+		echo " 💀 ERROR: No curl or wget found"
+		exit 0
+	fi
+}
+
+if [ "$ARCH" = aarch64 ] || [ "$ARCH" = x86_64 ]; then
+	mkdir -p "$CACHEDIR"/AMCACHEPATH
+	amutils="$AM_core_dependencies $AM_opt_dependencies"
+	AM_UTILS_SOURCE="https://github.com/ivan-hc/am-utils/releases/download/$ARCH-20260502"
+	for name in $amutils; do
+		if ! command -v "$name" >/dev/null 2>&1; then
+			if [ -d "$CACHEDIR"/AMCACHEPATH/"$name" ] || [ -L "$CACHEDIR"/AMCACHEPATH/"$name" ] || [ ! -f "$CACHEDIR"/AMCACHEPATH/"$name" ]; then
+				rm -Rf "$CACHEDIR"/AMCACHEPATH/"$name"
+				printf "Missing command \"%b\", downloading static binary as a fallback solution\n" "$name" | _fit
+				_deps_dl && chmod a+x "$CACHEDIR"/AMCACHEPATH/"$name"
+			fi
+		else
+			rm -Rf "$CACHEDIR"/AMCACHEPATH/"$name"
+		fi
+	done
+	export PATH="$CACHEDIR"/AMCACHEPATH/:"${PATH}"
+fi
+
 # Check for essential commands required by the application
 missing_deps=""
-AMDEPENDENCES="cat chmod chown curl grep sed wget"
-for name in $AMDEPENDENCES; do
+for name in $AM_core_dependencies; do
 	if ! command -v "$name" >/dev/null 2>&1; then
 		missing_deps="$name $missing_deps"
 	fi
@@ -542,9 +573,16 @@ _online_check() {
 
 # Check AMCACHEPATH integrity
 if [ -d "$CACHEDIR"/AMCACHEPATH ]; then
-	am_bins_allowed=$(echo "appimagetool" | tr ' ' '\n' | sed "s#^#$CACHEDIR/AMCACHEPATH/#g")
+	am_bins_allowed=$(echo "appimagetool $amutils" | tr ' ' '\n' | sed "s#^#$CACHEDIR/AMCACHEPATH/#g")
 	am_bins_all=$(find "$CACHEDIR"/AMCACHEPATH -mindepth 1 -maxdepth 1 \( -type d -o -type f -o -type l \))
-	for f in $am_bins_all; do if ! echo "$am_bins_allowed" | grep -q "$f$" 2>/dev/null; then rm "$f" 2>/dev/null; fi; done
+	if [ -n "$am_bins_all" ]; then
+		for f in "$CACHEDIR"/AMCACHEPATH/*; do
+			am_bin_item=$(echo "$f" | sed 's:.*/::')
+			if ! echo "$am_bins_allowed" | grep -q "$am_bin_item$" 2>/dev/null; then
+				rm -Rf "$f"
+			fi
+		done
+	fi
 fi
 
 # Check if appimagetool is installed, and if it is not installed, download and use it where it is needed
