Move _appman_validate_directory function

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -55,7 +55,27 @@ function _appman_prompt_for_directory() {
 	echo "$location"
 }
 
+# we are doing this because script will be more readable. We separate "working" part of script, from script logic itself
 
+function _appman_validate_directory() {
+	local location=$1
+	if [[ "$location" == "" ]]; then
+		echo -e "--------------------------------------------------------------------------"
+		echo "OPERATION ABORTED!"
+		exit  1
+	elif [[ "$location" == ".local/bin" ]]; then
+		echo -e "--------------------------------------------------------------------------\n"
+		echo -e " 💀 ERROR, you can't install applications into a '$PATH'\n\n The directory ~/.local/bin and 'bin' folders are used for executables.\n\n Please, choose a different path and retry! \n"
+		echo -e "--------------------------------------------------------------------------\n"
+		exit  1
+	else
+		local location_appman="${location/#$HOME}"
+		location_appman="${location_appman// /-}"
+		location_appman="${location_appman#/}"
+		location_appman="${location_appman%/}"
+		echo "$location_appman"
+	fi
+}
 
 
 
@@ -111,25 +131,7 @@ fi
 
 # "APPMAN" CORE VARIABLES AND FUNCTIONS
 function _appman() {
-	function _appman_validate_directory() {
-		local location=$1
-		if [[ "$location" == "" ]]; then
-			echo -e "--------------------------------------------------------------------------"
-			echo "OPERATION ABORTED!"
-			exit  1
-		elif [[ "$location" == ".local/bin" ]]; then
-			echo -e "--------------------------------------------------------------------------\n"
-			echo -e " 💀 ERROR, you can't install applications into a '$PATH'\n\n The directory ~/.local/bin and 'bin' folders are used for executables.\n\n Please, choose a different path and retry! \n"
-			echo -e "--------------------------------------------------------------------------\n"
-			exit  1
-		else
-			local location_appman="${location/#$HOME}"
-			location_appman="${location_appman// /-}"
-			location_appman="${location_appman#/}"
-			location_appman="${location_appman%/}"
-			echo "$location_appman"
-		fi
-	}
+
 
 	if [[ ! -f "$APPMANCONFIG"/appman-config ]]; then
 		echo "--------------------------------------------------------------------------"
