printf

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -229,6 +229,35 @@ function _use_betatester_off() {
 	rm -f "$AMPATH"/betatester
 }
 
+function _jq_installer() {
+	if ! command -v jq 1>/dev/null; then
+		_system_package_manager_check
+		if [[ -z "$osPKGman" ]];then
+			echo -e " ${RED}💀 ERROR!\033[0m Missing essential command ${Green}jq\033[0m\n"
+			read -p " Do you wish to install it using $AMCLI (Y,n)? " yn
+			case $yn in
+			'N'|'n')
+				printf '\n The "jq" command is essential for parsing JSON files on sites\n\
+				 for example api.github.com, to list the URLs of apps to download.\n\
+				 You need to install it at least via your package manager to use %s.\n\n\
+				 Missing essential command ${RED}jq\033[0m, aborted!' "$AMCLI"
+				exit
+				;;
+			'Y'|'y'|*)
+				rm -f "$AMPATH"/.cache/*
+				echo
+				source "$AMPATH"/modules/install.am -i jq 2>&1 | grep 'INSTALLED'
+				echo
+				;;
+			esac
+		else
+			echo -e " ${RED}💀 ERROR!\033[0m Missing essential command ${Green}jq\033[0m\n"
+			printf ' Install it from your system package manager %s and retry!' "$osPKGman"
+			exit
+		fi
+	fi
+}
+
 # DOWNLOAD PORTABLE DEPENDENCES
 function _portable_dependences_setup() {
 
