Improve online check, one block  for dependencies check
- _online_check now can alternate between wget and curl
- wget/curl availability is determined directly in _online_check
- move _online_check before dependencies check
- list missing dependencies before installing them, and show the source
- remove appimagetool and other extra dependencies not in "am-utils" if the command is in $PATH
always check "purity" of the AMCACHEPATH directory

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-AMVERSION="10.1-6"
+AMVERSION="10.1-7"
 
 # Determine main repository and branch
 AMREPO="https://raw.githubusercontent.com/ivan-hc/AM/main"
@@ -492,6 +492,25 @@ _validate_and_download_lists_of_archived_and_obsolete_apps() {
 
 # SAFETY CHECKS
 
+# Function to check online connections (uses github.com by default, as the database and CLI itself are stored/hosted there)
+_online_check_tool() {
+	if command -v wget >/dev/null 2>&1; then
+		wget -q --tries=10 --timeout=20 --spider https://github.com
+	elif command -v curl >/dev/null 2>&1; then
+		curl --output /dev/null --silent --head --fail https://github.com 1> /dev/null
+	else
+		printf $" ${RED}💀 ERROR! MISSING ESSENTIAL COMMANDS\033[0m: %s\n\n Install the above and try again! \n" "$(echo "curl, wget")"
+		exit 0
+	fi
+}
+
+_online_check() {
+	if ! _online_check_tool; then
+		printf $"\n %b is offline, please check your internet connection and try again\n\n" "$AMCLI"
+		exit 0
+	fi
+}
+
 # Use static binaries as a fallback solution in case there are no dependencies
 AM_core_dependencies="cat chmod chown curl grep sed wget"
 AM_opt_dependencies="7z ar column file md5sum sha1sum sha256sum sha512sum tar unxz unzip xz xzcat"
@@ -500,27 +519,53 @@ _deps_dl() {
 		curl -Lo "$CACHEDIR"/AMCACHEPATH/"$name" "$AM_UTILS_SOURCE/$name-$ARCH-static" 2>/dev/null
 	elif command -v wget >/dev/null 2>&1; then
 		wget -q "$AM_UTILS_SOURCE/$name-$ARCH-static" -O "$CACHEDIR"/AMCACHEPATH/"$name"
-	else
-		echo " 💀 ERROR: No curl or wget found"
-		exit 0
 	fi
 }
 
 if [ "$ARCH" = aarch64 ] || [ "$ARCH" = x86_64 ]; then
 	mkdir -p "$CACHEDIR"/AMCACHEPATH
+	# Download static binaries if commands are not available
 	amutils="$AM_core_dependencies $AM_opt_dependencies"
 	AM_UTILS_SOURCE="https://github.com/ivan-hc/am-utils/releases/download/continuous-$ARCH"
 	for name in $amutils; do
 		if ! command -v "$name" >/dev/null 2>&1; then
 			if [ -d "$CACHEDIR"/AMCACHEPATH/"$name" ] || [ -L "$CACHEDIR"/AMCACHEPATH/"$name" ] || [ ! -f "$CACHEDIR"/AMCACHEPATH/"$name" ]; then
 				rm -Rf "$CACHEDIR"/AMCACHEPATH/"$name"
-				printf "Missing command \"%b\", downloading static binary as a fallback solution\n" "$name" | _fit
-				_deps_dl && chmod a+x "$CACHEDIR"/AMCACHEPATH/"$name"
+				if [ -z "$fallback_binaries_needed" ]; then
+					fallback_binaries_needed="$name"
+				else
+					fallback_binaries_needed=$(echo "$fallback_binaries_needed $name" | tr ' ' '\n' | sort | xargs)
+				fi
 			fi
-		else
+		fi
+	done
+	if [ -n "$fallback_binaries_needed" ]; then
+		_online_check
+		printf "%b\n" "$DIVIDING_LINE"
+		printf "Missing commands will be temporarily downloaded as static binaries:\n\n" | _fit
+		for name in $fallback_binaries_needed; do
+			_deps_dl && chmod a+x "$CACHEDIR"/AMCACHEPATH/"$name" && printf " - %b, downloaded from https://github.com/ivan-hc/am-utils\n" "$name"
+		done
+		printf "\n%b\n" "$DIVIDING_LINE"
+	fi
+	# Remove static binaries and other temporary utilities if related commands are already available in PATH
+	amutils="appimagetool $amutils"
+	for name in $amutils; do
+		if command -v "$name" >/dev/null 2>&1 && [ -f "$CACHEDIR"/AMCACHEPATH/"$name" ]; then
 			rm -Rf "$CACHEDIR"/AMCACHEPATH/"$name"
 		fi
 	done
+	# Check AMCACHEPATH integrity
+	am_bins_allowed=$(echo "$amutils" | tr ' ' '\n' | sed "s#^#$CACHEDIR/AMCACHEPATH/#g")
+	am_bins_all=$(find "$CACHEDIR"/AMCACHEPATH -mindepth 1 -maxdepth 1 \( -type d -o -type f -o -type l \))
+	if [ -n "$am_bins_all" ]; then
+		for f in "$CACHEDIR"/AMCACHEPATH/*; do
+			am_bin_item=$(echo "$f" | sed 's:.*/::')
+			if ! echo "$am_bins_allowed" | grep -q "$am_bin_item$" 2>/dev/null; then
+				rm -Rf "$f"
+			fi
+		done
+	fi
 	export PATH="$CACHEDIR"/AMCACHEPATH/:"${PATH}"
 fi
 
@@ -537,10 +582,10 @@ if [ -n "$missing_deps" ]; then
 	echo "$DIVIDING_LINE"
 	printf $" ${RED}💀 ERROR! MISSING ESSENTIAL COMMANDS\033[0m: %s\n\n Install the above and try again! \n" "${missing_deps[*]}"
 	echo "$DIVIDING_LINE"
-	printf $"%bList of the %b core dependences\033[0m:\n\n%b\n" "${Green}" "$AMCLIUPPER $AMVERSION" "$AMDEPENDENCES" | _fit
+	printf $"%bList of the %b core dependences\033[0m:\n\n%b\n" "${Green}" "$AMCLIUPPER $AMVERSION" "$AM_core_dependencies" | _fit
 	echo "$DIVIDING_LINE"
 	printf $"If this message appears it is because you are missing some dependency and if its the first time its because something new has been introduced.\n\n" | _fit
-	printf $" See %bhttps://github.com/ivan-hc/AM#core-dependences\033[0m for more information\n" "${LightBlue}"
+	printf $" See %bhttps://github.com/ivan-hc/AM#installation\033[0m for more information\n" "${LightBlue}"
 	echo "$DIVIDING_LINE"
 	exit 1
 fi
@@ -563,28 +608,6 @@ _check_fedora_mess() {
 		[ -f /etc/redhat-release ] && printf $"Please install \"%bwget1\033[0m\" and \"%bwget1-wget\033[0m\" (use %b--allowerasing\033[0m if you have to)\n\nSee https://bugzilla.redhat.com/show_bug.cgi?id=2358792\n\n" "${Gold}" "${Gold}" "${Green}" | sed "s/^/ /g"
 	fi
 }
-
-# Function to check online connections (uses github.com by default, as the database and CLI itself are stored/hosted there)
-_online_check() {
-	if ! wget -q --tries=10 --timeout=20 --spider https://github.com; then
-		printf $"\n %b is offline, please check your internet connection and try again\n\n" "$AMCLI"
-		exit 0
-	fi
-}
-
-# Check AMCACHEPATH integrity
-if [ -d "$CACHEDIR"/AMCACHEPATH ]; then
-	am_bins_allowed=$(echo "appimagetool $amutils" | tr ' ' '\n' | sed "s#^#$CACHEDIR/AMCACHEPATH/#g")
-	am_bins_all=$(find "$CACHEDIR"/AMCACHEPATH -mindepth 1 -maxdepth 1 \( -type d -o -type f -o -type l \))
-	if [ -n "$am_bins_all" ]; then
-		for f in "$CACHEDIR"/AMCACHEPATH/*; do
-			am_bin_item=$(echo "$f" | sed 's:.*/::')
-			if ! echo "$am_bins_allowed" | grep -q "$am_bin_item$" 2>/dev/null; then
-				rm -Rf "$f"
-			fi
-		done
-	fi
-fi
 
 # Check if appimagetool is installed, and if it is not installed, download and use it where it is needed
 _download_appimagetool() {
