Add "xdg-user-dirs" among dependences
See https://github.com/ivan-hc/AM/issues/293#issuecomment-2027735308

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -1,7 +1,9 @@
 #!/usr/bin/env bash
 
 DIR="$( cd "$( dirname "$0" )" && pwd )"
-CLI=$(echo $(basename "$0"))
+CLI=$(echo "$(basename "$0")")
+
+if ! command -v xdg-user-dir 1>/dev/null; then echo ' ⚠️ WARNING: "xdg-user-dir" command not found (required by modules)'; exit; fi
 
 function _am(){
 	AMCLI="am"
@@ -88,7 +90,7 @@ function _appman() {
 		echo -e '\nIn case of problems, use the option "-h".'
 		echo '--------------------------------------------------------------------------'
 	fi
-	initialize_appman $(<"$APPMANCONFIG"/appman-config)
+	initialize_appman "$(<"$APPMANCONFIG"/appman-config)"
 }
 
 if [[ "$DIR/$CLI" == "/usr/local/bin/am" ]] 2>/dev/null; then
