Separate sub-functions & make main section titles stand out

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -12,7 +12,7 @@ CLI=$(basename "$0")
 
 # Determine system architecture and current user
 arch="$HOSTTYPE"
-currentuser="$USER"
+export currentuser="$USER"
 
 # XDG Variables
 DATADIR="${XDG_DATA_HOME:-$HOME/.local/share}"
@@ -21,39 +21,17 @@ CACHEDIR="${XDG_CACHE_HOME:-$HOME/.cache}"
 
 APPMANCONFIG="$CONFIGDIR/appman"
 
-# Prevent the use of "sudo" ("AM")
-function _no_sudo() {
-	if [ -n "$SUDO_COMMAND" ]; then
-		printf '\n Please do not use "sudo" to execute "'"$CLI"'", try again.\n\n'
-		printf '\n Please do not use "sudo" to execute %s, try again.\n\n' "$CLI"
-		exit 1
-	fi
-}
-
-function web_get() {
-	wget -q "${@}"
-}
-
-function _make_upper() {
-	tr '[:lower:]' '[:upper:]'
-}
-
-function _make_lower() {
-	tr '[:upper:]' '[:lower:]'
-}
-# Export functions to use them also in modules
-export -f web_get _make_upper _make_lower
-
+export SCRIPTDIR="$(if command -v xdg-user-dir &>/dev/null; then xdg-user-dir DESKTOP; else echo $HOME; fi)"
 
 # Determine sytem package manager
 function _system_package_manager_check() {
-    for cmd in dnf pacman emerge zypper apt-get apk; do
-        if command -v $cmd &> /dev/null; then
-            osPKGman="$cmd"
-            return
-        fi
-    done
-    osPKGman=""
+	for cmd in dnf pacman emerge zypper apt-get apk; do
+		if command -v $cmd &> /dev/null; then
+		osPKGman="$cmd"
+		return
+		fi
+	done
+	osPKGman=""
 }
 
 # Colors
@@ -69,23 +47,10 @@ function _no_sudo() {
 
 _no_sudo
 
-# Common variables to handle user's XDG directories
-SCRIPTDIR="$(if command -v xdg-user-dir &>/dev/null; then xdg-user-dir DESKTOP; else echo $HOME; fi)"
-
-# Check XDG variables ("APPMAN")
-if [ -n "$XDG_CONFIG_HOME" ]; then
-	APPMANCONFIG="$XDG_CONFIG_HOME/appman"
-else
-	APPMANCONFIG="$HOME/.config/appman"
-fi
-
-if [ -n "$XDG_DATA_HOME" ]; then
-	DATADIR="$XDG_DATA_HOME"
-else
-	DATADIR="$HOME/.local/share"
-fi
-
+#####################
 # "AM" CORE VARIABLES
+#####################
+
 function _am() {
 	AMCLI="am"
 	AMCLIPATH="$AMCLI"
@@ -98,7 +63,9 @@ function _am() {
 	mkdir -p "$AMPATH"/modules
 }
 
+#######################################
 # "APPMAN" CORE VARIABLES AND FUNCTIONS
+#######################################
 
 function _patch_bashrc_and_profile() {
 	# Fix order in "echo $PATH" in case "$HOME/.local/bin" is placed at the beginning instead of the end
@@ -121,52 +88,48 @@ function _patch_bashrc_and_profile() {
 	fi
 }
 
+function _appman_initialize() {
+	APPSDIR=$1
+	mkdir -p ~/"$APPSDIR"/appman/.cache
+	mkdir -p ~/"$APPSDIR"/appman/modules
+	mkdir -p ~/.local/bin "$DATADIR"/applications "$DATADIR"/icons
+	AMCLI="appman"
+	AMCLIPATH="$DIR/$AMCLI"
+	SUDOCOMMAND=""
+	COMPLETIONPATH="$HOME"
+	COMPLETIONFILE=".bash_completion"
+	APPSPATH="$HOME/$APPSDIR"
+	AMPATH="$HOME/$APPSDIR/$AMCLI"
+}
+
+function _appman_prompt_for_directory() {
+	local location
+	read -r -ep "Please, write the name or the path of your custom application's folder: $(echo -e '\n\n '$HOME'/')" location
+	echo "$location"
+}
+
+function _appman_validate_directory() {
+	local location=$1
+	if [[ "$location" == "" ]]; then
+		echo -e "--------------------------------------------------------------------------"
+		echo "OPERATION ABORTED!"
+		exit  1
+	elif [[ "$location" == ".local/bin" ]]; then
+		echo -e "--------------------------------------------------------------------------\n"
+		echo -e " 💀 ERROR, you can't install applications into a '$PATH'\n\n The directory ~/.local/bin and 'bin' folders are used for executables.\n\n Please, choose a different path and retry! \n"
+		echo -e "--------------------------------------------------------------------------\n"
+		exit  1
+	else
+		local location_appman="${location/#$HOME}"
+		location_appman="${location_appman// /-}"
+		location_appman="${location_appman#/}"
+		location_appman="${location_appman%/}"
+		echo "$location_appman"
+	fi
+}
+
 function _appman() {
-
-	function _appman_initialize() {
-		APPSDIR=$1
-		mkdir -p ~/"$APPSDIR"/appman/.cache
-		mkdir -p ~/"$APPSDIR"/appman/modules
-		mkdir -p ~/.local/bin "$DATADIR"/applications "$DATADIR"/icons
-		AMCLI="appman"
-		AMCLIPATH="$DIR/$AMCLI"
-		SUDOCOMMAND=""
-		COMPLETIONPATH="$HOME"
-		COMPLETIONFILE=".bash_completion"
-		APPSPATH="$HOME/$APPSDIR"
-		AMPATH="$HOME/$APPSDIR/$AMCLI"
-	}
-
-	# Helper functions don't need to be defined inside the parent function
-	function _appman_prompt_for_directory() {
-		local location
-		read -r -ep "Please, write the name or the path of your custom application's folder: $(echo -e '\n\n '$HOME'/')" location
-		echo "$location"
-	}
-
-	function _appman_validate_directory() {
-		local location=$1
-		if [[ "$location" == "" ]]; then
-			echo -e "--------------------------------------------------------------------------"
-			echo "OPERATION ABORTED!"
-			exit  1
-		elif [[ "$location" == ".local/bin" ]]; then
-			echo -e "--------------------------------------------------------------------------\n"
-			echo -e " 💀 ERROR, you can't install applications into a '$PATH'\n\n The directory ~/.local/bin and 'bin' folders are used for executables.\n\n Please, choose a different path and retry! \n"
-			echo -e "--------------------------------------------------------------------------\n"
-			exit  1
-		else
-			local location_appman="${location/#$HOME}"
-			location_appman="${location_appman// /-}"
-			location_appman="${location_appman#/}"
-			location_appman="${location_appman%/}"
-			echo "$location_appman"
-		fi
-	}
-
 	if [[ ! -f "$APPMANCONFIG"/appman-config ]]; then
-		local location=""
-		local validated_location=""
 		echo "--------------------------------------------------------------------------"
 		echo " >>> Thank you for choosing AppMan!"
 		echo "--------------------------------------------------------------------------"
@@ -179,8 +142,8 @@ function _appman() {
 		echo 'decide to change your choice in the future, first remove all the programs'
 		echo 'and then edit the ~/.config/appman/appman-config text file.'
 		echo -e "--------------------------------------------------------------------------\n"
-		location=$(_appman_prompt_for_directory)
-		validated_location=$(_appman_validate_directory "$location")
+		local location=$(_appman_prompt_for_directory)
+		local validated_location=$(_appman_validate_directory "$location")
 		mkdir -p "$APPMANCONFIG"
 		echo "$validated_location" >> "$APPMANCONFIG"/appman-config
 		echo '--------------------------------------------------------------------------'
@@ -194,7 +157,10 @@ function _appman() {
 	_patch_bashrc_and_profile
 }
 
+########################################
 # DETERMINE WHEN TO USE "AM" OR "APPMAN"
+########################################
+
 if [[ "$DIR/$CLI" == "/usr/local/bin/am" ]] 2>/dev/null; then
 	_am
 else
@@ -204,12 +170,37 @@ fi
 # Set header authorization if GitHub API key file exists
 [ -f "$AMPATH/ghapikey.txt" ] && HeaderAuthWithGITPAT=" --header \"Authorization: token $(<"$AMPATH/ghapikey.txt")\" "
 
+################
+# DEVELOPER MODE
+################
+
+if test -f "$AMPATH"/betatester; then
+	AMREPO="https://raw.githubusercontent.com/ivan-hc/AM/dev"
+	AMBRANCH=$(basename "$AMREPO")
+fi
+function _betatester_message_on() {
+	if test -f "$AMPATH"/betatester; then
+		echo '--------------------------------------------------------------------------'
+		echo "\"$AMCLI\" $AMVERSION: developer mode" | tr a-z A-Z
+		echo '--------------------------------------------------------------------------'
+	fi
+}
+
+function _use_betatester_on() {
+	touch "$AMPATH"/betatester
+}
+
+function _use_betatester_off() {
+	rm -f "$AMPATH"/betatester
+}
+
+###############################
 # DOWNLOAD PORTABLE DEPENDENCES
+###############################
+
 function _jq_installer() {
 	if ! command -v jq 1>/dev/null; then
-
 		_system_package_manager_check
-
 		if [[ -z "$osPKGman" ]];then
 			echo -e " ${RED}💀 ERROR!\033[0m Missing essential command ${Green}jq\033[0m\n"
 			read -p " Do you wish to install it using $AMCLI (Y,n)? " yn
@@ -237,36 +228,38 @@ function _portable_dependences_setup() {
 	_jq_installer
 }
 
+###########################################
 # FUNCTIONS RELATED TO THE SAFE USE OF "AM"
-function _am_security_check() {
-	function _am_dependences_check() {
-		# Check for essential commands required by the application
-		missing_deps=()
-		AMDEPENDENCES="cat chmod chown curl grep sed wget"
-		for name in $AMDEPENDENCES; do
-			if ! command -v "$name" &>/dev/null; then
-				missing_deps+=("$name")
-			fi
-		done
+###########################################
 
-		# Exit if any essential command is missing
-		if [ -n "$missing_deps" ]; then
-			echo '--------------------------------------------------------------------------'
-			printf " ${RED}💀 ERROR! MISSING ESSENTIAL COMMANDS\033[0m: %s\n\n Install the above and try again! \n" "${missing_deps[*]}"
-			echo '--------------------------------------------------------------------------'
-			echo -e "\n ${Green}List of the $(echo "$AMCLI" | tr a-z A-Z) $AMVERSION core dependences\033[0m:\n"
-			echo $AMDEPENDENCES | tr ' ' ',' | sed 's/,/, /g' | sed 's/^/ /g'
-			echo -e '\n--------------------------------------------------------------------------'
-			echo " If this message appears it is because you are missing some dependency"
-			echo " and if its the first time its because something new has been introduced."
-			echo -e "\n See ${LightBlue}https://github.com/ivan-hc/AM#dependences\033[0m for more information"
-			echo '--------------------------------------------------------------------------'
-			exit 1
+function _am_dependences_check() {
+	# Check for essential commands required by the application
+	missing_deps=()
+	AMDEPENDENCES="cat chmod chown curl grep sed wget"
+	for name in $AMDEPENDENCES; do
+		if ! command -v "$name" &>/dev/null; then
+			missing_deps+=("$name")
 		fi
-	}
+	done
 
+	# Exit if any essential command is missing
+	if [ -n "$missing_deps" ]; then
+		echo '--------------------------------------------------------------------------'
+		printf " ${RED}💀 ERROR! MISSING ESSENTIAL COMMANDS\033[0m: %s\n\n Install the above and try again! \n" "${missing_deps[*]}"
+		echo '--------------------------------------------------------------------------'
+		echo -e "\n ${Green}List of the $(echo "$AMCLI" | tr a-z A-Z) $AMVERSION core dependences\033[0m:\n"
+		echo $AMDEPENDENCES | tr ' ' ',' | sed 's/,/, /g' | sed 's/^/ /g'
+		echo -e '\n--------------------------------------------------------------------------'
+		echo " If this message appears it is because you are missing some dependency"
+		echo " and if its the first time its because something new has been introduced."
+		echo -e "\n See ${LightBlue}https://github.com/ivan-hc/AM#dependences\033[0m for more information"
+		echo '--------------------------------------------------------------------------'
+		exit 1
+	fi
+}
+
+function _am_security_check() {
 	_am_dependences_check
-
 	# Check and create the $AMPATH directory if it does not exist
 	if [ ! -d "$AMPATH" ]; then
 		$SUDOCOMMAND mkdir -p "$AMPATH"
@@ -275,13 +268,16 @@ function _am_security_check() {
 
 # Function to check online connections (uses github.com by default, as the database and CLI itself are stored/hosted there)
 function _online_check() {
-	if ! web_get --tries=10 --timeout=20 --spider https://github.com; then
+	if ! wget -q --tries=10 --timeout=20 --spider https://github.com; then
 		echo -e "\n $AMCLI is offline, please check your internet connection and try again\n"
 		exit
 	fi
 }
 
+#######################
 # SECURE INSTALLED APPS
+#######################
+
 function _prevent_apps_from_being_removed_by_third_parties() {
 	# Add a security layer to scripts named "remove" of installed apps to prevent file removal by non-privileged users
 	if [ $AMCLI == am ] 2>/dev/null; then
@@ -295,34 +291,35 @@ function _prevent_apps_from_being_removed_by_third_parties() {
 	fi
 }
 
+###########################################
 # FUNCTIONS RELATED TO THE DATABASE OF APPS
+###########################################
+
+function _am_newrepo_check() {
+	# Determine if the CLI uses the "main" branch of https://github.com/ivan-hc/AM or an alternative one
+	if [[ -f "$AMPATH"/new-repo.txt ]]; then
+		AMREPO=$(<"$AMPATH/new-repo.txt") # Utilizing command substitution with < for more efficient file reading
+		export AMBRANCH=$(basename "$AMREPO")
+		export APPSDB="$AMREPO/programs/$arch"
+		export APPSLISTDB="$AMREPO/programs/$arch-apps"
+		export LIBSLISTDB="$AMREPO/programs/libs-list"
+		if [[ "$*" != "newrepo off" ]]; then
+			echo '--------------------------------------------------------------------------'
+			echo " Source: $AMREPO"
+			echo '--------------------------------------------------------------------------'
+		fi
+	else
+		export APPSDB="$AMREPO/programs/$arch"
+		export APPSLISTDB="$AMREPO/programs/$arch-apps"
+		export LIBSLISTDB="$AMREPO/programs/libs-list"
+	fi
+}
+
 function _am_databases_check() {
 	# Determine catalogue in use
 	export AMCATALOGUEMARKDOWNS="https://raw.githubusercontent.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/main/apps"
 	export AMCATALOGUEICONS="https://raw.githubusercontent.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/main/icons"
-
-	function _am_newrepo_check() {
-		# Determine if the CLI uses the "main" branch of https://github.com/ivan-hc/AM or an alternative one
-		if [[ -f "$AMPATH"/new-repo.txt ]]; then
-			AMREPO=$(<"$AMPATH/new-repo.txt") # Utilizing command substitution with < for more efficient file reading
-			AMBRANCH=$(basename "$AMREPO")
-			APPSDB="$AMREPO/programs/$arch"
-			APPSLISTDB="$AMREPO/programs/$arch-apps"
-			LIBSLISTDB="$AMREPO/programs/libs-list"
-			if [[ "$*" != "newrepo off" ]]; then
-				echo '--------------------------------------------------------------------------'
-				echo " Source: $AMREPO"
-				echo '--------------------------------------------------------------------------'
-			fi
-		else
-			APPSDB="$AMREPO/programs/$arch"
-			APPSLISTDB="$AMREPO/programs/$arch-apps"
-			LIBSLISTDB="$AMREPO/programs/libs-list"
-		fi
-	}
-
 	_am_newrepo_check
-
 	# To implement future application database changes
 	if [ -f "$AMPATH/neodb" ]; then
 		if grep -q "://" "$AMPATH/neodb"; then
@@ -339,7 +336,10 @@ function _am_databases_check() {
 	fi
 }
 
-# Check version of the installed apps
+#####################################
+# CHECK VERSION OF THE INSTALLED APPS
+#####################################
+
 function _check_version() {
 	rm -f $AMPATH/.cache/version-args
 	cd $APPSPATH &&
@@ -388,7 +388,10 @@ function _check_version() {
 	done
 }
 
-# Functions related to internal options to enable/disable bash (and zsh) completion.
+###################################################################################
+# FUNCTIONS RELATED TO INTERNAL OPTIONS TO ENABLE/DISABLE BASH (AND ZSH) COMPLETION
+###################################################################################
+
 function _use_disable-completion() {
 	if [ "$(grep -o "$AMCLI" 0<"$COMPLETIONPATH/$COMPLETIONFILE" | head -1)" == "$AMCLI" ]; then
 		grep -v 'complete -W "$(cat '"$AMPATH"'/list 2>/dev/null)" '"$AMCLI"'' "$COMPLETIONPATH/$COMPLETIONFILE" > "$AMPATH"/$COMPLETIONFILE.backup &&
@@ -433,59 +436,6 @@ function _use_enable_completion() {
 	fi
 }
 
-# Function for the option that helps "AM" function like "AppMan", via alias
-function _use_appman() {
-	_online_check
-	if [ "$AMCLI" == appman ] 2>/dev/null; then
-		echo " This function only works for AM"
-		exit
-	fi
-	if test -f /opt/am/appman; then
-		_appman
-		echo -e "Please run '${RED}alias am=/opt/am/appman\033[0m' to made 'AM' act exactly like 'AppMan' for\nthe current session or save this command to your '"'~/.bashrc'"' file to make the\nchanges permanent. Visit ${LightBlue}https://github.com/ivan-hc/appman\033[0m for more!"
-	else
-		_appman
-		web_get "$AMREPO"/APP-MANAGER -O /opt/am/appman && chmod a+x /opt/am/appman
-		echo -e "Please run '${RED}alias am=/opt/am/appman\033[0m' to made 'AM' act exactly like 'AppMan' for\nthe current session or save this command to your '"'~/.bashrc'"' file to make the\nchanges permanent."
-	fi
-}
-
-# Handle external modules
-function _use_module() {
-	# Test if module exists
-	if ! test -f "$AMPATH/modules/$MODULE"; then
-		wget -q "$AMREPO/modules/$MODULE" -O "$AMPATH/modules/$MODULE"
-		chmod a+x "$AMPATH/modules/$MODULE"
-	fi
-	# Source module
-	source "$AMPATH/modules/$MODULE" "$@"
-}
-
-# DEVELOPER MODE
-if test -f "$AMPATH"/betatester; then
-	AMREPO="https://raw.githubusercontent.com/ivan-hc/AM/dev"
-	AMBRANCH=$(basename "$AMREPO")
-fi
-function _betatester_message_on() {
-	if test -f "$AMPATH"/betatester; then
-		echo '--------------------------------------------------------------------------'
-		echo "\"$AMCLI\" $AMVERSION: developer mode" | tr a-z A-Z
-		echo '--------------------------------------------------------------------------'
-	fi
-}
-
-function _use_betatester_on() {
-	touch "$AMPATH"/betatester
-}
-
-function _use_betatester_off() {
-	rm -f "$AMPATH"/betatester
-}
-
-_am_security_check
-_prevent_apps_from_being_removed_by_third_parties 2> /dev/null
-_am_databases_check
-
 # Generate a list of words to use in bash completion
 rm -rf "$AMPATH/options"
 cat <<-HEREDOC >> "$AMPATH/options"
@@ -529,7 +479,45 @@ cat <<-HEREDOC >> "$AMPATH/options"
 	--user
 HEREDOC
 
-# ALL THE OPTIONS
+#############################################
+# OTHER FUNCTIONS RELATED TO INTERNAL OPTIONS
+#############################################
+
+# Function for the option "appman" or "--user" that helps "AM" function like "AppMan", via alias
+function _use_appman() {
+	_online_check
+	if [ "$AMCLI" == appman ] 2>/dev/null; then
+		echo " This function only works for AM"
+		exit
+	fi
+	if test -f /opt/am/appman; then
+		_appman
+		echo -e "Please run '${RED}alias am=/opt/am/appman\033[0m' to made 'AM' act exactly like 'AppMan' for\nthe current session or save this command to your '"'~/.bashrc'"' file to make the\nchanges permanent. Visit ${LightBlue}https://github.com/ivan-hc/appman\033[0m for more!"
+	else
+		_appman
+		wget -q "$AMREPO"/APP-MANAGER -O /opt/am/appman && chmod a+x /opt/am/appman
+		echo -e "Please run '${RED}alias am=/opt/am/appman\033[0m' to made 'AM' act exactly like 'AppMan' for\nthe current session or save this command to your '"'~/.bashrc'"' file to make the\nchanges permanent."
+	fi
+}
+
+#############################################
+# FUNCTION TO HANDLE ALL THE EXTERNAL MODULES
+#############################################
+
+function _use_module() {
+	# Test if module exists
+	if ! test -f "$AMPATH/modules/$MODULE"; then
+		wget -q "$AMREPO/modules/$MODULE" -O "$AMPATH/modules/$MODULE"
+		chmod a+x "$AMPATH/modules/$MODULE"
+	fi
+	# Source module
+	source "$AMPATH/modules/$MODULE" "$@"
+}
+
+_am_security_check
+_prevent_apps_from_being_removed_by_third_parties 2> /dev/null
+_am_databases_check
+
 case "$1" in
 	'')
 		echo -e "\n USAGE: '$AMCLI [option]'\n        '$AMCLI [option] [argument]'\n\n Run the '$AMCLI -h' command to find out more\n"
