Add "file: command not found" message

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -196,6 +196,8 @@ _clean_amcachedir() {
 file() {
 	if command -v file >/dev/null 2>&1; then
 		command file "$@"
+	else
+		>&2 printf $"file: command not found\n\n"
 	fi
 }
 
