Updated curl "Not Found" error checking for digest file curl search loop. (#2164)

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -1437,11 +1437,11 @@ _use_verify() {
 				# Search other sources if no zsync file
 				for ext in digest DIGEST sha512 sha256 sha1 md5; do
 					digest=$(curl -Ls "$download_url.$ext")
-					if ! echo "$digest" | grep -qi "not found"; then
+					if ! echo "$digest" | grep -qi "not found\|access denied"; then
 						break
 					fi
 				done
-				if echo "$digest" | grep -qi "not found"; then
+				if echo "$digest" | grep -qi "not found\|access denied"; then
 					return 1
 				fi
 			fi
