Installing ffwa-* requires "Firefox" to be installed

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -703,29 +703,31 @@ case "$1" in
 										
 										if grep -q '.deb' ./$arg; then
 											if ! command -v ar 1>/dev/null; then
-												echo ' 💀 ERROR: YOU CANNOT INSTALL "'$(echo '"'$arg'"' | tr a-z A-Z)'" WITHOUT INSTALLING "BINUTILS"!'
-												break
+												echo ' 💀 ERROR: YOU CANNOT INSTALL "'$(echo '"'$arg'"' | tr a-z A-Z)'" WITHOUT INSTALLING "BINUTILS"!'; break
+											fi
+										fi
+										
+										if grep -q 'ffwa-' ./$arg; then
+											if ! command -v ar 1>/dev/null; then
+												echo ' 💀 ERROR: YOU CANNOT INSTALL "'$(echo '"'$arg'"' | tr a-z A-Z)'" WITHOUT INSTALLING "FIREFOX"!'; break
 											fi
 										fi
 										
 										if grep -q '.tar' ./$arg; then
 											if ! command -v tar 1>/dev/null; then
-												echo ' 💀 ERROR: YOU CANNOT INSTALL "'$(echo '"'$arg'"' | tr a-z A-Z)'" WITHOUT INSTALLING "TAR"!'
-												break
+												echo ' 💀 ERROR: YOU CANNOT INSTALL "'$(echo '"'$arg'"' | tr a-z A-Z)'" WITHOUT INSTALLING "TAR"!'; break
 											fi
 										fi
 										
 										if grep -q '.zip' ./$arg; then
 											if ! command -v unzip 1>/dev/null; then
-												echo ' 💀 ERROR: YOU CANNOT INSTALL "'$(echo '"'$arg'"' | tr a-z A-Z)'" WITHOUT INSTALLING "UNZIP"!'
-												break
+												echo ' 💀 ERROR: YOU CANNOT INSTALL "'$(echo '"'$arg'"' | tr a-z A-Z)'" WITHOUT INSTALLING "UNZIP"!'; break
 											fi
 										fi
 										
 										if grep -q 'zsync /opt' ./$arg; then
 											if ! command -v zsync 1>/dev/null; then
-												echo ' 💀 ERROR: YOU CANNOT INSTALL "'$(echo '"'$arg'"' | tr a-z A-Z)'" WITHOUT INSTALLING "ZSYNC"!'
-												break
+												echo ' 💀 ERROR: YOU CANNOT INSTALL "'$(echo '"'$arg'"' | tr a-z A-Z)'" WITHOUT INSTALLING "ZSYNC"!'; break
 											fi
 										fi
 										
