Add option --location to set local directory for AppMan's apps

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-AMVERSION="10.3"
+AMVERSION="10.3-1"
 
 # Determine main repository and branch
 AMREPO="https://raw.githubusercontent.com/ivan-hc/AM/main"
@@ -338,6 +338,42 @@ NOTE: If no input is given then \"~/Applications\" will be used as default
 
 if you wish to later change the location, first remove all the programs and then edit the \"$APPMANCONFIG/appman-config\" file.")
 
+_appman_create_path() {
+	location="$(echo "$location" | sed 's/[ \t]/-/g; s|^\./||' 2>/dev/null)"
+	[ -z "$location" ] && location="$HOME/Applications"
+	if printf '%s' "$location" | grep -q '`\|\$(\|"\|\\'; then
+		echo "$DIVIDING_LINE"
+		echo $" 💀 ERROR: unsupported characters in path, please use a plain path"
+		echo "$DIVIDING_LINE"
+		exit 1
+	fi
+	case "$location" in
+		"~")   location="$HOME" ;;
+		"~/"*) location="$HOME/${location#\~/}" ;;
+	esac
+	location=$(eval "printf '%s' \"$location\"")
+	if ! echo "$location" | grep "^/" >/dev/null 2>&1; then
+		location="$HOME/$location"
+	fi
+	if echo "$location" | grep "$BINDIR" >/dev/null 2>&1; then
+		echo "$DIVIDING_LINE"
+		echo $" 💀 ERROR, you can't install applications in \"$BINDIR\""
+		echo $" $BINDIR is normally used for executables, Please choose a different path and retry!"
+		echo "$DIVIDING_LINE"
+		exit  1
+	elif ! mkdir -p "$location" 2>/dev/null || [ ! -w "$location" ]; then
+		echo $" 💀 ERROR: You don't have write access to $location or it is invalid"
+		exit 1
+	fi
+	mkdir -p "$APPMANCONFIG" || exit 1
+	echo "${location%/}" > "$APPMANCONFIG"/appman-config || exit 1
+	echo "$DIVIDING_LINE"
+	echo $" You are ready! Start installing your favorite apps locally!"
+	echo $" All apps will be installed in $location"
+	echo $" In case of problems, use the option \"-h\"."
+	echo "$DIVIDING_LINE"
+}
+
 _appman_check() {
 	if [ ! -f "$APPMANCONFIG"/appman-config ]; then
 		echo "$DIVIDING_LINE"
@@ -346,39 +382,14 @@ _appman_check() {
 		echo "$APPMAN_SETUP_MSG" | _fit
 		echo "$DIVIDING_LINE"
 		read -r -ep $" Write the path or just press enter to use default:$(printf "\n\n ")" location
-		location="$(echo "$location" | sed 's/[ \t]/-/g; s|^\./||' 2>/dev/null)"
-		[ -z "$location" ] && location="$HOME/Applications"
-		if printf '%s' "$location" | grep -q '`\|\$(\|"\|\\'; then
-			echo "$DIVIDING_LINE"
-			echo $" 💀 ERROR: unsupported characters in path, please use a plain path"
-			echo "$DIVIDING_LINE"
-			exit 1
-		fi
-		case "$location" in
-			"~")   location="$HOME" ;;
-			"~/"*) location="$HOME/${location#\~/}" ;;
-		esac
-		location=$(eval "printf '%s' \"$location\"")
-		if ! echo "$location" | grep "^/" >/dev/null 2>&1; then
-			location="$HOME/$location"
-		fi
-		if echo "$location" | grep "$BINDIR" >/dev/null 2>&1; then
-			echo "$DIVIDING_LINE"
-			echo $" 💀 ERROR, you can't install applications in \"$BINDIR\""
-			echo $" $BINDIR is normally used for executables, Please choose a different path and retry!"
-			echo "$DIVIDING_LINE"
-			exit  1
-		elif ! mkdir -p "$location" 2>/dev/null || [ ! -w "$location" ]; then
-			echo $" 💀 ERROR: You don't have write access to $location or it is invalid"
-			exit 1
-		fi
-		mkdir -p "$APPMANCONFIG" || exit 1
-		echo "${location%/}" > "$APPMANCONFIG"/appman-config || exit 1
-		echo "$DIVIDING_LINE"
-		echo $" You are ready! Start installing your favorite apps locally!"
-		echo $" All apps will be installed in $location"
-		echo $" In case of problems, use the option \"-h\"."
-		echo "$DIVIDING_LINE"
+		_appman_create_path
+	fi
+}
+
+_use_location() {
+	if [ ! -f "$APPMANCONFIG"/appman-config ]; then
+		location="$(echo "$@" | cut -f2- -d ' ' | tr ' ' '\n' | grep -v -- "^-\|^$1$")"
+		_appman_create_path
 	fi
 }
 
@@ -980,7 +991,7 @@ available_options="about add apikey backup clean clone config disable downgrade 
 	install install-appimage integrate launcher list lock neodb newrepo nolibfuse off on overwrite purge query reinstall relocate remove sandbox \
 	search select sync template test translate unhide unlock update upgrade --all --appimages --apps --byname --clone --config --convert --debug \
 	--devmode-disable --devmode-enable --disable-notifications --enable-notifications --force-latest --help --home --icons \
-	-ias --launcher --less --pkg --portable --rollback --disable-sandbox --relocate --sandbox --system --translate --user $third_party_flags"
+	-ias --launcher --less --location --pkg --portable --rollback --disable-sandbox --relocate --sandbox --system --translate --user $third_party_flags"
 
 _completion_lists() {
 	# Remove existing lists and download new ones
@@ -2258,6 +2269,9 @@ case "$1" in
 	'force-latest'|'--force-latest')
 		_use_force_latest "$@"
 		;;
+	'--location')
+		_use_location "$@"
+		;;
 	'newrepo'|'neodb')
 		_use_newrepo "$@"
 		;;
@@ -2352,6 +2366,7 @@ case "$1" in
 		description_launcher=$(echo $"Description: Drag/drop one or more AppImages in the terminal and embed them in the apps menu and customize a command to use from the CLI.
 
 			NOTE that \"--launcher\" can be used as a flag in \"-u\" to try to update the integrated AppImages (see \"-u\"). This works only if \"appimageupdatetool\" is installed and delta updates are supported. This flag does not work miracles, I strongly suggest to use options \"-ia\" and \"-e\" instead.")
+		description_location="Description: Set local directory for AppMan's applications."
 		description_system=$(echo $"Description: Switch \"AM\" back to \"AM\" from \"AppMan Mode\" (see \"--user\").")
 		description_user=$(echo $"Description: Made \"AM\" run in \"AppMan Mode\", locally, useful for unprivileged users. This option only works with \"AM\".
 
@@ -2669,6 +2684,12 @@ case "$1" in
 					${LightBlue}$AMCLI --launcher /path/to/\${APPIMAGE}\033[0m
 
 			$description_launcher
+
+			${Gold}--location\033[0m
+
+					${LightBlue}$AMCLI --location /path/to/applications\033[0m
+
+			$description_location
 
 			${Gold}--system\033[0m
 
