workaround bsd sed when there is no gsed

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -52,11 +52,8 @@ if [ -n "${SUDO_USER:-$DOAS_USER}" ]; then
 	exit 1
 fi
 
-# check what sed we have
-if ! sed --version 2>/dev/null | grep -qi gnu && ! command -v gsed 1>/dev/null; then
-  echo "$DIVIDING_LINE"
-  echo " 💀 WARNING: You don't have GNU sed, things will likely break"
-  echo "$DIVIDING_LINE"
+if ! sed --version 2>/dev/null | grep -qi "gnu"; then
+	NO_SED_I=true
 fi
 
 _create_cache_dir() {
@@ -84,11 +81,27 @@ less() {
 
 # Force usage of a GNU implementation of "sed"
 sed() {
-    if command -v gsed >/dev/null 2>&1; then
-        command gsed "$@"
-    else
-        command sed "$@"
-    fi
+	if [ "$NO_SED_I" = true ] && [ "$1" = '-i' ]; then
+		if command -v gsed >/dev/null 2>&1; then
+			command gsed "$@"
+		else
+			shift
+			tmpsedYYY="$(command sed "$@" 2>/dev/null)"
+			while [ "$#" -gt 1 ]; do shift; done
+			if [ -n "$tmpsedYYY" ] && [ -f "$1" ]; then
+				echo "$tmpsedYYY" > "$1"
+				unset tmpsedYYY
+			else
+				>&2 echo " 💀 ERROR: Your version of sed does not support '-i' flag"
+				>&2 echo " without extension, we tried to workaround and failed"
+				>&2 echo " Please install gsed"
+				unset tmpsedYYY
+				return 1
+			fi
+		fi
+	else
+		command sed "$@"
+	fi
 }
 
 ################################################################################
