"AM" 2.7.0 RELEASED!
Added a dependency check at the beginning of the main script to prevent installation errors.

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -1,5 +1,11 @@
 #!/usr/bin/env bash
 
+for name in "ar" "cat" "convert" "curl" "echo" "egrep" "grep" "tar" "test" "unzip" "wget" "zsync"
+do
+  [[ $(which $name 2>/dev/null) ]] || { echo "" && echo -e 'ERROR: "'$name'" not found, required by some installation scripts.';deps=1; }
+done
+[[ $deps -ne 1 ]] || { echo -e "\nInstall the above and try again\n";exit 1; }
+
 URL="https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main"
 arch=$(uname -m)
 currentuser=$(who | awk '{print $1}')
@@ -516,6 +522,6 @@ case "$1" in
 	fi
 	done
 	shift;;
-  'version'|'-v'|'--version') echo "2.6.1-3";;
+  'version'|'-v'|'--version') echo "2.7.0";;
   *) exec /opt/am/APP-MANAGER ;;
 esac
