Add /run/media support to -c in AppImage launchers removal

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-AMVERSION="9.1.1-4"
+AMVERSION="9.1.1-5"
 
 # Determine main repository and branch
 AMREPO="https://raw.githubusercontent.com/ivan-hc/AM/main"
@@ -613,30 +613,32 @@ function _clean_all_tmp_directories_from_appspath() {
 }
 
 function _clean_determine_removable_launchers() {
-	if ! test -f "$APPIMAGENAME" 2>/dev/null; then
-		if ! test -d "$MOUNTPOINTS" 2>/dev/null; then
-			if echo "$MOUNTPOINTS" | grep -q "/media/"; then
-				unmounted_poin="/media"
-			elif echo "$MOUNTPOINTS" | grep -q "/mnt/"; then
-				unmounted_poin="/mnt"
-			fi
-			echo " ✖ ERROR: cannot remove \"$(basename "$var")\""
-			echo "   related AppImage is located in an unmounted path of $unmounted_poin"
-		else
-			rm -f "$var"
-			rm -f "$HOME"/.local/bin/"$launcher2del"*
-			cd "$HOME"/.local/bin && find . -xtype l -delete
+	if echo "$mountpoint" | grep -q "^/media/\|^/mnt/\|^/run/media/" && ! test -d "$mountpoint"; then
+		if echo "$mountpoint" | grep -q "^/media/"; then
+			unmounted_point="/media"
+		elif echo "$mountpoint" | grep -q "^/mnt/"; then
+			unmounted_point="/mnt"
+		elif echo "$mountpoint" | grep -q "^/run/media/"; then
+			unmounted_point="/run/media"
 		fi
+		echo " ✖ ERROR: cannot remove \"$(basename "$var")\""
+		echo "   related AppImage is located in an unmounted path of $unmounted_point"
+	else
+		rm -f "$var"
+		rm -f "$HOME"/.local/bin/"$launcher2del"*
+		cd "$HOME"/.local/bin && find . -xtype l -delete
 	fi
 }
 
 function _clean_launchers() {
-	if test -d "$DATADIR"/applications/AppImages 2>/dev/null; then
+	if test -d "$DATADIR"/applications/AppImages; then
 		for var in "$DATADIR"/applications/AppImages/*.desktop; do
-			APPIMAGENAME=$(grep "Exec=" 0<"$var" 2>/dev/null | head -1 | cut -c 6- | sed 's/\s.*$//')
-			launcher2del=$(basename -- "$(echo "$APPIMAGENAME" | tr '[:upper:]' '[:lower:]')")
-			MOUNTPOINTS=$(echo "$APPIMAGENAME" | cut -d'/' -f1-4)
-			_clean_determine_removable_launchers
+			appimagename=$(grep "Exec=" 0<"$var" 2>/dev/null | head -1 | cut -c 6- | sed 's/\s.*$//') # full path to appimage
+			launcher2del=$(basename -- "$(echo "$appimagename" | tr '[:upper:]' '[:lower:]')") # name of the appimage
+			mountpoint=$(echo "$appimagename" | cut -d'/' -f1-4) # removable mount point where the appimage may be stored
+			if ! test -f "$appimagename"; then
+				_clean_determine_removable_launchers
+			fi
 		done
 		echo ' ✔ Removed orphaned launchers produced with the "--launcher" option'
 		rmdir "$DATADIR"/applications/AppImages
