Add hidden lines to improve next time, for checksum
ref https://github.com/ivan-hc/AM/issues/2360

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -1775,6 +1775,10 @@ _use_verify() {
 						break
 					fi
 				done
+				# Check the online file if no kind of digest file is available
+				#if [ -z "$digest" ] || echo "$digest" | grep -qi "not found\|access denied"; then
+				#	digest=$(_use_online_reading_tool "$download_url" | sha256sum)
+				#fi
 				if [ -z "$digest" ] || echo "$digest" | grep -qi "not found\|access denied"; then
 					return 1
 				fi
