Update APP-MANAGER
- add messages for "hide" and "unhide"

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -810,12 +810,18 @@ _use_hide_unhide() {
 	if [ "$1" = hide ]; then
 		for arg in $entries; do
 			argpath=$(echo "$ARGPATHS" | grep "/$arg$")
-			[ -f "$argpath/remove" ] && mv "$argpath/remove" "$argpath/remove.old"
+			[ -f "$argpath/remove" ] && mv "$argpath/remove" "$argpath/remove.old" \
+			&& echo "✔ $argpath has been hidden" || echo "✖ Can't hide \"$arg\", app already hidden or non-existent"
 		done
 	else
 		for arg in $entries; do
 			[ "$AMCLI" = am ] && [ -f "/opt/$arg/remove.old" ] && mv "/opt/$arg/remove.old" "/opt/$arg/remove"
 			[ -n "$APPMAN_APPSPATH" ] && [ -f "$APPMAN_APPSPATH/$arg/remove.old" ] && mv "$APPMAN_APPSPATH/$arg/remove.old" "$APPMAN_APPSPATH/$arg/remove"
+			if [ "$AMCLI" = am ] && [ -f "/opt/$arg/remove" ] || [ -n "$APPMAN_APPSPATH" ] && [ -f "$APPMAN_APPSPATH/$arg/remove" ]; then
+				echo "✔ \"$arg\" can be managed by \"$AMCLIUPPER\""
+			else
+				echo "✖ \"$arg\" not found"
+			fi
 		done
 	fi
 }
