Update APP-MANAGER: fix https://github.com/ivan-hc/AM/issues/309
..also code refactoring anf fix shellcheck warnings

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -1,20 +1,20 @@
 #!/usr/bin/env bash
 
 DIR="$( cd "$( dirname "$0" )" && pwd )"
-CLI=$(echo "$(basename "$0")")
+CLI=$(basename "$0")
 
 if ! command -v xdg-user-dir 1>/dev/null; then echo ' ⚠️ WARNING: "xdg-user-dir" command not found (required by modules)'; exit; fi
 
 function _am(){
 	AMCLI="am"
-	AMCLIPATH=$AMCLI
+	AMCLIPATH="$AMCLI"
 	SUDOCOMMAND="sudo"
 	COMPLETIONPATH="/etc/bash_completion.d"
 	COMPLETIONFILE="am-completion.sh"
 	APPSPATH="/opt"
 	AMPATH="$APPSPATH/$AMCLI"
-	mkdir -p $AMPATH/.cache
-	mkdir -p $AMPATH/modules
+	mkdir -p "$AMPATH"/.cache
+	mkdir -p "$AMPATH"/modules
 }
 
 function _appman() {
@@ -47,8 +47,8 @@ function _appman() {
 
 	function initialize_appman() {
 		APPSDIR=$1
-		mkdir -p ~/$APPSDIR/appman/.cache
-		mkdir -p ~/$APPSDIR/appman/modules
+		mkdir -p ~/"$APPSDIR"/appman/.cache
+		mkdir -p ~/"$APPSDIR"/appman/modules
 		mkdir -p ~/.local/bin ~/.local/share/applications ~/.local/share/icons
 		AMCLI="appman"
 		AMCLIPATH="$DIR/$AMCLI"
@@ -106,7 +106,7 @@ function _online_check(){
 	fi
 }
 
-if [[ -f $AMPATH/new-repo.txt ]]; then
+if [[ -f "$AMPATH"/new-repo.txt ]]; then
 	AMREPO=$(<"$AMPATH/new-repo.txt") # Utilizing command substitution with < for more efficient file reading
 	if [[ "$@" != "newrepo off" ]]; then
 		echo '--------------------------------------------------------------------------'
@@ -118,20 +118,20 @@ else
 fi
 
 # Determine system architecture and current user
-arch="$HOSTTYPE"
-currentuser="$USER"
+export arch="$HOSTTYPE"
+export currentuser="$USER"
 
 # Check for essential commands required by the application
 missing_deps=()
 for name in cat chmod chown curl grep sed wget; do
-  if ! command -v "$name" &>/dev/null; then
-	printf "\nERROR: command \"%s\" not found, strongly needed by \"%s\"!\n" "$name" "$AMCLI"
+	if ! command -v "$name" &>/dev/null; then
+		printf "\nERROR: command \"%s\" not found, strongly needed by \"%s\"!\n" "$name" "$AMCLI"
 	missing_deps+=("$name")
-  fi
+	fi
 done
 
 # Exit if any essential command is missing
-if [ ! -z "$missing_deps" ]; then
+if [ -n "$missing_deps" ]; then
   printf "\nMissing essential commands: %s\nInstall the above and try again\n\n" "${missing_deps[*]}"
   exit 1
 fi
@@ -182,9 +182,11 @@ function _no_sudo(){
 
 function _patch_bashrc_and_profile(){
 	# Check if the custom PATH is not already in .bashrc, then append it (fix - exclamation mark negates the entire command substitution)
-	if ! grep -q 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' "$HOME/.bashrc"; then
-		echo 'export PATH=$(echo $PATH | tr ":" "\n" | grep -v "/.local/bin" | tr "\n" ":" | sed ''s/.$//'')' >> "$HOME/.bashrc"
-		echo -e 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin\n' >> "$HOME/.bashrc"
+	if test -f "$HOME/.bashrc"; then
+		if ! grep -q 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' "$HOME/.bashrc"; then
+			echo 'export PATH=$(echo $PATH | tr ":" "\n" | grep -v "/.local/bin" | tr "\n" ":" | sed ''s/.$//'')' >> "$HOME/.bashrc"
+			echo -e 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin\n' >> "$HOME/.bashrc"
+		fi
 	fi
 	# Correct the order of .local/bin in .profile if necessary
 	if test -f "$HOME/.profile"; then
@@ -209,16 +211,16 @@ function _patch_bashrc_and_profile(){
 
 case "$1" in
 
-  '') printf "\n USAGE: '$AMCLI [option]'\n        '$AMCLI [option] [argument]'\n\n Run the '$AMCLI -h' command to find out more\n\n";;
+  '')	echo -e "\n USAGE: '$AMCLI [option]'\n        '$AMCLI [option] [argument]'\n\n Run the '$AMCLI -h' command to find out more\n";;
 
   '-h'|'help')
 
-	if ! test -f $AMPATH/modules/help.am; then
-		wget -q $AMREPO/modules/help.am -O $AMPATH/modules/help.am
-		chmod a+x $AMPATH/modules/help.am
+	if ! test -f "$AMPATH"/modules/help.am; then
+		wget -q "$AMREPO"/modules/help.am -O "$AMPATH"/modules/help.am
+		chmod a+x "$AMPATH"/modules/help.am
 	fi
 
-	source $AMPATH/modules/help.am
+	source "$AMPATH"/modules/help.am
   	;;
 
   '-a'|'about'|'-l'|'list'|'-q'|'query')
@@ -226,36 +228,36 @@ case "$1" in
 	_no_sudo
 	_online_check
 
-	[[ -f $AMPATH/modules/database.am ]] || {
-		wget -q $AMREPO/modules/database.am -O $AMPATH/modules/database.am
-		chmod a+x $AMPATH/modules/database.am
+	[[ -f "$AMPATH"/modules/database.am ]] || {
+		wget -q "$AMREPO"/modules/database.am -O "$AMPATH"/modules/database.am
+		chmod a+x "$AMPATH"/modules/database.am
 	}
 
-	source $AMPATH/modules/database.am "$@"
+	source "$AMPATH"/modules/database.am "$@"
 	;;
 
   '-b'|'backup'|'-o'|'overvrite'|'lock'|'unlock')
 
 	_no_sudo
 
-	if ! test -f $AMPATH/modules/no-updates.am; then
-		wget -q $AMREPO/modules/no-updates.am -O $AMPATH/modules/no-updates.am
-		chmod a+x $AMPATH/modules/no-updates.am
+	if ! test -f "$AMPATH"/modules/no-updates.am; then
+		wget -q "$AMREPO"/modules/no-updates.am -O "$AMPATH"/modules/no-updates.am
+		chmod a+x "$AMPATH"/modules/no-updates.am
 	fi
 
-	source $AMPATH/modules/no-updates.am "$@"
+	source "$AMPATH"/modules/no-updates.am "$@"
 	;;
 
   '-c'|'clean')
 
   	_no_sudo
 
-	if ! test -f $AMPATH/modules/clean.am; then
-		wget -q $AMREPO/modules/clean.am -O $AMPATH/modules/clean.am
-		chmod a+x $AMPATH/modules/clean.am
+	if ! test -f "$AMPATH"/modules/clean.am; then
+		wget -q "$AMREPO"/modules/clean.am -O "$AMPATH"/modules/clean.am
+		chmod a+x "$AMPATH"/modules/clean.am
 	fi
 
-	source $AMPATH/modules/clean.am
+	source "$AMPATH"/modules/clean.am
 	;;
 
   '-d'|'download')
@@ -263,58 +265,58 @@ case "$1" in
 	_no_sudo
 	_online_check
 
-	if ! test -f $AMPATH/modules/download.am; then
-		wget -q $AMREPO/modules/download.am -O $AMPATH/modules/download.am
-		chmod a+x $AMPATH/modules/download.am
+	if ! test -f "$AMPATH"/modules/download.am; then
+		wget -q "$AMREPO"/modules/download.am -O "$AMPATH"/modules/download.am
+		chmod a+x "$AMPATH"/modules/download.am
 	fi
 
-	source $AMPATH/modules/download.am "$@"
+	source "$AMPATH"/modules/download.am "$@"
 	;;
 
   '-f'|'files')
 
   	_no_sudo
 
-	if ! test -f $AMPATH/modules/files.am; then
-		wget -q $AMREPO/modules/files.am -O $AMPATH/modules/files.am
-		chmod a+x $AMPATH/modules/files.am
+	if ! test -f "$AMPATH"/modules/files.am; then
+		wget -q "$AMREPO"/modules/files.am -O "$AMPATH"/modules/files.am
+		chmod a+x "$AMPATH"/modules/files.am
 	fi
 
-	source $AMPATH/modules/files.am
+	source "$AMPATH"/modules/files.am
 	;;
 
   '-H'|'--home'|'--firejail'|'--sandbox')
 
 	_no_sudo
 
-	if ! test -f $AMPATH/modules/sandboxes.am; then
-		wget -q $AMREPO/modules/sandboxes.am -O $AMPATH/modules/sandboxes.am
-		chmod a+x $AMPATH/modules/sandboxes.am
+	if ! test -f "$AMPATH"/modules/sandboxes.am; then
+		wget -q "$AMREPO"/modules/sandboxes.am -O "$AMPATH"/modules/sandboxes.am
+		chmod a+x "$AMPATH"/modules/sandboxes.am
 	fi
 
-	source $AMPATH/modules/sandboxes.am "$@"
+	source "$AMPATH"/modules/sandboxes.am "$@"
 	;;
 
   '-i'|'install')
 
 	_online_check
 
-	if ! test -f $AMPATH/modules/install.am; then
-		wget -q $AMREPO/modules/install.am -O $AMPATH/modules/install.am
-		chmod a+x $AMPATH/modules/install.am
+	if ! test -f "$AMPATH"/modules/install.am; then
+		wget -q "$AMREPO"/modules/install.am -O "$AMPATH"/modules/install.am
+		chmod a+x "$AMPATH"/modules/install.am
 	fi
 
-	source $AMPATH/modules/install.am "$@"
+	source "$AMPATH"/modules/install.am "$@"
 	;;
 
   '-R'|'-r'|'remove')
 
-	if ! test -f $AMPATH/modules/remove.am; then
-		wget -q $AMREPO/modules/remove.am -O $AMPATH/modules/remove.am
-		chmod a+x $AMPATH/modules/remove.am
+	if ! test -f "$AMPATH"/modules/remove.am; then
+		wget -q "$AMREPO"/modules/remove.am -O "$AMPATH"/modules/remove.am
+		chmod a+x "$AMPATH"/modules/remove.am
 	fi
 
-	source $AMPATH/modules/remove.am "$@"
+	source "$AMPATH"/modules/remove.am "$@"
 	;;
 
   '-s'|'sync')
@@ -322,12 +324,12 @@ case "$1" in
 	_no_sudo
 	_online_check
 
-	if ! test -f $AMPATH/modules/sync.am; then
-		wget -q $AMREPO/modules/sync.am -O $AMPATH/modules/sync.am
-		chmod a+x $AMPATH/modules/sync.am
+	if ! test -f "$AMPATH"/modules/sync.am; then
+		wget -q "$AMREPO"/modules/sync.am -O "$AMPATH"/modules/sync.am
+		chmod a+x "$AMPATH"/modules/sync.am
 	fi
 
-	source $AMPATH/modules/sync.am "$@"
+	source "$AMPATH"/modules/sync.am "$@"
 	;;
 
   '-t'|'template')
@@ -335,12 +337,12 @@ case "$1" in
 	_no_sudo
 	_online_check
 
-	if ! test -f $AMPATH/modules/template.am; then
-		wget -q $AMREPO/modules/template.am -O $AMPATH/modules/template.am
-		chmod a+x $AMPATH/modules/template.am
+	if ! test -f "$AMPATH"/modules/template.am; then
+		wget -q "$AMREPO"/modules/template.am -O "$AMPATH"/modules/template.am
+		chmod a+x "$AMPATH"/modules/template.am
 	fi
 
-	source $AMPATH/modules/template.am "$@"
+	source "$AMPATH"/modules/template.am "$@"
 	;;
 
   '-u'|'-U'|'update'|'--force-latest') 
@@ -348,19 +350,20 @@ case "$1" in
 	_no_sudo
 	_online_check
 
-	if ! test -f $AMPATH/modules/update.am; then
-		wget -q $AMREPO/modules/update.am -O $AMPATH/modules/update.am
-		chmod a+x $AMPATH/modules/update.am
+	if ! test -f "$AMPATH"/modules/update.am; then
+		wget -q "$AMREPO"/modules/update.am -O "$AMPATH"/modules/update.am
+		chmod a+x "$AMPATH"/modules/update.am
 	fi
 
-	source $AMPATH/modules/update.am "$@"
+	source "$AMPATH"/modules/update.am "$@"
 	;;
 
   '--disable-completion')
 
-  	if [ $(grep -o $AMCLI 0<$COMPLETIONPATH/$COMPLETIONFILE | head -1) == $AMCLI 2>/dev/null ]; then
-  		grep -v 'complete -W "$(cat '$AMPATH'/list 2>/dev/null)" '$AMCLI'' $COMPLETIONPATH/$COMPLETIONFILE > $AMPATH/$COMPLETIONFILE.backup &&
-		$SUDOCOMMAND mv $AMPATH/$COMPLETIONFILE.backup $COMPLETIONPATH/$COMPLETIONFILE
+  	
+  	if [ "$(grep -o "$AMCLI" 0<"$COMPLETIONPATH/$COMPLETIONFILE" | head -1)" == "$AMCLI" ]; then
+  		grep -v 'complete -W "$(cat '"$AMPATH"'/list 2>/dev/null)" '"$AMCLI"'' "$COMPLETIONPATH/$COMPLETIONFILE" > "$AMPATH"/$COMPLETIONFILE.backup &&
+		$SUDOCOMMAND mv "$AMPATH"/$COMPLETIONFILE.backup "$COMPLETIONPATH/$COMPLETIONFILE"
 		echo " Completion disabled! "
 	else
 		echo " Completion script is NOT enabled! "
@@ -369,20 +372,20 @@ case "$1" in
 
   '--enable-completion')
 
-	if [ $(grep -o $AMCLI 0<$COMPLETIONPATH/$COMPLETIONFILE | head -1) == $AMCLI 2>/dev/null ]; then
+	if [ "$(grep -o "$AMCLI" 0<"$COMPLETIONPATH/$COMPLETIONFILE" | head -1)" == "$AMCLI" ]; then
 		echo " Completion script is already enabled!"
 	else
-		$SUDOCOMMAND mkdir -p $COMPLETIONPATH
-		if [ $AMCLI == appman ]; then
-			if ! test -f $COMPLETIONPATH/$COMPLETIONFILE; then
-				echo '#!/usr/bin/env bash' >> $COMPLETIONFILE
+		$SUDOCOMMAND mkdir -p "$COMPLETIONPATH"
+		if [ "$AMCLI" == appman ]; then
+			if ! test -f "$COMPLETIONPATH/$COMPLETIONFILE"; then
+				echo '#!/usr/bin/env bash' >> "$COMPLETIONFILE"
 			fi
 		else
-			echo '#!/usr/bin/env bash' >> $COMPLETIONFILE
+			echo '#!/usr/bin/env bash' >> "$COMPLETIONFILE"
 		fi
-		echo 'complete -W "$(cat '$AMPATH'/list 2>/dev/null)" '$AMCLI'' >> $COMPLETIONFILE
-		chmod a+x $COMPLETIONFILE
-		$SUDOCOMMAND mv $COMPLETIONFILE $COMPLETIONPATH/ 2> /dev/null
+		echo 'complete -W "$(cat '"$AMPATH"'/list 2>/dev/null)" '"$AMCLI"'' >> "$COMPLETIONFILE"
+		chmod a+x "$COMPLETIONFILE"
+		$SUDOCOMMAND mv "$COMPLETIONFILE" "$COMPLETIONPATH/" 2> /dev/null
 		echo " Completion has been enabled!"
 	fi
 	;;
@@ -391,12 +394,12 @@ case "$1" in
 
 	_no_sudo
 
-	if ! test -f $AMPATH/modules/launcher.am; then
-		wget -q $AMREPO/modules/launcher.am -O $AMPATH/modules/launcher.am
-		chmod a+x $AMPATH/modules/launcher.am
+	if ! test -f "$AMPATH"/modules/launcher.am; then
+		wget -q "$AMREPO"/modules/launcher.am -O "$AMPATH"/modules/launcher.am
+		chmod a+x "$AMPATH"/modules/launcher.am
 	fi
 
-	source $AMPATH/modules/launcher.am "$@"
+	source "$AMPATH"/modules/launcher.am "$@"
 	;;
 
   '--rollback')
@@ -404,12 +407,12 @@ case "$1" in
 	_no_sudo
 	_online_check
 
-	if ! test -f $AMPATH/modules/rollback.am; then
-		wget -q $AMREPO/modules/rollback.am -O $AMPATH/modules/rollback.am
-		chmod a+x $AMPATH/modules/rollback.am
+	if ! test -f "$AMPATH"/modules/rollback.am; then
+		wget -q "$AMREPO"/modules/rollback.am -O "$AMPATH"/modules/rollback.am
+		chmod a+x "$AMPATH"/modules/rollback.am
 	fi
 
-	source $AMPATH/modules/rollback.am "$@"
+	source "$AMPATH"/modules/rollback.am "$@"
 	;;
 
   '--user'|'appman')
@@ -417,7 +420,7 @@ case "$1" in
   	_no_sudo
   	_online_check
 
-	if [ $AMCLI == appman ] 2>/dev/null; then
+	if [ "$AMCLI" == appman ] 2>/dev/null; then
 		echo " This function only works for AM"
 		exit
 	fi
@@ -428,7 +431,7 @@ case "$1" in
 		echo -e "Please run '${RED}alias am=/opt/am/appman\033[0m' to made 'AM' act exactly like 'AppMan' for\nthe current session or save this command to your '"'~/.bashrc'"' file to make the\nchanges permanent. Visit ${LightBlue}https://github.com/ivan-hc/appman\033[0m for more!"
 	else
 		_appman
-		wget -q $AMREPO/APP-MANAGER -O /opt/am/appman && chmod a+x /opt/am/appman
+		wget -q "$AMREPO"/APP-MANAGER -O /opt/am/appman && chmod a+x /opt/am/appman
 		echo -e "Please run '${RED}alias am=/opt/am/appman\033[0m' to made 'AM' act exactly like 'AppMan' for\nthe current session or save this command to your '"'~/.bashrc'"' file to make the\nchanges permanent."
   	fi
   	;;
@@ -438,12 +441,12 @@ case "$1" in
 	_no_sudo
 	_online_check
 
-	if ! test -f $AMPATH/modules/devtools.am; then
-		wget -q $AMREPO/modules/devtools.am -O $AMPATH/modules/devtools.am
-		chmod a+x $AMPATH/modules/devtools.am
+	if ! test -f "$AMPATH"/modules/devtools.am; then
+		wget -q "$AMREPO"/modules/devtools.am -O "$AMPATH"/modules/devtools.am
+		chmod a+x "$AMPATH"/modules/devtools.am
 	fi
 
-	source $AMPATH/modules/devtools.am "$@"
+	source "$AMPATH"/modules/devtools.am "$@"
 	;;
 
   'nolibfuse')
@@ -451,18 +454,18 @@ case "$1" in
 	_no_sudo
 	_online_check
 
-	if ! test -f $AMPATH/modules/nolibfuse.am; then
-		wget -q $AMREPO/modules/nolibfuse.am -O $AMPATH/modules/nolibfuse.am
-		chmod a+x $AMPATH/modules/nolibfuse.am
+	if ! test -f "$AMPATH"/modules/nolibfuse.am; then
+		wget -q "$AMREPO"/modules/nolibfuse.am -O "$AMPATH"/modules/nolibfuse.am
+		chmod a+x "$AMPATH"/modules/nolibfuse.am
 	fi
 
-	source $AMPATH/modules/nolibfuse.am "$@"
+	source "$AMPATH"/modules/nolibfuse.am "$@"
 	;;
 
   'version'|'-v'|'--version')
 
-  	echo "6.2.1";;
+  	echo "6.2.1-1";;
 
-  *) exec $AMCLIPATH ;;
+  *) exec "$AMCLIPATH" ;;
 
 esac
