don't allow `-ias` without aisap

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -1072,6 +1072,10 @@ case "$1" in
 		;;
 	'-ias')
 		shift
+		if ! command -v aisap >/dev/null 2>&1; then
+			echo "ERROR: You need to install aisap to use this option"
+			exit 1
+		fi
 		if echo "${@}" | grep -q -- '--user'; then
 			user_true=1
 		fi
