Fix MODULES_PATH detection for AM in AppMan mode (#2158)
fix https://github.com/ivan-hc/AM/issues/2157

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-AMVERSION="9.9.5-4"
+AMVERSION="9.9.5-5"
 
 # Determine main repository and branch
 AMREPO="https://raw.githubusercontent.com/ivan-hc/AM/main"
@@ -1704,17 +1704,15 @@ _use_force_latest() {
 # HANDLE ALL THE EXTERNAL MODULES
 _use_module() {
 	# Test if module exists
+	if [ ! -f "$MODULES_PATH/$MODULE" ] && [ -f "$APPMANCONFIG/appman-mode" ] && { [ "$CLI" = am ] || [ "$CLI" = APP-MANAGER ]; }; then
+		[ -f "/usr/lib/am/modules/$MODULE" ] && MODULES_PATH="/usr/lib/am/modules"
+		[ -f "$(readlink -f /opt)/am/modules/$MODULE" ] && MODULES_PATH="$(readlink -f /opt)/am/modules"
+	fi
 	if [ ! -f "$MODULES_PATH/$MODULE" ]; then
-		if [ "$CLI" = am ] && [ -f "$APPMANCONFIG"/appman-mode ] && [ -f "/usr/lib/am/modules/$MODULE" ]; then
-			MODULES_PATH="/usr/lib/am/modules"
-		elif [ "$CLI" = am ] && [ -f "$APPMANCONFIG"/appman-mode ] && [ -f "$(readlink -f /opt)/am/modules/$MODULE" ]; then
-			MODULES_PATH="$(readlink -f /opt)/am/modules"
-		else
-			_online_check
-			if ! wget -q "$MODULES_SOURCE/$MODULE" -O "$MODULES_PATH/$MODULE"; then
-				echo $" Module not found, run \"$AMCLI -s\" to update \"$AMCLIUPPER\""
-				exit 1
-			fi
+		_online_check
+		if ! wget -q "$MODULES_SOURCE/$MODULE" -O "$MODULES_PATH/$MODULE"; then
+			echo $" Module not found, run \"$AMCLI -s\" to update \"$AMCLIUPPER\""
+			exit 1
 		fi
 	fi
 	# Source module
