Replace Spaces from previous PR with Tabs

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -14,74 +14,74 @@ function _am(){
 }
 
 function _appman() {
-    # Helper functions defined inside the parent function
-    function prompt_for_directory() {
-        local location
-        read -r -ep "Please, write the name or the path of your custom application's folder: $(echo -e '\n\n '$HOME'/')" location
-        echo "$location"
-    }
+	# Helper functions defined inside the parent function
+	function prompt_for_directory() {
+		local location
+		read -r -ep "Please, write the name or the path of your custom application's folder: $(echo -e '\n\n '$HOME'/')" location
+		echo "$location"
+	}
 
-    function validate_directory() {
-        local location=$1
-        if [[ "$location" == "" ]]; then
-            echo -e "--------------------------------------------------------------------------"
-            echo "OPERATION ABORTED!"
-            exit  1
-        elif [[ "$location" == ".local/bin" ]]; then
-            echo -e "--------------------------------------------------------------------------\n"
-            echo -e " 💀 ERROR, you can't install applications into a '$PATH'\n\n The directory ~/.local/bin and 'bin' folders are used for executables.\n\n Please, choose a different path and retry! \n"
-            echo -e "--------------------------------------------------------------------------\n"
-            exit  1
-        else
-            local location_appman="${location/#$HOME}"
-            location_appman="${location_appman// /-}"
-            location_appman="${location_appman#/}"
-            location_appman="${location_appman%/}"
-            echo "$location_appman"
-        fi
-    }
+	function validate_directory() {
+		local location=$1
+		if [[ "$location" == "" ]]; then
+			echo -e "--------------------------------------------------------------------------"
+			echo "OPERATION ABORTED!"
+			exit  1
+		elif [[ "$location" == ".local/bin" ]]; then
+			echo -e "--------------------------------------------------------------------------\n"
+			echo -e " 💀 ERROR, you can't install applications into a '$PATH'\n\n The directory ~/.local/bin and 'bin' folders are used for executables.\n\n Please, choose a different path and retry! \n"
+			echo -e "--------------------------------------------------------------------------\n"
+			exit  1
+			else
+			local location_appman="${location/#$HOME}"
+			location_appman="${location_appman// /-}"
+			location_appman="${location_appman#/}"
+			location_appman="${location_appman%/}"
+			echo "$location_appman"
+		fi
+	}
 
-    function initialize_appman() {
-        APPSDIR=$1
-        mkdir -p ~/$APPSDIR/appman/.cache
-        mkdir -p ~/.local/bin ~/.local/share/applications ~/.local/share/icons
-        AMCLI="appman"
-        AMCLIPATH="$DIR/$AMCLI"
-        SUDOCOMMAND=""
-        COMPLETIONPATH="$HOME"
-        COMPLETIONFILE=".bash_completion"
-        APPSPATH="$HOME/$APPSDIR"
-        AMPATH="$HOME/$APPSDIR/$AMCLI"
-    }
+	function initialize_appman() {
+		APPSDIR=$1
+		mkdir -p ~/$APPSDIR/appman/.cache
+		mkdir -p ~/.local/bin ~/.local/share/applications ~/.local/share/icons
+		AMCLI="appman"
+		AMCLIPATH="$DIR/$AMCLI"
+		SUDOCOMMAND=""
+		COMPLETIONPATH="$HOME"
+		COMPLETIONFILE=".bash_completion"
+		APPSPATH="$HOME/$APPSDIR"
+		AMPATH="$HOME/$APPSDIR/$AMCLI"
+	}
 
-    # Main execution
-    if [[ ! -f ~/.config/appman/appman-config ]]; then
-        echo "--------------------------------------------------------------------------"
-        echo " >>> Thank you for choosing AppMan!"
-        echo "--------------------------------------------------------------------------"
-        echo "Before proceeding with any task, write the name of the directory in which"
-        echo 'you will install the apps, for example "Programs" or "My-apps", you can '
-        echo 'also choose a subfolder, for example ".local/My-apps" or a deeper path.'
-        echo -e "\nThe destination folder will be created in $HOME"
-        echo -e "\nSYNTAX: PATH/TO/DIRNAME\n"
-        echo 'NOTE, any spaces or "/" at the beginning and end will be removed. If you '
-        echo 'decide to change your choice in the future, first remove all the programs'
-        echo 'and then edit the ~/.config/appman/appman-config text file.'
-        echo -e "--------------------------------------------------------------------------\n"
+	# Main execution
+	if [[ ! -f ~/.config/appman/appman-config ]]; then
+		echo "--------------------------------------------------------------------------"
+		echo " >>> Thank you for choosing AppMan!"
+		echo "--------------------------------------------------------------------------"
+		echo "Before proceeding with any task, write the name of the directory in which"
+		echo 'you will install the apps, for example "Programs" or "My-apps", you can '
+		echo 'also choose a subfolder, for example ".local/My-apps" or a deeper path.'
+		echo -e "\nThe destination folder will be created in $HOME"
+		echo -e "\nSYNTAX: PATH/TO/DIRNAME\n"
+		echo 'NOTE, any spaces or "/" at the beginning and end will be removed. If you '
+		echo 'decide to change your choice in the future, first remove all the programs'
+		echo 'and then edit the ~/.config/appman/appman-config text file.'
+		echo -e "--------------------------------------------------------------------------\n"
 
-        local location=$(prompt_for_directory)
-        local validated_location=$(validate_directory "$location")
-        mkdir -p ~/.config/appman
-        echo "$validated_location" >> ~/.config/appman/appman-config
-        echo '--------------------------------------------------------------------------'
-        echo 'You are ready! Start installing your favorite apps locally!!'
-        echo "All apps will be installed in $HOME/$validated_location"
-        echo -e '\nIn case of problems, use the option "-h".'
-        echo '--------------------------------------------------------------------------'
-    else
-        break  2> /dev/null
-    fi
-    initialize_appman $(<~/.config/appman/appman-config)
+		local location=$(prompt_for_directory)
+		local validated_location=$(validate_directory "$location")
+		mkdir -p ~/.config/appman
+		echo "$validated_location" >> ~/.config/appman/appman-config
+		echo '--------------------------------------------------------------------------'
+		echo 'You are ready! Start installing your favorite apps locally!!'
+		echo "All apps will be installed in $HOME/$validated_location"
+		echo -e '\nIn case of problems, use the option "-h".'
+		echo '--------------------------------------------------------------------------'
+	else
+		break  2> /dev/null
+	fi
+	initialize_appman $(<~/.config/appman/appman-config)
 }
 
 if [[ "$DIR/$CLI" == "/usr/local/bin/am" ]] 2>/dev/null; then
@@ -98,12 +98,12 @@ function _online_check(){
 }
 
 if [[ -f $AMPATH/new-repo.txt ]]; then
-    AMREPO=$(<"$AMPATH/new-repo.txt") # Utilizing command substitution with < for more efficient file reading
-    if [[ "$@" != "newrepo off" ]]; then
-        echo -e "\n WARNING, custom repository ENABLED!\n Use the command '$AMCLI newrepo off' to restore the default repo!\n"
-    fi
+	AMREPO=$(<"$AMPATH/new-repo.txt") # Utilizing command substitution with < for more efficient file reading
+	if [[ "$@" != "newrepo off" ]]; then
+		echo -e "\n WARNING, custom repository ENABLED!\n Use the command '$AMCLI newrepo off' to restore the default repo!\n"
+	fi
 else
-    AMREPO="https://raw.githubusercontent.com/IVAN-HC/AM/main" # Consolidating variable assignments for clarity and brevity
+	AMREPO="https://raw.githubusercontent.com/IVAN-HC/AM/main" # Consolidating variable assignments for clarity and brevity
 fi
 
 # Determine system architecture and current user
@@ -114,8 +114,8 @@ currentuser="$USER"
 missing_deps=()
 for name in cat chmod chown curl grep sed wget; do
   if ! command -v "$name" &>/dev/null; then
-    printf "\nERROR: command \"%s\" not found, strongly needed by \"%s\"!\n" "$name" "$AMCLI"
-    missing_deps+=("$name")
+	printf "\nERROR: command \"%s\" not found, strongly needed by \"%s\"!\n" "$name" "$AMCLI"
+	missing_deps+=("$name")
   fi
 done
 
@@ -169,15 +169,15 @@ function _no_sudo(){
 }
 
 function _patch_bashrc_and_profile(){
-    # Check if the custom PATH is not already in .bashrc, then append it (fix - exclamation mark negates the entire command substitution)
-    if ! grep -q 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' "$HOME/.bashrc"; then
-        echo 'export PATH=$(echo $PATH | tr ":" "\n" | grep -v "/.local/bin" | tr "\n" ":" | sed ''s/.$//'')' >> "$HOME/.bashrc"
-        echo -e 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin\n' >> "$HOME/.bashrc"
-    fi
-    # Correct the order of .local/bin in .profile if necessary
-    if grep -q 'PATH="$HOME/.local/bin:$PATH"' "$HOME/.profile"; then
-        sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' "$HOME/.profile"
-    fi
+	# Check if the custom PATH is not already in .bashrc, then append it (fix - exclamation mark negates the entire command substitution)
+	if ! grep -q 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' "$HOME/.bashrc"; then
+		echo 'export PATH=$(echo $PATH | tr ":" "\n" | grep -v "/.local/bin" | tr "\n" ":" | sed ''s/.$//'')' >> "$HOME/.bashrc"
+		echo -e 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin\n' >> "$HOME/.bashrc"
+	fi
+	# Correct the order of .local/bin in .profile if necessary
+	if grep -q 'PATH="$HOME/.local/bin:$PATH"' "$HOME/.profile"; then
+		sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' "$HOME/.profile"
+	fi
 }
 
 # Check if the script is called with 'appman' and if so, perform initial setup
