If module not online, then update "AM" and retry

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-AMVERSION="7.8.1"
+AMVERSION="7.8.1-1"
 
 # Determine main repository and branch
 AMREPO="https://raw.githubusercontent.com/ivan-hc/AM/main"
@@ -967,8 +967,13 @@ function _use_force_latest() {
 function _use_module() {
 	# Test if module exists
 	if ! test -f "$AMPATH/modules/$MODULE"; then
-		wget -q "$AMREPO/modules/$MODULE" -O "$AMPATH/modules/$MODULE"
-		chmod a+x "$AMPATH/modules/$MODULE"
+		_online_check
+		if curl --output /dev/null --silent --head --fail "$AMREPO/modules/$MODULE"; then
+			wget -q "$AMREPO/modules/$MODULE" -O "$AMPATH/modules/$MODULE"
+			chmod a+x "$AMPATH/modules/$MODULE"
+		else
+			echo " Module not found, run \"$AMCLI -s\" to update \"$AMCLIUPPER\"" && exit 1
+		fi
 	fi
 	# Source module
 	source "$AMPATH/modules/$MODULE" "$@"
