Update APP-MANAGER

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -1,8 +1,5 @@
 #!/usr/bin/env bash
 
-AMVERSION="6.6.2-2"
-
-# Determine the name of this script and its working directory
 DIR="$( cd "$( dirname "$0" )" && pwd )"
 CLI=$(basename "$0")
 AMVERSION="6.6.2-1"
@@ -39,50 +36,48 @@ function _am(){
 	mkdir -p "$AMPATH"/modules
 }
 
-# "APPMAN" CORE VARIABLES AND FUNCTIONS
-function _appman() {
+# Helper functions don't need to be defined inside the parent function
+function prompt_for_directory() {
+	local location
+	read -r -ep "Please, write the name or the path of your custom application's folder: $(echo -e '\n\n '$HOME'/')" location
+	echo "$location"
+}
 
-	function _appman_initialize() {
-		APPSDIR=$1
-		mkdir -p ~/"$APPSDIR"/appman/.cache
-		mkdir -p ~/"$APPSDIR"/appman/modules
-		mkdir -p ~/.local/bin "$DATADIR"/applications "$DATADIR"/icons
-		AMCLI="appman"
-		AMCLIPATH="$DIR/$AMCLI"
-		SUDOCOMMAND=""
-		COMPLETIONPATH="$HOME"
-		COMPLETIONFILE=".bash_completion"
-		APPSPATH="$HOME/$APPSDIR"
-		AMPATH="$HOME/$APPSDIR/$AMCLI"
-	}
-
-	# Helper functions don't need to be defined inside the parent function
-	function _appman_prompt_for_directory() {
-		local location
-		read -r -ep "Please, write the name or the path of your custom application's folder: $(echo -e '\n\n '$HOME'/')" location
-		echo "$location"
-	}
-
-	function _appman_validate_directory() {
-		local location=$1
-		if [[ "$location" == "" ]]; then
-			echo -e "--------------------------------------------------------------------------"
-			echo "OPERATION ABORTED!"
-			exit  1
-		elif [[ "$location" == ".local/bin" ]]; then
-			echo -e "--------------------------------------------------------------------------\n"
-			echo -e " 💀 ERROR, you can't install applications into a '$PATH'\n\n The directory ~/.local/bin and 'bin' folders are used for executables.\n\n Please, choose a different path and retry! \n"
-			echo -e "--------------------------------------------------------------------------\n"
-			exit  1
+function validate_directory() {
+	local location=$1
+	if [[ "$location" == "" ]]; then
+		echo -e "--------------------------------------------------------------------------"
+		echo "OPERATION ABORTED!"
+		exit  1
+	elif [[ "$location" == ".local/bin" ]]; then
+		echo -e "--------------------------------------------------------------------------\n"
+		echo -e " 💀 ERROR, you can't install applications into a '$PATH'\n\n The directory ~/.local/bin and 'bin' folders are used for executables.\n\n Please, choose a different path and retry! \n"
+		echo -e "--------------------------------------------------------------------------\n"
+		exit  1
 		else
-			local location_appman="${location/#$HOME}"
-			location_appman="${location_appman// /-}"
-			location_appman="${location_appman#/}"
-			location_appman="${location_appman%/}"
-			echo "$location_appman"
-		fi
-	}
+		local location_appman="${location/#$HOME}"
+		location_appman="${location_appman// /-}"
+		location_appman="${location_appman#/}"
+		location_appman="${location_appman%/}"
+		echo "$location_appman"
+	fi
+}
 
+function initialize_appman() {
+	APPSDIR=$1
+	mkdir -p ~/"$APPSDIR"/appman/.cache
+	mkdir -p ~/"$APPSDIR"/appman/modules
+	mkdir -p ~/.local/bin "$DATADIR"/applications "$DATADIR"/icons
+	AMCLI="appman"
+	AMCLIPATH="$DIR/$AMCLI"
+	SUDOCOMMAND=""
+	COMPLETIONPATH="$HOME"
+	COMPLETIONFILE=".bash_completion"
+	APPSPATH="$HOME/$APPSDIR"
+	AMPATH="$HOME/$APPSDIR/$AMCLI"
+}
+
+function _appman() {
 	if [[ ! -f "$APPMANCONFIG"/appman-config ]]; then
 		echo "--------------------------------------------------------------------------"
 		echo " >>> Thank you for choosing AppMan!"
@@ -96,8 +91,8 @@ function _appman() {
 		echo 'decide to change your choice in the future, first remove all the programs'
 		echo 'and then edit the ~/.config/appman/appman-config text file.'
 		echo -e "--------------------------------------------------------------------------\n"
-		local location=$(_appman_prompt_for_directory)
-		local validated_location=$(_appman_validate_directory "$location")
+		local location=$(prompt_for_directory)
+		local validated_location=$(validate_directory "$location")
 		mkdir -p "$APPMANCONFIG"
 		echo "$validated_location" >> "$APPMANCONFIG"/appman-config
 		echo '--------------------------------------------------------------------------'
@@ -106,79 +101,58 @@ function _appman() {
 		echo -e '\nIn case of problems, use the option "-h".'
 		echo '--------------------------------------------------------------------------'
 	fi
-	_appman_initialize "$(<"$APPMANCONFIG"/appman-config)"
-
-	# Fix order in "echo $PATH" in case "$HOME/.local/bin" is placed at the beginning instead of the end
-	function _patch_bashrc_and_profile() {
-		# Check if the custom PATH is not already in .bashrc, then append it (fix - exclamation mark negates the entire command substitution)
-		if test -f "$HOME/.bashrc"; then
-			if ! grep -q 'export PATH=$PATH:$HOME/.local/bin' "$HOME/.bashrc"; then
-				echo 'export PATH=$(echo $PATH | tr ":" "\n" | grep -v "/.local/bin" | tr "\n" ":" | sed ''s/.$//'')' >> "$HOME/.bashrc"
-				echo -e 'export PATH=$PATH:$HOME/.local/bin\n' >> "$HOME/.bashrc"
-			fi
-		fi
-		# Correct the order of .local/bin in .profile if necessary
-		if test -f "$HOME/.profile"; then
-			if grep -q 'PATH="$HOME/.local/bin:$PATH"' "$HOME/.profile"; then
-				sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' "$HOME/.profile"
-			fi
-		elif test -f "$HOME/.bash_profile"; then
-			if grep -q 'PATH="$HOME/.local/bin:$PATH"' "$HOME/.bash_profile"; then
-				sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' "$HOME/.bash_profile"
-			fi
-		fi
-	}
-	_patch_bashrc_and_profile
+	initialize_appman "$(<"$APPMANCONFIG"/appman-config)"
 }
 
-# DETERMINE WHEN TO USE "AM" OR "APPMAN"
 if [[ "$DIR/$CLI" == "/usr/local/bin/am" ]] 2>/dev/null; then
 	_am
 else
 	_appman
 fi
 
-# FUNCTIONS RELATED TO THE SAFE USE OF "AM"
-function _am_security_check() {
-	function _am_dependences_check() {
-		# Check for essential commands required by the application
-		missing_deps=()
-		for name in cat chmod chown curl grep sed wget; do
-			if ! command -v "$name" &>/dev/null; then
-				printf "\nERROR: command \"%s\" not found, strongly needed by \"%s\"!\n" "$name" "$AMCLI"
-			missing_deps+=("$name")
-			fi
-		done
+function _online_check(){
+	if ! wget -q --tries=10 --timeout=20 --spider https://github.com; then
+		echo -e "\n $AMCLI is offline, please check your internet connection and try again\n"
+		exit
+	fi
+}
 
-		# Exit if any essential command is missing
-		if [ -n "$missing_deps" ]; then
-			printf "\nMissing essential commands: %s\nInstall the above and try again\n\n" "${missing_deps[*]}"
-			exit 1
-		fi
-	}
+# Determine catalogue in use
+export AMCATALOGUEMARKDOWNS="https://raw.githubusercontent.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/main/apps"
+export AMCATALOGUEICONS="https://raw.githubusercontent.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/main/icons"
 
 # Determine system architecture and current user
 export arch="$HOSTTYPE"
 export currentuser="$USER"
 
-	# Check and create the $AMPATH directory if it does not exist
-	if [ ! -d "$AMPATH" ]; then
-		$SUDOCOMMAND mkdir -p "$AMPATH"
+if [[ -f "$AMPATH"/new-repo.txt ]]; then
+	AMREPO=$(<"$AMPATH/new-repo.txt") # Utilizing command substitution with < for more efficient file reading
+	APPSDB="$AMREPO/programs/$arch"
+	APPSLISTDB="$AMREPO/programs/$arch-apps"
+	LIBSLISTDB="$AMREPO/programs/libs-list"
+	if [[ "$@" != "newrepo off" ]]; then
+		echo '--------------------------------------------------------------------------'
+		echo " Source: $AMREPO"
+		echo '--------------------------------------------------------------------------'
 	fi
+else
+	AMREPO="https://raw.githubusercontent.com/IVAN-HC/AM/main" # Consolidating variable assignments for clarity and brevity
+	APPSDB="$AMREPO/programs/$arch"
+	APPSLISTDB="$AMREPO/programs/$arch-apps"
+	LIBSLISTDB="$AMREPO/programs/libs-list"
+fi
 
-	# Prevent other system users from using "AM"
-	if [ "$AMCLI" == am ]; then
-		ampathowner=$(ls -ld /opt/am | awk 'NR==1 {print $3}')
-		if [ "$ampathowner" != "$currentuser" ]; then
-			echo ' 💀 ERROR: you are not the owner of /opt/am, so you cannot use "AM"'
-			echo '--------------------------------------------------------------------------'
-			echo ' The user that have installed "AM" on this system is "'"$ampathowner"'"'
-			echo ' you are only allowed to use the installed apps, not to manage them.'
-			echo '--------------------------------------------------------------------------'
-			echo ' Please, contact "'"$ampathowner"'" to change the ownership of /opt/am or'
-			echo ' consider using "AppMan" instead, see https://github.com/ivan-hc/AppMan'
-			echo '--------------------------------------------------------------------------'
-			exit
+# To implement future application database changes
+if [ -f "$AMPATH/neodb" ]; then
+	if grep -q "://" "$AMPATH/neodb"; then
+		if grep -q "#STATUS=quiet" "$AMPATH/neodb"; then
+			case "$1" in
+			'-a'|'about'|'-d'|'download'|'-i'|'install'|'-l'|'list'|'-q'|'query')
+				echo '--------------------------------------------------------------------------'
+				echo " Source: Third party repositories are enabled"
+				echo '--------------------------------------------------------------------------'
+				;;
+			esac
 		fi
 	fi
 fi
@@ -238,62 +212,38 @@ cat <<-HEREDOC >> "$CACHEDIR/options"
 	--user
 HEREDOC
 
-	# Function to check online connections (uses github.com by default, as the database and CLI itself are stored/hosted there)
-	function _online_check() {
-		if ! wget -q --tries=10 --timeout=20 --spider https://github.com; then
-			echo -e "\n $AMCLI is offline, please check your internet connection and try again\n"
-			exit
-		fi
-	}
+function _no_sudo(){
+	if [ -n "$SUDO_COMMAND" ]; then
+		printf "\n WARNING: You don't need to use SUDO for this.\n\n";
+		exit 1;
+	fi
 }
 
-_am_security_check
-
-# FUNCTIONS RELATED TO THE DATABASE OF APPS
-function _am_databases_check() {
-	# Determine catalogue in use
-	export AMCATALOGUEMARKDOWNS="https://raw.githubusercontent.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/main/apps"
-	export AMCATALOGUEICONS="https://raw.githubusercontent.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/main/icons"
-
-	function _am_newrepo_check() {
-		# Determine if the CLI uses the "main" branch of https://github.com/ivan-hc/AM or an alternative one
-		if [[ -f "$AMPATH"/new-repo.txt ]]; then
-			AMREPO=$(<"$AMPATH/new-repo.txt") # Utilizing command substitution with < for more efficient file reading
-			APPSDB="$AMREPO/programs/$arch"
-			APPSLISTDB="$AMREPO/programs/$arch-apps"
-			LIBSLISTDB="$AMREPO/programs/libs-list"
-			if [[ "$@" != "newrepo off" ]]; then
-				echo '--------------------------------------------------------------------------'
-				echo " Source: $AMREPO"
-				echo '--------------------------------------------------------------------------'
-			fi
-		else
-			AMREPO="https://raw.githubusercontent.com/IVAN-HC/AM/main" # Consolidating variable assignments for clarity and brevity
-			APPSDB="$AMREPO/programs/$arch"
-			APPSLISTDB="$AMREPO/programs/$arch-apps"
-			LIBSLISTDB="$AMREPO/programs/libs-list"
+function _patch_bashrc_and_profile(){
+	# Check if the custom PATH is not already in .bashrc, then append it (fix - exclamation mark negates the entire command substitution)
+	if test -f "$HOME/.bashrc"; then
+		if ! grep -q 'export PATH=$PATH:$HOME/.local/bin' "$HOME/.bashrc"; then
+			echo 'export PATH=$(echo $PATH | tr ":" "\n" | grep -v "/.local/bin" | tr "\n" ":" | sed ''s/.$//'')' >> "$HOME/.bashrc"
+			echo -e 'export PATH=$PATH:$HOME/.local/bin\n' >> "$HOME/.bashrc"
 		fi
-	}
-
-	_am_newrepo_check
-
-	# To implement future application database changes
-	if [ -f "$AMPATH/neodb" ]; then
-		if grep -q "://" "$AMPATH/neodb"; then
-			if grep -q "#STATUS=quiet" "$AMPATH/neodb"; then
-				case "$1" in
-				'-a'|'about'|'-d'|'download'|'-i'|'install'|'-l'|'list'|'-q'|'query')
-					echo '--------------------------------------------------------------------------'
-					echo " Source: Third party repositories are enabled"
-					echo '--------------------------------------------------------------------------'
-					;;
-				esac
-			fi
+	fi
+	# Correct the order of .local/bin in .profile if necessary
+	if test -f "$HOME/.profile"; then
+		if grep -q 'PATH="$HOME/.local/bin:$PATH"' "$HOME/.profile"; then
+			sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' "$HOME/.profile"
+		fi
+	elif test -f "$HOME/.bash_profile"; then
+		if grep -q 'PATH="$HOME/.local/bin:$PATH"' "$HOME/.bash_profile"; then
+			sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' "$HOME/.bash_profile"
 		fi
 	fi
 }
 
-_am_databases_check
+# Check if the script is called with 'appman' and if so, perform initial setup
+[ "$AMCLI" = "appman" ] && {
+	_no_sudo
+	_patch_bashrc_and_profile
+}
 
 # Set header authorization if GitHub API key file exists
 [ -f "$AMPATH/ghapikey.txt" ] && HeaderAuthWithGITPAT=" --header \"Authorization: token $(<"$AMPATH/ghapikey.txt")\" "
@@ -347,49 +297,43 @@ function _check_version(){
 	done
 }
 
-# Generate a list of words to use in bash completion
-rm -rf "$AMPATH/options"
-cat <<-HEREDOC >> "$AMPATH/options"
-	about
-	apikey
-	backup
-	clean
-	download
-	files
-	install
-	list
-	lock
-	neodb
-	newrepo
-	nolibfuse
-	overwrite
-	query
-	remove
-	sync
-	template
-	test
-	unlock
-	update
-	web
-	--apps
-	--byname
-	--convert
-	--debug
-	--disable-completion
-	--enable-completion
-	--firejail
-	--force-latest
-	--home
-	--launcher
-	--less
-	--rollback
-	--sandbox
-	--silent
-	--user
-HEREDOC
+# All the options
+function source_module() {
+	source "$AMPATH/modules/$MODULE" "$@"
+}
 
-# Functions related to internal options to enable/disable bash (and zsh) completion.
-function _use_disable-completion() {
+function get_module() {
+	wget -q "$AMREPO/modules/$MODULE" -O "$AMPATH/modules/$MODULE"
+	chmod a+x "$AMPATH/modules/$MODULE"
+}
+
+function test_module() {
+	if ! test -f "$AMPATH/modules/$MODULE"; then
+		get_module
+	fi
+}
+
+function use_module_sudo() {
+	test_module
+	source_module "$@"
+}
+
+function use_module() {
+	_no_sudo
+	use_module_sudo "$@"
+}
+
+function use_module_online_sudo () {
+	_online_check
+	use_module "$@"
+}
+
+function use_module_online () {
+	_no_sudo
+	use_module_online_sudo "$@"
+}
+
+function use_disable-completion() {
 	if [ "$(grep -o "$AMCLI" 0<"$COMPLETIONPATH/$COMPLETIONFILE" | head -1)" == "$AMCLI" ]; then
 		grep -v 'complete -W "$(cat '"$AMPATH"'/list 2>/dev/null)" '"$AMCLI"'' "$COMPLETIONPATH/$COMPLETIONFILE" > "$AMPATH"/$COMPLETIONFILE.backup &&
 		$SUDOCOMMAND mv "$AMPATH"/$COMPLETIONFILE.backup "$COMPLETIONPATH/$COMPLETIONFILE"
@@ -399,7 +343,7 @@ function _use_disable-completion() {
 	fi
 }
 
-function _use_enable_completion() {
+function use_enable_completion() {
 	if [ "$(grep -o "$AMCLI" 0<"$COMPLETIONPATH/$COMPLETIONFILE" | head -1)" == "$AMCLI" ]; then
 		echo " Completion script is already enabled!"
 	else
@@ -433,8 +377,8 @@ function _use_enable_completion() {
 	fi
 }
 
-# Function for the option that helps "AM" function like "AppMan", via alias
-function _use_appman() {
+function use_appman() {
+	_no_sudo
 	_online_check
 	if [ "$AMCLI" == appman ] 2>/dev/null; then
 		echo " This function only works for AM"
@@ -451,104 +395,82 @@ function _use_appman() {
 	fi
 }
 
-# Handle external modules
-function _use_module() {
-	# Test if module exists
-	if ! test -f "$AMPATH/modules/$MODULE"; then
-		wget -q "$AMREPO/modules/$MODULE" -O "$AMPATH/modules/$MODULE"
-		chmod a+x "$AMPATH/modules/$MODULE"
-	fi
-	# Source module
-	source "$AMPATH/modules/$MODULE" "$@"
-}
-
-# ALL THE OPTIONS
 case "$1" in
 	'')
 		echo -e "\n USAGE: '$AMCLI [option]'\n        '$AMCLI [option] [argument]'\n\n Run the '$AMCLI -h' command to find out more\n"
 		;;
-	# OPTIONS BASED ON EXTERNAL MODULES
 	'-a'|'about'|'-l'|'list'|'-q'|'query')
 		MODULE="database.am"
-		_use_module "$@"
+		use_module "$@"
 		;;
 	'-b'|'backup'|'-o'|'overwrite'|'lock'|'unlock')
 		MODULE="no-updates.am"
-		_use_module "$@"
+		use_module "$@"
 		;;
 	'-c'|'clean')
 		MODULE="clean.am"
-		_use_module
+		use_module
 		;;
 	'-d'|'download')
 		MODULE="download.am"
-		_online_check
-		_use_module "$@"
+		use_module_online "$@"
 		;;
 	'-f'|'files')
 		MODULE="files.am"
-		_use_module "$@"
+		use_module "$@"
 		;;
 	'-h'|'help')
 		MODULE="help.am"
-		_use_module "$@"
+		use_module "$@"
 		;;
 	'-H'|'--home'|'--firejail'|'--sandbox')
 		MODULE="sandboxes.am"
-		_use_module "$@"
+		use_module "$@"
 		;;
 	'-i'|'install')
 		MODULE="install.am"
-		_online_check
-		_use_module "$@"
+		use_module_online_sudo "$@"
 		;;
 	'-R'|'-r'|'remove')
 		MODULE="remove.am"
-		_use_module "$@"
+		use_module_sudo "$@"
 		;;
 	'-s'|'sync')
 		MODULE="sync.am"
-		_online_check
-		_use_module "$@"
+		use_module_online "$@"
 		;;
 	'-t'|'template')
 		MODULE="template.am"
-		_online_check
-		_use_module "$@"
+		use_module_online "$@"
 		;;
 	'-u'|'-U'|'update'|'--force-latest')
 		MODULE="update.am"
-		_online_check
-		_use_module "$@"
+		use_module_online "$@"
+		;;
+	'--disable-completion')
+		use_disable-completion
+		;;
+	'--enable-completion')
+		use_enable_completion
 		;;
 	'--launcher')
 		MODULE="launcher.am"
-		_use_module "$@"
+		use_module "$@"
 		;;
 	'--rollback')
 		MODULE="rollback.am"
-		_online_check
-		_use_module "$@"
+		use_module_online "$@"
+		;;
+	'--user'|'appman')
+		use_appman
 		;;
 	'neodb'|'apikey'|'newrepo')
 		MODULE="devtools.am"
-		_online_check
-		_use_module "$@"
+		use_module_online "$@"
 		;;
 	'nolibfuse')
 		MODULE="nolibfuse.am"
-		_online_check
-		_use_module "$@"
-		;;
-	# INBUILT OPTIONS
-	'--disable-completion')
-		_use_disable-completion
-		;;
-	'--enable-completion')
-		_use_enable_completion
-		;;
-	'--user'|'appman')
-		_use_appman
+		use_module_online "$@"
 		;;
 	'version'|'-v'|'--version')
 		echo "$AMVERSION"
