small refactor to _use_apikey APP-MANAGER

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -456,14 +456,14 @@ ghapikey_file="$AMDATADIR/ghapikey.txt"
 function _use_apikey() {
 	case $2 in
 	'del'|'delete'|'remove')
-		[ -f "$ghapikey_file" ] && rm -f "$ghapikey_file" &&
-		echo " ✔ $ghapikey_file has been removed" || echo " ✖ No file named $ghapikey_file has been found"
-		exit
+		[ -f "$ghapikey_file" ] || { echo " ✖ No file named $ghapikey_file has been found"; exit 1; }
+		rm -f "$ghapikey_file" && echo " ✔ $ghapikey_file has been removed" 
+		exit 0
 	esac
 	if [[ "$2" =~ ^(gh[ps]_[a-zA-Z0-9]{36}|github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59})$ ]]; then
 		test_apikey_output_with_wget=$(curl -Ls --header "Authorization: token $2" 'https://api.github.com/repos/ivan-hc/AM/releases' | head -1)
-		[ -n "$test_apikey_output_with_wget" ] && echo "$2" > "$ghapikey_file" &&
-		echo "Validation successful!" || echo "ERROR: This is not a valid key!"
+		[ -n "$test_apikey_output_with_wget" ] && echo "$2" > "$ghapikey_file" \
+			&& echo "Validation successful!" || echo "ERROR: This is not a valid key!"
 	else
 		echo "ERROR: Wrong expression, validation failed!"
 	fi
