More flexible dependency policy
"ar" (included in "binutils"), "unzip", "tar" and "zsync" are now just optional dependencies!

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -40,10 +40,15 @@ AMREPO="https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main"
 arch=$(printf '%s\n' "$HOSTTYPE")
 currentuser=$(printf '%s\n' "$USER")
 
-for name in "ar" "cat" "chmod" "chown" "curl" "grep" "sed" "tar" "unzip" "wget" "zsync"; do
+for name in "cat" "chmod" "chown" "curl" "grep" "sed" "wget"; do
   test -x "$(command -v $name 2>/dev/null)" \
-  || { printf "\n%s\n" "ERROR: $name not found, required by some installation scripts."; deps=1; };
+  || { printf "\n%s\n" 'ERROR: command "'$name'" not found, strongly needed by "'$AMCLI'"!'; deps=1; };
 done; [ "$deps" != "1" ] || { printf "\nInstall the above and try again\n\n"; exit 1; }
+
+for name in "ar" "unzip" "tar" "zsync"; do
+  test -x "$(command -v $name 2>/dev/null)" \
+  || { printf "\n%s\n" 'NOTE: command "'$name'" not found, strongly needed by some installation scripts!'; deps=1; };
+done; [ "$deps" != "1" ] || { printf '\nThe above are optional for "'$AMCLI'" itself, but to prevent installation/update\nerrors for some kind of packages, its strongly recommended to install them!\n\n'; }
 
 rm -rf "$AMPATH/options"
 cat <<-HEREDOC >> "$AMPATH/options"
@@ -2018,7 +2023,7 @@ case "$1" in
 	;;
 
   'version'|'-v'|'--version')
-  	echo "5.1";;
+  	echo "5.2";;
 
   *) exec $AMCLIPATH ;;
 
