Update APP-MANAGER

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -114,24 +114,24 @@ MODULES_SOURCE="$AMREPO/modules"
 CURLCMD="curl"
 WGETCMD="wget"
 
+# Check for essential commands
+if ! command -v wget >/dev/null 2>&1 && ! command -v curl >/dev/null 2>&1; then
+	printf $" ${RED}💀 ERROR! MISSING ESSENTIAL COMMANDS\033[0m: %s\n\n Install the above and try again! \n" "$CURLCMD, $WGETCMD"
+	exit 0
+fi
+
 # Export variables for such commands to avoid confusion
 export CURLLS="$CURLCMD -Ls" # This will be added in variables
 export CURLPROGRES="$CURLCMD -LJO --progress-bar --write-out 'Downloaded %{size_download} bytes in %{time_total} seconds'"
 export WGETPROGRESS="$WGETCMD -q --no-verbose --show-progress --progress=bar"
 
-# Check if essential commands are available
-_check_essential_commands() {
-	if ! command -v wget >/dev/null 2>&1 && ! command -v curl >/dev/null 2>&1; then
-		printf $" ${RED}💀 ERROR! MISSING ESSENTIAL COMMANDS\033[0m: %s\n\n Install the above and try again! \n" "$CURLCMD, $WGETCMD"
-		exit 0
-	fi
+# Check wget version
+_check_wget_version() {
 	if command -v wget >/dev/null 2>&1 && wget --version 2>/dev/null | head -1 | grep -qi "$WGETCMD.* 1." ; then
 		WGETV="1"
 	fi
 }
-
-# Check for essential commands first before running anything else
-_check_essential_commands
+_check_wget_version
 
 # Identify objects online
 _use_online_check_tool() {
@@ -684,8 +684,8 @@ if [ "$ARCH" = aarch64 ] || [ "$ARCH" = x86_64 ]; then
 			done
 			wait
 			export PATH="$CACHEDIR"/AMCACHEPATH/:"${PATH}"
-			# Check for essential commands (again but with new $PATH)
-			_check_essential_commands
+			# Check wget version again but with new $PATH
+			_check_wget_version
 		fi
 	fi
 fi
