Keep .desktop file handler updated and run AM/AppMan to handle links

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-AMVERSION="10.4.1"
+AMVERSION="10.4.1-1"
 
 # Determine main repository and branch
 AMREPO="https://raw.githubusercontent.com/ivan-hc/AM/main"
@@ -1102,7 +1102,8 @@ fi
 
 # PLA-INSTALL HANDLER
 
-if [ ! -f "$DATADIR"/applications/am-install.desktop ]; then
+_create_pla_handler_desktop_file() {
+	mkdir -p "$DATADIR"/applications
 	cat <<-'HEREDOC' >> "$DATADIR"/applications/am-install.desktop
 	[Desktop Entry]
 	Version=1.1
@@ -1110,16 +1111,62 @@ if [ ! -f "$DATADIR"/applications/am-install.desktop ]; then
 	Name=AM PLA-Install Handler
 	NoDisplay=true
 	Icon=io.github.ivan-hc.AM
-	Exec=sh -c 'curl -Ls "https://raw.githubusercontent.com/ivan-hc/AM/dev/tools/pla-installer.sh" | sh -s -- "${1#pla-install://}"' sh %u
+	Exec=sh -c 'PLA_APP="${1#pla-install://}"; [ -n "$PLA_APP" ] && export PLA_APP || exit 1; command -v appman >/dev/null 2>&1 && appman pla-install-handler || command -v am >/dev/null 2>&1 && am pla-install-handler' sh %u
 	Terminal=true
 	MimeType=x-scheme-handler/pla-install;
 	Categories=Utility;
 	HEREDOC
+}
+
+if [ ! -f "$DATADIR"/applications/am-install.desktop ]; then
+	_create_pla_handler_desktop_file
 	if command -v update-mime-database >/dev/null 2>&1 && command -v update-desktop-database >/dev/null 2>&1 && [ ! -f /var/lib/mime/mime.cache ] && [ ! -f /var/cache/desktop/desktop.cache ]; then
 		mkdir -p "$DATADIR"/mime/packages && update-mime-database "$DATADIR"/mime
 		mkdir -p "$DATADIR"/applications && update-desktop-database "$DATADIR"/applications
 	fi
 fi
+[ -f "$DATADIR"/applications/am-install.desktop ] && rm -f "$DATADIR"/applications/am-install.desktop && _create_pla_handler_desktop_file
+
+_use_pla_install_handler() {
+	# Ask install scope
+	if command -v yad >/dev/null 2>&1; then
+		yad --title="PLA Install" --text="Install <b>$PLA_APP</b>?" --button="System-Wide:0" --button="User:1"
+		RET=$?
+	elif command -v zenity >/dev/null 2>&1; then
+		zenity --question --title="PLA Install" --text="Install <b>$PLA_APP</b>?" --ok-label="System-Wide" --cancel-label="User"
+		RET=$?
+	else
+		RET=1
+	fi
+
+	if [ "$RET" -eq 0 ]; then
+		SCOPE="system"
+	elif [ "$RET" -eq 1 ]; then
+		SCOPE="user"
+	else
+		exit 1
+	fi
+
+	# Pick CMD based on the requested scope
+	if [ "$SCOPE" = "system" ]; then
+		if ! command -v am >/dev/null 2>&1; then
+			echo "Error: System-wide install requires 'am', which isn't installed."
+			read -p "Press [ENTER] to exit..."
+			exit 1
+		else
+			am -i "$PLA_APP"
+		fi
+	elif [ "$SCOPE" = "user" ]; then
+		if command -v am >/dev/null 2>&1; then
+			am -i --user "$PLA_APP"
+		else
+			appman -i "$PLA_APP"
+		fi
+	fi
+	printf "\n"
+	echo "Process finished."
+	read -p "Press [ENTER] to close this window..."
+}
 
 # VERSION OF THE INSTALLED APPS
 # Filters
@@ -2339,6 +2386,9 @@ case "$1" in
 		;;
 	'newrepo'|'neodb')
 		_use_newrepo "$@"
+		;;
+	'pla-install-handler')
+		_use_pla_install_handler "$@"
 		;;
 	'relocate'|'--relocate')
 		_use_relocate "$@"
