AM 4.2.2-6~1
I just added a check option to the "am -H" command, in case the topic folder doesn't exist.

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -302,6 +302,9 @@ case "$1" in
 		exit
 	else
 	cd /opt
+	if ! test -d ./$arg; then
+		echo ' ERROR: "'$arg'" is not installed'
+	else
 	case $arg in
     	*) keyword=$(grep -hios appimage ./$arg/AM-updater ./$arg/version | tail -1 | tr A-Z a-z 2> /dev/null)
     	if [ "$keyword" = "appimage" ]; then
@@ -321,6 +324,7 @@ case "$1" in
     		else echo ' ERROR: "'$arg'" is NOT an AppImage'; break
     	fi
     	esac
+    	fi
     	fi
     	done
     	done
@@ -1097,6 +1101,6 @@ case "$1" in
 	done
 	shift;;
   'version'|'-v'|'--version')
-  	echo "4.2.2-6";;
+  	echo "4.2.2-6~1";;
   *) exec $AMPATH/APP-MANAGER ;;
 esac
