Update APP-MANAGER
...add support for updates in AppImages integrated with "--laungher"

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-AMVERSION="9.1.3"
+AMVERSION="9.2"
 
 # Determine main repository and branch
 AMREPO="https://raw.githubusercontent.com/ivan-hc/AM/main"
@@ -805,6 +805,13 @@ function _use_sync() {
 #				UPDATE
 ################################################################################
 
+function _update_updatable_apps_msg_head() {
+	printf " \"%b\" CAN MANAGE UPDATES FOR THE FOLLOWING PROGRAMS:\n%b\n\n" "$AMCLIUPPER" "$DIVIDING_LINE"
+	[ -f "$AMCACHEDIR/updatable-args-list" ] && grep "◆" "$AMCACHEDIR/updatable-args-list" | sort || echo " None"
+	printf "\n All self-updatable programs are excluded\n"
+	echo "$DIVIDING_LINE"
+}
+
 function _update_list_updatable_apps() {
 	_determine_args
 	_check_version
@@ -884,6 +891,33 @@ function _update_all_apps() {
 	[ -d "$APPMAN_APPSPATH" ] && rm -Rf "$APPMAN_APPSPATH"/*/tmp
 }
 
+function _update_launchers_not_found_msg() {
+	MISSING_LAUNCHERS_MSG=" No launcher found."
+	printf "%b\n%b\n%b\n" "$DIVIDING_LINE" "$MISSING_LAUNCHERS_MSG" "$DIVIDING_LINE"
+}
+
+function _update_launchers() {
+	_clean_launchers 2>/dev/null 1>/dev/null
+	MISSING_LAUNCHERS_MSG="No launcher found, use option \"--launcher\" to create them."
+	[ ! -d "$DATADIR"/applications/AppImages ] && _update_launchers_not_found_msg && exit 0
+	[ -d "$DATADIR"/applications/AppImages ] && [ -z "$( ls -A "$DATADIR"/applications/AppImages )" ] && _update_launchers_not_found_msg && exit 0
+	if ! command -v appimageupdatetool 1>/dev/null; then
+		update_launchers_error_message=" 💀 ERROR! Missing command \"${RED}appimageupdatetool\033[0m\", install it and retry!"
+		printf "%b\n%b\n%b\n" "$DIVIDING_LINE" "$update_launchers_error_message" "$DIVIDING_LINE"
+	else
+		echo "$DIVIDING_LINE"
+		echo " >> UPDATE LOCAL APPIMAGES <<"
+		for var in "$DATADIR"/applications/AppImages/*.desktop; do
+			appimage_full_path=$(grep "^Exec=" 0<"$var" 2>/dev/null | head -1 | cut -c 6- | sed 's/"//g; s/\s.*$//')
+			appimagename=$(basename -- "$appimage_full_path")
+			appimage_path=$(echo "$appimage_full_path" | sed -E 's|/[^/]+$|/|')
+			appimage_updating_msg="◆ Trying to update $appimagename..."
+			printf "%b\n%b\n\n" "$DIVIDING_LINE" "$appimage_updating_msg"
+			appimageupdatetool -Or "$appimage_full_path"
+		done
+	fi
+}
+
 function _use_update() {
 	_online_check
 	_update_github_api_key_in_the_updater_files
@@ -897,20 +931,23 @@ function _use_update() {
 	if [ -z "$ENTRIES" ]; then
 		_clean_amcachedir
 		_update_list_updatable_apps
-		echo -e "$DIVIDING_LINE\n \"$AMCLIUPPER\" CAN MANAGE UPDATES FOR THE FOLLOWING PROGRAMS:\n"
-		[ -f "$AMCACHEDIR/updatable-args-list" ] && grep "◆" "$AMCACHEDIR/updatable-args-list" | sort || echo " None"
-		echo -e "\n All self-updatable programs are excluded"
-		echo -e "$DIVIDING_LINE\n >> START OF ALL PROCESSES <<\n$DIVIDING_LINE"
-		_update_all_apps
-		if ! echo "$FLAGS" | grep -q -- "--apps"; then
-			echo "$DIVIDING_LINE"
+		printf "%b\n >> START OF ALL PROCESSES << \n%b\n" "$DIVIDING_LINE" "$DIVIDING_LINE"
+		if echo "$FLAGS" | grep -q -- "--apps"; then
+			_update_updatable_apps_msg_head
+			_update_all_apps
+		elif echo "$FLAGS" | grep -q -- "--launcher"; then
+			_update_launchers
+		else
+			_update_updatable_apps_msg_head
+			_update_all_apps
 			_use_sync
-			echo -e " >> END OF ALL PROCESSES << \n$DIVIDING_LINE"
+			printf " >> END OF ALL PROCESSES << \n%b\n" "$DIVIDING_LINE"
 			sleep 0.2
 			exit 0
-		else
-			echo "$DIVIDING_LINE"
 		fi
+		printf "%b\n >> END OF ALL PROCESSES << \n%b\n" "$DIVIDING_LINE" "$DIVIDING_LINE"
+		sleep 0.2
+		exit 0
 	else
 		[ -n "$debug_update" ] && echo "$DIVIDING_LINE"
 		_determine_args
@@ -1262,9 +1299,10 @@ case "$1" in
 					${LightBlue}$AMCLI -u --debug
 					${LightBlue}$AMCLI -u --apps --debug
 					${LightBlue}$AMCLI -u {PROGRAM}\033[0m
-					${LightBlue}$AMCLI -u --debug {PROGRAM}\033[0m
+					${LightBlue}$AMCLI -u --debug {PROGRAM}
+					${LightBlue}$AMCLI -u --launcher\033[0m
 
-			Description: Update everything. Add \"--apps\" to update only the apps or write only the apps you want to update by adding their names. Add the \"--debug\" flag to view the output of AM-updater scripts.
+			Description: Update everything. Add \"--apps\" to update only the apps or write only the apps you want to update by adding their names. Add the \"--debug\" flag to view the output of AM-updater scripts. Add the \"--launcher\" flag to try to update only local AppImages integrated with the \"--launcher\" option (see \"--launcher\").
 
 			${Gold}version, -v\033[0m
 
@@ -1313,6 +1351,8 @@ case "$1" in
 					${LightBlue}$AMCLI --launcher /path/to/\${APPIMAGE}\033[0m
 
 			Description: Drag/drop one or more AppImages in the terminal and embed them in the apps menu and customize a command to use from the CLI.
+
+			NOTE that \"--launcher\" can be used as a flag in \"-u\" to try to update the integrated AppImages (see \"-u\"). This works only if \"appimageupdatetool\" is installed and delta updates are supported. This flag does not work miracles, I strongly suggest to use options \"-ia\" and \"-e\" instead.
 
 			${Gold}--system\033[0m
 
