Update APP-MANAGER: function to select a way to install "jq"

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -21,13 +21,12 @@ function _system_package_manager_check() {
 	osInfo[/etc/arch-release]=pacman
 	osInfo[/etc/gentoo-release]=emerge
 	osInfo[/etc/SuSE-release]=zypper
-	osInfo[/etc/debian_version]=apt-get
+	osInfo[/etc/debian_version]=apt
 	osInfo[/etc/alpine-release]=apk
-	for f in ${!osInfo[@]};	do
+
+	for f in ${!osInfo[@]}; do
 		if [[ -f $f ]];then
-			osPKGman="1"
-		else
-			osPKGman="0"
+			SysPKGMan="${osInfo[$f]}"
 		fi
 	done
 }
@@ -199,12 +198,10 @@ function _use_betatester_off() {
 
 # DOWNLOAD PORTABLE DEPENDENCES
 function _portable_dependences_setup() {
-	mkdir -p "$AMPATH"/bin
 
 	function _jq_installer() {
-		if command -v jq 1>/dev/null; then
-			amjq="jq"
-		else
+		function _jq_downloader() {
+			mkdir -p "$AMPATH"/bin
 			amjq="$AMPATH/bin/jq"
 			jqversion=$(curl -Ls $HeaderAuthWithGITPAT https://api.github.com/repos/jqlang/jq/releases | sed 's/[()",{}]/ /g; s/ /\n/g' | grep -o "https.*linux.*$jqarch" | head -1)
 			if ! test -f "$AMPATH"/bin/jq; then
@@ -222,6 +219,24 @@ function _portable_dependences_setup() {
 					echo -ne "Updating $AMPATH/bin/jq...\r"
 					wget -q "$jqversion" -O "$AMPATH"/bin/jq && echo "$jqversion" >> "$AMPATH"/bin/jq-version && chmod a+x "$AMPATH"/bin/jq
 				fi
+			fi
+		}
+
+		if ! command -v jq 1>/dev/null; then
+
+			_system_package_manager_check
+
+			if [[ ! -z "$SysPKGMan" ]];then
+				echo -e " ${RED}💀 ERROR!\033[0m Missing essential command ${Green}jq\033[0m"
+				read -p " Do you wish to install it using $AMCLI (Y,n)? "
+				case $yn in
+				'N'|'n')	echo -e "Missing essential command ${RED}jq\033[0m, aborted!"; exit;;
+				'Y'|'y'|*)	_jq_downloader
+					;;
+				esac
+			else
+				echo -e " ${RED}💀 ERROR!\033[0m Missing essential command ${Green}jq\033[0m"
+				echo " Install it from your package manager \"$SysPKGMan\" and retry"; exit
 			fi
 		fi
 	}
