"AM" 9.9 - clone configurations and relocate AppMan apps (#1818)
* Add option to clone/read the/a list of apps installed/to install

see https://github.com/ivan-hc/AM/issues/1817#issuecomment-3303621541

* Option "clone" with "-i"  flag installs apps from a list

...now you can clone other's configurations, including apps installed locally and system-wide in AM

* List apps to clone by separating local apps from system apps

* Draft new option "relocate"

* Option "clone -i", add a confirmation prompt to install the listed apps

* Add option "relocate", to reinstall AppMan apps to a new location

fix https://github.com/ivan-hc/AM/issues/1817

* Add the new options "relocate" and "clone" to the "help" message

* Update README.md

* Update APP-MANAGER

* Update language-updater.yml (move to dev)

* Sync locale files

* Update italian and part of serbian

* Sync locale files

* Fix typo in italian language

* Sync locale files

* Use flags --user and --system to the "clone" option (see -h)

* Sync locale files

* Fix some translations

* Sync locale files

* Update README.md

* Improve prompt in --relocate

* Sync locale files

* Update italian

* Sync locale files

* Sync with main (#1819)

* Add mudlet

fix https://github.com/mijorus/gearlever/issues/318
fix https://github.com/mijorus/gearlever/issues/319

* Add mudlet (sync lists) [d739c873519584d70d58602fcb8e767ff071b96a]

---------

Co-authored-by: web-flow <noreply@github.com>

* Create clone.md

* Update clone.md

* Update README.md

* Update README.md

* Create relocate.md (draft)

* Update README.md

* Update relocate.md

* Update clone.md

* Update relocate.md

* Update APP-MANAGER

* Sync locale files

* Update APP-MANAGER

* Update clone.md

* Option "clone", improve system/local app setting with flag

* Update language-updater.yml

* Fix parent directory /opt in "clone" and "relocate"

* Update APP-MANAGER

---------

Co-authored-by: ivan-hc <noreply@github.com>

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-AMVERSION="9.8.2-3"
+AMVERSION="9.9"
 
 # Determine main repository and branch
 AMREPO="https://raw.githubusercontent.com/ivan-hc/AM/main"
@@ -632,11 +632,11 @@ fi
 ################################################################################################################################################################
 
 # COMPLETION LIST
-available_options="about add apikey backup clean config disable downgrade download enable extra files hide home icons info \
-	install install-appimage launcher list lock neodb newrepo nolibfuse off on overwrite purge query reinstall remove sandbox \
-	select sync template test translate unhide unlock update --all --appimages --apps --byname --config --convert --debug \
+available_options="about add apikey backup clean clone config disable downgrade download enable extra files hide home icons info \
+	install install-appimage launcher list lock neodb newrepo nolibfuse off on overwrite purge query reinstall relocate remove sandbox \
+	select sync template test translate unhide unlock update --all --appimages --apps --byname --clone --config --convert --debug \
 	--devmode-disable --devmode-enable --disable-notifications --enable-notifications --force-latest --home --icons \
-	-ias --launcher --less --pkg --portable --rollback --disable-sandbox --sandbox --system --translate --user $third_party_flags"
+	-ias --launcher --less --pkg --portable --rollback --disable-sandbox --relocate --sandbox --system --translate --user $third_party_flags"
 
 _completion_lists() {
 	# Remove existing lists and download new ones
@@ -1023,6 +1023,86 @@ _use_clean() {
 }
 
 ################################################################################################################################################################
+#				CLONE
+################################################################################################################################################################
+
+_clone_create_clone_file() {
+	_determine_args
+	rm -f "$SCRIPTDIR"/am-clone.source
+	for arg in $ARGS; do
+		argpath=$(echo "$ARGPATHS" | grep "/$arg$")
+		[ -d "$argpath"/.am-installer ] && scriptname=$(ls "$argpath/.am-installer/" | head -1)
+		[ -z "$scriptname" ] && scriptname="$arg"
+		if [ "$arg" != am ]; then
+			echo "$argpath" | sed "s/\/$arg$/\/$scriptname/g" >> "$SCRIPTDIR"/am-clone.source
+		fi
+		scriptname=""
+	done
+	[ -f "$SCRIPTDIR"/am-clone.source ] && CLONE_FILE="$SCRIPTDIR/am-clone.source"
+}
+
+_clone_show_items_msg() {
+	echo "$DIVIDING_LINE"
+	if [ -f "$CLONE_FILE" ]; then
+		CLONE_FILE_CONTENT=$(sort -u "$CLONE_FILE")
+		if echo "$@" | grep -q -- "system"; then
+			CLONE_FILE_CONTENT=$(echo "$CLONE_FILE_CONTENT" | sed 's#^#/opt/#; s#//#/#g')
+		elif echo "$@" | grep -q -- "user"; then
+			CLONE_FILE_CONTENT=$(echo "$CLONE_FILE_CONTENT" | sed 's#^/opt/#/local/#g; s#//#/#g')
+		fi
+		printf "File: %b\n" "$CLONE_FILE"
+		system_apps=$(echo "$CLONE_FILE_CONTENT" | grep "^/opt/" 2>/dev/null | sed -- 's:.*/::; s/^/ - /g' | sort -u)
+		local_apps=$(echo "$CLONE_FILE_CONTENT" | grep -v "^/opt/" 2>/dev/null | sed -- 's:.*/::; s/^/ - /g' | sort -u)
+		[ -n "$system_apps" ] && printf "\nContent (system-wide installation):\n\n%b\n" "$system_apps" | _fit
+		[ -n "$local_apps" ] && printf "\nContent (local/rootless installation):\n\n%b\n" "$local_apps" | _fit
+	else
+		echo " ERROR: am-clone.source file not found"
+	fi
+	echo "$DIVIDING_LINE"
+}
+
+_clone_install() {
+	if [ -f "$CLONE_FILE" ]; then
+		AMCLIPATH_ORIGIN="$AMCLIPATH"
+		ARGS=$(echo "$CLONE_FILE_CONTENT" | sed 's:.*/::' | xargs)
+		for arg in $ARGS; do
+			argpath=$(echo "$CLONE_FILE_CONTENT" | grep "/$arg$")
+			if [ "$AMCLI" = "am" ] && ! echo "$argpath" | grep -q "^/opt/"; then
+				"$AMCLIPATH_ORIGIN" -i --user "$arg"
+			else
+				"$AMCLIPATH_ORIGIN" -i "$arg"
+			fi
+		done
+	else
+		echo "$DIVIDING_LINE"
+		echo " ERROR: am-clone.source file not found"
+		echo "$DIVIDING_LINE"
+	fi
+}
+
+_use_clone() {
+	[ -z "$CLONE_FILE" ] && CLONE_FILE=$(find "$SCRIPTDIR" -type f -name am-clone.source 2>/dev/null | head -1)
+	[ -z "$CLONE_FILE" ] && CLONE_FILE=$(find "$HOME" -type f -name am-clone.source 2>/dev/null | grep -v "share/Trash" | head -1)
+	[ -z "$CLONE_FILE" ] && CLONE_FILE=$(find / -type f -name am-clone.source 2>/dev/null | grep -v "share/Trash" | head -1)
+	if [ -z "$CLONE_FILE" ]; then
+		_clone_create_clone_file
+	fi
+	if echo "$1" | grep -q -- "clone"; then
+
+		_clone_show_items_msg "$@"
+
+		if echo "$@" | grep -oq -- "install\|-i"; then
+			read -r -p $" Do you want to install the set of programs listed above (y,N)?" yn
+			if ! echo "$yn" | grep -i '^y' >/dev/null 2>&1; then
+				echo "$DIVIDING_LINE"
+			else
+				_clone_install "$@"
+			fi
+		fi
+	fi
+}
+
+################################################################################################################################################################
 #				HIDE/UNHIDE
 ################################################################################################################################################################
 
@@ -1040,6 +1120,41 @@ _use_hide_unhide() {
 			[ -n "$APPMAN_APPSPATH" ] && [ -f "$APPMAN_APPSPATH/$arg/remove.old" ] && mv "$APPMAN_APPSPATH/$arg/remove.old" "$APPMAN_APPSPATH/$arg/remove" && echo $"✔ $APPMAN_APPSPATH/$arg can be managed again"
 		done
 		_clean_amcachedir
+	fi
+}
+
+################################################################################################################################################################
+#				RELOCATE
+################################################################################################################################################################
+
+_use_relocate() {
+	if [ ! -f "$APPMANCONFIG"/appman-config ]; then
+		echo "$DIVIDING_LINE"
+		echo " ERROR: appman-config file not found"
+		echo "$DIVIDING_LINE"
+	else
+		APPMAN_APPSPATH=$(sort "$APPMANCONFIG/appman-config")
+		printf $"The local path currently in use for programs is as follows:\n\n%b\n\n" "$APPMAN_APPSPATH" | _fit
+		read -r -p $" Do you want to remove and re-install everything to a new location (y,N)?" yn
+		if echo "$yn" | grep -i '^y' >/dev/null 2>&1; then
+			AMCLIPATH_ORIGIN="$AMCLIPATH"
+			rm -f "$SCRIPTDIR"/am-clone.source
+			_clone_create_clone_file
+			sort -u "$SCRIPTDIR"/am-clone.source | grep -v "^/opt/" > "$SCRIPTDIR"/am-clone.source.appman
+			_determine_args
+			APPMAN_APPS_OLD=$(echo "$ARGPATHS" | grep -v "^/opt/")
+			if [ -n "$APPMAN_APPS_OLD" ]; then
+				for arg in $APPMAN_APPS_OLD; do
+					appname=$(echo "$arg" | sed 's:.*/::')
+					"$AMCLIPATH_ORIGIN" -R "$appname"
+				done
+			fi
+			rm -f "$APPMANCONFIG"/appman-config
+			_appman
+			APPMAN_APPS_NEW=$(sort -u "$SCRIPTDIR"/am-clone.source.appman | sed 's:.*/::' | xargs)
+			"$AMCLIPATH_ORIGIN" -i --user "$APPMAN_APPS_NEW"
+		fi
+		
 	fi
 }
 
@@ -1493,6 +1608,9 @@ case "$1" in
 	'clean'|'-c')
 		_use_clean
 		;;
+	'clone'|'--clone')
+		_use_clone "$@"
+		;;
 	'devmode-disable'|'devmode-enable'|'--devmode-disable'|'--devmode-enable')
 		if [ "$CLI_PATH" = "/usr/bin/am" ]; then
 			echo $"This feature is disabled by your organization" | _fit
@@ -1527,6 +1645,9 @@ case "$1" in
 		;;
 	'newrepo'|'neodb')
 		_use_newrepo "$@"
+		;;
+	'relocate'|'--relocate')
+		_use_relocate "$@"
 		;;
 	'sync'|'-s')
 		_use_sync
@@ -1589,6 +1710,18 @@ case "$1" in
 					${LightBlue}$AMCLI -c\033[0m
 
 			Description: Removes all the unnecessary files and folders.
+
+			${Gold}clone, --clone\033[0m
+
+					${LightBlue}$AMCLI --clone
+					${LightBlue}$AMCLI --clone -i
+					${LightBlue}$AMCLI --clone -i --system
+					${LightBlue}$AMCLI --clone -i --user\033[0m
+
+			Description: Clone the list of installed apps to an \"am-clone.source\" file, or search for an existing one on the desktop (priority), in $HOME, or across the entire system and removable devices. Add \"-i\" or \"install\" if you want to install or add the listed apps to a new configuration, to share it with anyone on other PCs and configurations. Add the \"--system\" or \"--user\" flag if you want all listed apps to be installed system-wide or locally respectively.
+
+			You can also set the path to a custom file by exporting the \$CLONE_FILE variable.
+
 
 			${Gold}config, -C, --config\033[0m
 
@@ -1733,6 +1866,13 @@ case "$1" in
 			Description: Reinstall only programs whose installation script has been modified in AM's online database. Use the \"--all\" flaf to reinstall everything instead.
 
 			NOTE, this only works with the \"AM\" database. Apps installed with the \"-e\" option and custom scripts created with the \"-t\" option are not supported.
+
+			${Gold}relocate, --relocate\033[0m
+
+					${LightBlue}$AMCLI --relocate\033[0m
+
+			Description: Remove and reinstall local/AppMan apps to a new location.
+
 
 			${Gold}remove, -r\033[0m
 
