Move _am_dependeces_check

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -156,7 +156,23 @@ function _appman_message_before_installation() {
 	fi
 }
 
+# Dependencies checks should be here, right after everything in _am and _appman functions is done
+function _am_dependences_check() {
+	# Check for essential commands required by the application
+	missing_deps=()
+	for name in cat chmod chown curl grep sed wget; do
+		if ! command -v "$name" &>/dev/null; then
+			printf "\nERROR: command \"%s\" not found, strongly needed by \"%s\"!\n" "$name" "$AMCLI"
+		missing_deps+=("$name")
+		fi
+	done
 
+	# Exit if any essential command is missing
+	if [ -n "$missing_deps" ]; then
+		printf "\nMissing essential commands: %s\nInstall the above and try again\n\n" "${missing_deps[*]}"
+		exit 1
+	fi
+}
 
 
 
@@ -204,22 +220,6 @@ fi
 
 # FUNCTIONS RELATED TO THE SAFE USE OF "AM"
 function _am_security_check() {
-	function _am_dependences_check() {
-		# Check for essential commands required by the application
-		missing_deps=()
-		for name in cat chmod chown curl grep sed wget; do
-			if ! command -v "$name" &>/dev/null; then
-				printf "\nERROR: command \"%s\" not found, strongly needed by \"%s\"!\n" "$name" "$AMCLI"
-			missing_deps+=("$name")
-			fi
-		done
-
-		# Exit if any essential command is missing
-		if [ -n "$missing_deps" ]; then
-			printf "\nMissing essential commands: %s\nInstall the above and try again\n\n" "${missing_deps[*]}"
-			exit 1
-		fi
-	}
 
 	_am_dependences_check
 
