Increased readability with whitespace.

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -300,51 +300,62 @@ case "$1" in
 	;;
 
   '-f'|'files')
-    	if [ -n "$SUDO_COMMAND" ]; then echo -e "\n WARNING: You don't need to run the option '$1' with SUDO.\n"; exit; fi
+    	if [ -n "$SUDO_COMMAND" ]; then 
+		echo -e "\n WARNING: You don't need to run the option '$1' with SUDO.\n"; 
+		exit; 
+	fi
+
   	echo ""; echo $(echo "YOU HAVE INSTALLED "; cd /opt && find . -type f -name 'remove' 2>/dev/null | sed -r 's|/[^/]+$||' | sort | uniq | wc -l;
   	echo " STANDALONE PROGRAMS MANAGED BY THE 'AM' COMMAND:"); echo "";
   	cd /opt && find -name 'remove' -printf "%h\n" 2>/dev/null | sort -u | echo $(xargs -n 1 basename 2> /dev/null) | du -sh $(find . -type f -name 'remove' 2>/dev/null | sed -r 's|/[^/]+$||' | sort | uniq | cut -c 3-) | awk '{ print " ◆ "$2 " - " $1"iB of disk space used"}' | grep -w -v "◆ ."; echo "" 
 	;;
 
   '-H'|'--home')
-    	if [ -n "$SUDO_COMMAND" ]; then echo -e "\n WARNING: You don't need to run the option '$1' with SUDO.\n"; exit; fi
-    	while [ -n "$1" ]
-	do
-	rm -f $AMPATH/.cache/home-args
-	echo $@ | tr ' ' '\n' >> $AMPATH/.cache/home-args && echo STOP >> $AMPATH/.cache/home-args
-	ARGS=$(tail +2 $AMPATH/.cache/home-args)
-	for arg in $ARGS; do
-	for var in $arg; do
-	if [ $arg == STOP ]; then
-		exit
-	else
-	cd /opt
-	if ! test -d ./$arg; then
-		echo ' ERROR: "'$arg'" is not installed'
-	else
-	case $arg in
-    	*) keyword=$(grep -hios appimage ./$arg/AM-updater ./$arg/version | tail -1 | tr A-Z a-z 2> /dev/null)
-    	if [ "$keyword" = "appimage" ]; then
-  		cd ./$arg
-    		./$arg --appimage-extract AppRun > /dev/null 2>&1
-    		if test -f ./squashfs-root/AppRun; then
-    			mkdir -p ./$arg.home
-    			echo ' Setting $HOME to /opt/'$arg'/'$arg'.home for this AppImage'
-    			rm -R -f ./squashfs-root; break
-    		elif test -h ./squashfs-root/AppRun; then
-    			mkdir -p ./$arg.home
-    			echo ' Setting $HOME to /opt/'$arg'/'$arg'.home for this AppImage'
-    			rm -R -f ./squashfs-root; break
-    		else
-    			echo ' ERROR: "'$arg'" is NOT an AppImage'; break
-    		fi
-    		else echo ' ERROR: "'$arg'" is NOT an AppImage'; break
-    	fi
-    	esac
-    	fi
-    	fi
-    	done
-    	done
+    	if [ -n "$SUDO_COMMAND" ]; then 
+		echo -e "\n WARNING: You don't need to run the option '$1' with SUDO.\n"; 
+		exit; 
+	fi
+
+    	while [ -n "$1" ]; do
+		rm -f $AMPATH/.cache/home-args
+		echo $@ | tr ' ' '\n' >> $AMPATH/.cache/home-args && echo STOP >> $AMPATH/.cache/home-args
+		ARGS=$(tail +2 $AMPATH/.cache/home-args)
+
+		for arg in $ARGS; do
+			for var in $arg; do
+				if [ $arg == STOP ]; then
+					exit
+				else
+					cd /opt
+					if ! test -d ./$arg; then
+						echo ' ERROR: "'$arg'" is not installed'
+					else
+						case $arg in
+    						*) 
+							keyword=$(grep -hios appimage ./$arg/AM-updater ./$arg/version | tail -1 | tr A-Z a-z 2> /dev/null)
+
+    							if [ "$keyword" = "appimage" ]; then
+  								cd ./$arg
+    								./$arg --appimage-extract AppRun > /dev/null 2>&1
+    								if test -f ./squashfs-root/AppRun; then
+    									mkdir -p ./$arg.home
+    									echo ' Setting $HOME to /opt/'$arg'/'$arg'.home for this AppImage'
+    									rm -R -f ./squashfs-root; break
+    								elif test -h ./squashfs-root/AppRun; then
+    									mkdir -p ./$arg.home
+    									echo ' Setting $HOME to /opt/'$arg'/'$arg'.home for this AppImage'
+    									rm -R -f ./squashfs-root; break
+    								else
+    									echo ' ERROR: "'$arg'" is NOT an AppImage'; break
+    								fi
+    							else 
+								echo ' ERROR: "'$arg'" is NOT an AppImage'; break
+    							fi
+    						esac
+    					fi
+    				fi
+    			done
+    		done
     	done
 	;;
 
