handle errors in `INSTALL`

diff --git a/INSTALL b/INSTALL
--- a/INSTALL
+++ b/INSTALL
@@ -37,7 +37,10 @@ _prepare_am_directory() {
 	chmod a+x /opt/am/remove || exit 1
 
 	# DOWNLOAD AND LINK THE MAIN SCRIPT
-	wget -q "https://raw.githubusercontent.com/ivan-hc/AM/$AM_BRANCH/APP-MANAGER"
+	if ! wget -q "https://raw.githubusercontent.com/ivan-hc/AM/$AM_BRANCH/APP-MANAGER"; then
+		echo "💀 ERROR: Cannot download am"
+		exit 1
+	fi
 	chmod a+x /opt/am/APP-MANAGER
 	ln -s /opt/am/APP-MANAGER /usr/local/bin/am 2> /dev/null || printf "${RED}WARNING: Couldn't link am to \"/usr/local/bin/am\"!\033[0m\n"
 }
@@ -46,6 +49,10 @@ _download_am_modules() {
 	# DOWNLOAD MODULES
 	cd /opt/am/modules || exit
 	MODULES=$(curl -Ls "https://raw.githubusercontent.com/ivan-hc/AM/$AM_BRANCH/APP-MANAGER" | tr '"' '\n' | grep "[a-z]\.am$")
+	if [ -z "$MODULES" ]; then
+		echo "💀 ERROR: Cannot download am modules"
+		exit 1
+	fi
 	for module_name in $MODULES; do
 		if [ ! -f ./"$module_name" ]; then
 			echo " ◆ Downloading $module_name..."
@@ -56,7 +63,7 @@ _download_am_modules() {
 	cd ..
 
 	# ENABLE NON-ROOT PERMISSIONS TO THE MAIN DIRECTORY FOR THE CURRENT USER
-	chown -R "${SUDO_USER:-$DOAS_USER}" /opt/am 2>/dev/null
+	chown -R "${SUDO_USER:-$DOAS_USER}" /opt/am
 }
 
 echo '--------------------------------------------------------------------------'
