Update INSTALL
Chek if "sudo" or "doas" is installed, else abort the installation.

diff --git a/INSTALL b/INSTALL
--- a/INSTALL
+++ b/INSTALL
@@ -19,6 +19,11 @@ _check_dependency() {
 
 _check_dependency
 
+if [ -z "${SUDO_USER:-$DOAS_USER}" ]; then
+	echo 'ERROR: No sudo or doas found'
+	exit 1
+fi
+
 # INSTALL "AM"
 _prepare_am_directory() {
 	# CREATE AND ENTER THE MAIN DIRECTORY FOR "AM"
