Update some installation scripts for aarch64

diff --git a/programs/aarch64/btop b/programs/aarch64/btop
--- a/programs/aarch64/btop
+++ b/programs/aarch64/btop
@@ -1,58 +1,55 @@
 #!/bin/sh
 
+# AM INSTALL SCRIPT VERSION 3. 
+set -u
 APP=btop
-REPO="aristocratos/btop"
+SITE="aristocratos/btop"
 
-# CREATE DIRECTORIES
-if [ -z "$APP" ]; then exit 1; fi
-mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
+# CREATE DIRECTORIES AND ADD REMOVER
+[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
+printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
+#printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
+chmod a+x ../remove || exit 1
 
-# ADD THE REMOVER
-echo "#!/bin/sh
-rm -f /usr/local/share/applications/$APP-AM.desktop /usr/local/bin/$APP
-rm -R -f /opt/$APP" >> "/opt/$APP/remove"
-chmod a+x "/opt/$APP/remove"
-
-# DOWNLOAD AND PREPARE THE APP
-# $version is also used for updates
-
-version=$(curl -Ls https://api.github.com/repos/"$REPO"/releases/latest | grep browser_download_url | grep aarch64 | cut -d '"' -f 4 | head -1)
-wget "$version"
-tar xf ./*.tbz
+# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
+version=$(curl -Ls https://api.github.com/repos/aristocratos/btop/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -i "aarch64" | head -1)
+wget "$version" || exit 1
+[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
+[ -e ./*tbz ] && tar fx ./*tbz && rm -f ./*tbz
+[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
 cd ..
-echo "$version" >> ./version
-mv ./tmp/*/* ./
-ln -s ./bin/btop ./"$APP"
-chmod a+x ./bin/btop
-rm -R -f ./tmp
+if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
+rm -R -f ./tmp || exit 1
+echo "$version" > ./version
+chmod a+x ./bin/btop || exit 1
 
-# LINK
-ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"
+# LINK TO PATH
+ln -s "/opt/$APP/bin/btop" "/usr/local/bin/$APP"
 
 # SCRIPT TO UPDATE THE PROGRAM
-cat >> /opt/$APP/AM-updater << 'EOF'
+cat >> ./AM-updater << 'EOF'
 #!/bin/sh
+set -u
 APP=btop
-REPO="aristocratos/btop"
-version0=$(cat /opt/$APP/version)
-version=$(curl -Ls https://api.github.com/repos/"$REPO"/releases/latest | grep browser_download_url | grep aarch64 | cut -d '"' -f 4 | head -1)
-if [ "$version" = "$version0" ]; then
-	echo "Update not needed!" || exit 0
-else
+SITE="aristocratos/btop"
+version0=$(cat "/opt/$APP/version")
+version=$(curl -Ls https://api.github.com/repos/aristocratos/btop/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -i "aarch64" | head -1)
+[ -n "$version" ] || { echo "Error getting link"; exit 1; }
+if [ "$version" != "$version0" ]; then
+	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
 	notify-send "A new version of $APP is available, please wait"
-	mkdir /opt/$APP/tmp && cd /opt/$APP/tmp || exit 1
-	wget "$version"
-	tar xf ./*.tbz
+	wget "$version" || exit 1
+	[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
+	[ -e ./*tbz ] && tar fx ./*tbz && rm -f ./*tbz
+	[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
 	cd ..
-	rm ./version
-  	echo "$version" >> ./version
-  	mv --backup=t ./tmp/*/* ./
-	chmod a+x ./bin/btop
-  	rm -R -f ./tmp ./*~
+	if [ -d ./tmp/* 2>/dev/null ]; then mv --backup=t ./tmp/*/* ./; else mv --backup=t ./tmp/* ./"$APP" 2>/dev/null || mv --backup=t ./tmp/* ./; fi
+	chmod a+x ./bin/btop || exit 1
+	echo "$version" > ./version
+	rm -R -f ./tmp ./*~
 	notify-send "$APP is updated!"
+else
+	echo "Update not needed!"
 fi
 EOF
-chmod a+x "/opt/$APP/AM-updater"
-
-# LAUNCHER & ICON
-mv ./*.desktop /usr/local/share/applications/"$APP"-AM.desktop && mv ./*mg/*.svg ./icons/btop 2>/dev/null #btop already ships the files
+chmod a+x ./AM-updater || exit 1
diff --git a/programs/aarch64/streamlink b/programs/aarch64/streamlink
--- a/programs/aarch64/streamlink
+++ b/programs/aarch64/streamlink
@@ -1,65 +1,77 @@
 #!/bin/sh
 
+# AM INSTALL SCRIPT VERSION 3.5
+set -u
 APP=streamlink
+SITE="streamlink/streamlink-appimage"
 
-# CREATE THE FOLDER
-mkdir /opt/$APP
-cd /opt/$APP
+# CREATE DIRECTORIES AND ADD REMOVER
+[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
+printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
+printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
+chmod a+x ../remove || exit 1
 
-# ADD THE REMOVER
-echo '#!/bin/sh' >> /opt/$APP/remove
-echo "rm -R -f /usr/local/share/applications/$APP-AM.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
-chmod a+x /opt/$APP/remove
-
-# DOWNLOAD THE APPIMAGE
-mkdir tmp
-cd ./tmp
-
-wget https://github.com/$(wget https://github.com/streamlink/streamlink-appimage/releases/latest | grep -E '/.*/.*/.*aarch64.AppImage' -o);
-
-version=$(ls /opt/$APP/tmp)
-echo "$version" >> /opt/$APP/version
-
+# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
+version=$(curl -Ls https://api.github.com/repos/streamlink/streamlink-appimage/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -i "aarch64" | head -1)
+wget "$version" || exit 1
+# Keep this space in sync with other installation scripts
+# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
 cd ..
-mv ./tmp/*mage ./$APP
-chmod a+x /opt/$APP/$APP
-rmdir ./tmp
+mv ./tmp/*mage ./"$APP"
+# Keep this space in sync with other installation scripts
+rm -R -f ./tmp || exit 1
+echo "$version" > ./version
+chmod a+x ./"$APP" || exit 1
 
-# LINK
-ln -s /opt/$APP/$APP /usr/local/bin/$APP
+# LINK TO PATH
+ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"
 
 # SCRIPT TO UPDATE THE PROGRAM
-echo '#!/bin/sh' >> /opt/$APP/AM-updater
-echo "APP=$APP" >> /opt/$APP/AM-updater
-echo "cd /opt/$APP" /usr/local/bin/$APP
-echo 'version0=$(cat /opt/$APP/version)
+cat >> ./AM-updater << 'EOF'
+#!/bin/sh
+set -u
+APP=streamlink
+SITE="streamlink/streamlink-appimage"
+version0=$(cat "/opt/$APP/version")
+version=$(curl -Ls https://api.github.com/repos/streamlink/streamlink-appimage/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -vi "aarch64" | head -1)
+[ -n "$version" ] || { echo "Error getting link"; exit 1; }
+if command -v appimageupdatetool >/dev/null 2>&1; then
+	cd "/opt/$APP" || exit 1
+	appimageupdatetool -Or ./"$APP" && chmod a+x ./"$APP" && echo "$version" > ./version && exit 0
+fi
+if [ "$version" != "$version0" ]; then
+	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
+	notify-send "A new version of $APP is available, please wait"
+	wget "$version" || exit 1
+	# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
+	cd ..
+	mv --backup=t ./tmp/*mage ./"$APP"
+	chmod a+x ./"$APP" || exit 1
+	echo "$version" > ./version
+	rm -R -f ./*zs-old ./*.part ./tmp ./*~
+	notify-send "$APP is updated!"
+else
+	echo "Update not needed!"
+fi
+EOF
+chmod a+x ./AM-updater || exit 1
 
-url=https://github.com/streamlink/streamlink-appimage/releases/latest' >> /opt/$APP/AM-updater
-
-echo 'if curl -L -s $url | grep -ioF "$version0"; then' >> /opt/$APP/AM-updater
-echo '  echo "Update not needed!".'  >> /opt/$APP/AM-updater
-echo 'else' >> /opt/$APP/AM-updater
-echo "  notify-send 'A new version of $APP is available, please wait'" >> /opt/$APP/AM-updater
-echo "  mkdir /opt/$APP/tmp
-  cd /opt/$APP/tmp" >> /opt/$APP/AM-updater
-
-########################################################################################
-
-function1='$(wget https://github.com/streamlink/streamlink-appimage/releases/latest -O -'
-function2="grep -E '/.*/.*/.*aarch64.AppImage' -o)"
-function3='$(ls /opt/$APP/tmp)'
-
-echo "  wget https://github.com/$function1 | $function2
-  version=$function3" >> /opt/$APP/AM-updater
-
-########################################################################################
-
-echo '  cd ..
-  if test -f ./tmp/*mage; then rm ./version
-  fi
-  echo "$version" >> ./version' >> /opt/$APP/AM-updater
-echo "  mv ./tmp/*mage ./$APP
-  chmod a+x /opt/$APP/$APP
-  rmdir ./tmp
-fi" >> /opt/$APP/AM-updater
-chmod a+x /opt/$APP/AM-updater
+# LAUNCHER & ICON
+./"$APP" --appimage-extract *.desktop 1>/dev/null && mv ./squashfs-root/*.desktop ./"$APP".desktop
+./"$APP" --appimage-extract .DirIcon 1>/dev/null && mv ./squashfs-root/.DirIcon ./DirIcon
+COUNT=0
+while [ "$COUNT" -lt 10 ]; do # Tries to get the actual icon/desktop if it is a symlink to another symlink
+	if [ -L ./"$APP".desktop ]; then
+		LINKPATH="$(readlink ./"$APP".desktop | sed 's|^\./||' 2>/dev/null)"
+		./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./"$APP".desktop
+	fi
+	if [ -L ./DirIcon ]; then
+		LINKPATH="$(readlink ./DirIcon | sed 's|^\./||' 2>/dev/null)"
+		./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./DirIcon
+	fi
+	[ ! -L ./"$APP".desktop ] && [ ! -L ./DirIcon ] && break
+	COUNT=$((COUNT + 1))
+done
+sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g" ./"$APP".desktop
+mv ./"$APP".desktop /usr/local/share/applications/"$APP"-AM.desktop && mv ./DirIcon ./icons/"$APP" 1>/dev/null
+rm -R -f ./squashfs-root
diff --git a/programs/aarch64/ventoy b/programs/aarch64/ventoy
--- a/programs/aarch64/ventoy
+++ b/programs/aarch64/ventoy
@@ -1,68 +1,70 @@
 #!/bin/sh
 
+# AM INSTALL SCRIPT VERSION 3. 
+set -u
 APP=ventoy
 SITE="ventoy/Ventoy"
 
-# CREATE THE FOLDER
-mkdir /opt/$APP
-cd /opt/$APP
+# CREATE DIRECTORIES AND ADD REMOVER
+[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
+printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
+printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
+chmod a+x ../remove || exit 1
 
-# ADD THE REMOVER
-echo '#!/bin/sh' >> /opt/$APP/remove
-echo "rm -R -f /usr/local/share/applications/$APP-AM.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
-chmod a+x /opt/$APP/remove
-
-# DOWNLOAD THE ARCHIVE
-mkdir tmp
-cd ./tmp
-
-version=$(curl -Ls https://api.github.com/repos/ventoy/Ventoy/releases | grep browser_download_url | grep -i linux.tar.gz  | cut -d '"' -f 4 | head -1)
-wget $version
-echo "$version" >> /opt/$APP/version
-tar fx ./*; rm -R -f ./*tar*
+# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
+version=$(curl -Ls https://api.github.com/repos/ventoy/Ventoy/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -i "linux.tar.gz" | head -1)
+wget "$version" || exit 1
+[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
+[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
+[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
 cd ..
-mv --backup=t ./tmp/ventoy-*/* ./
-rm -R -f ./tmp
+if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
+rm -R -f ./tmp || exit 1
+echo "$version" > ./version
+chmod a+x ./VentoyGUI.aarch64 || exit 1
 
 # SCRIPT TO LAUNCH THE PROGRAM
 echo '#!/bin/sh
-exec /opt/'$APP'/VentoyGUI.aarch64' >> /usr/local/bin/$APP
-chmod a+x /usr/local/bin/$APP
+exec /opt/'$APP'/VentoyGUI.aarch64' >> /usr/local/bin/"$APP"
+chmod a+x /usr/local/bin/"$APP"
 
 # SCRIPT TO UPDATE THE PROGRAM
-cat >> /opt/$APP/AM-updater << 'EOF'
-#!/usr/bin/env bash
+cat >> ./AM-updater << 'EOF'
+#!/bin/sh
+set -u
 APP=ventoy
-version0=$(cat /opt/$APP/version)
-version=$(curl -Ls https://api.github.com/repos/ventoy/Ventoy/releases | grep browser_download_url | grep -i linux.tar.gz  | cut -d '"' -f 4 | head -1)
-if [ $version = $version0 ]; then
-	echo "Update not needed!"
-else
+SITE="ventoy/Ventoy"
+version0=$(cat "/opt/$APP/version")
+version=$(curl -Ls https://api.github.com/repos/ventoy/Ventoy/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -i "linux.tar.gz" | head -1)
+[ -n "$version" ] || { echo "Error getting link"; exit 1; }
+if [ "$version" != "$version0" ]; then
+	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
 	notify-send "A new version of $APP is available, please wait"
-	mkdir /opt/$APP/tmp
-	cd /opt/$APP/tmp
-	wget $version
-	tar fx ./*; rm -R -f ./*tar*
+	wget "$version" || exit 1
+	[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
+	[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
+	[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
 	cd ..
-	mv --backup=t ./tmp/ventoy-*/* ./
-	rm ./version
-	echo $version >> ./version
+	if [ -d ./tmp/* 2>/dev/null ]; then mv --backup=t ./tmp/*/* ./; else mv --backup=t ./tmp/* ./"$APP" 2>/dev/null || mv --backup=t ./tmp/* ./; fi
+	chmod a+x ./VentoyGUI.aarch64 || exit 1
+	echo "$version" > ./version
 	rm -R -f ./tmp ./*~
 	notify-send "$APP is updated!"
+else
+	echo "Update not needed!"
 fi
 EOF
-chmod a+x /opt/$APP/AM-updater
+chmod a+x ./AM-updater || exit 1
 
 # ICON
-mkdir icons
-wget https://www.ventoy.net/static/img/ventoy.png -O ./icons/$APP 2> /dev/null
+mkdir -p icons
+wget https://www.ventoy.net/static/img/ventoy.png -O ./icons/"$APP" 2> /dev/null
 
 # LAUNCHER
-rm -f /usr/local/share/applications/$APP-AM.desktop
 echo "[Desktop Entry]
 Name=Ventoy
 Comment=Open source tool to create bootable USB drive for ISO/WIM/IMG/VHD(x)/EFI files. 
 Exec=$APP
 Icon=/opt/$APP/icons/$APP
 Type=Application
-Categories=System;" >> /usr/local/share/applications/$APP-AM.desktop
+Categories=System;" > /usr/local/share/applications/"$APP"-AM.desktop
diff --git a/programs/aarch64/vscodium b/programs/aarch64/vscodium
--- a/programs/aarch64/vscodium
+++ b/programs/aarch64/vscodium
@@ -1,84 +1,70 @@
 #!/bin/sh
 
+# AM INSTALL SCRIPT VERSION 3.5
+set -u
 APP=vscodium
+SITE="VSCodium/vscodium"
 
-# CREATE THE FOLDER
-mkdir /opt/$APP
-cd /opt/$APP
+# CREATE DIRECTORIES AND ADD REMOVER
+[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
+printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
+#printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
+chmod a+x ../remove || exit 1
 
-# ADD THE REMOVER
-echo '#!/bin/sh' >> /opt/$APP/remove
-echo "rm -R -f /usr/local/share/applications/$APP-AM.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
-chmod a+x /opt/$APP/remove
-
-# DOWNLOAD THE APPIMAGE
-mkdir tmp
-cd ./tmp
-
-v=$(curl -Ls https://api.github.com/repos/VSCodium/vscodium/releases/latest | grep -E tag_name | awk -F '[""]' '{print $4}')
-wget https://github.com/VSCodium/vscodium/releases/download/$v/VSCodium-linux-arm64-$v.tar.gz
-
-version=$(ls /opt/$APP/tmp)
-echo "$version" >> /opt/$APP/version
-
-tar fx ./*.tar.gz
-rm -f ./*.tar.gz
+# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
+version=$(FUNCTION)
+wget "$version" || exit 1
+[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
+[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
+[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
 cd ..
-mv ./tmp/* ./
-rmdir ./tmp
+if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
+rm -R -f ./tmp || exit 1
+echo "$version" > ./version
+chmod a+x ./codium || exit 1
 
-# LINK
-ln -s /opt/$APP/codium /usr/local/bin/$APP
+# LINK TO PATH
+ln -s "/opt/$APP/codium" "/usr/local/bin/$APP"
 
 # SCRIPT TO UPDATE THE PROGRAM
-echo '#!/bin/sh' >> /opt/$APP/AM-updater
-echo "APP=$APP" >> /opt/$APP/AM-updater
-echo "cd /opt/$APP" /usr/local/bin/$APP
-echo 'version0=$(cat /opt/$APP/version)
+cat >> ./AM-updater << 'EOF'
+#!/bin/sh
+set -u
+APP=vscodium
+SITE="VSCodium/vscodium"
+version0=$(cat "/opt/$APP/version")
+version=$(FUNCTION)
+[ -n "$version" ] || { echo "Error getting link"; exit 1; }
+if [ "$version" != "$version0" ]; then
+	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
+	notify-send "A new version of $APP is available, please wait"
+	wget "$version" || exit 1
+	[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
+	[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
+	[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
+	cd ..
+	if [ -d ./tmp/* 2>/dev/null ]; then mv --backup=t ./tmp/*/* ./; else mv --backup=t ./tmp/* ./"$APP" 2>/dev/null || mv --backup=t ./tmp/* ./; fi
+	chmod a+x ./codium || exit 1
+	echo "$version" > ./version
+	rm -R -f ./tmp ./*~
+	notify-send "$APP is updated!"
+else
+	echo "Update not needed!"
+fi
+EOF
+chmod a+x ./AM-updater || exit 1
 
-url=https://github.com/VSCodium/vscodium/releases/latest' >> /opt/$APP/AM-updater
-
-echo 'if curl -L -s $url | grep -ioF "$version0"; then' >> /opt/$APP/AM-updater
-echo '  echo "Update not needed!".'  >> /opt/$APP/AM-updater
-echo 'else' >> /opt/$APP/AM-updater
-echo "  notify-send 'A new version of $APP is available, please wait'" >> /opt/$APP/AM-updater
-echo "  mkdir /opt/$APP/tmp
-  cd /opt/$APP/tmp" >> /opt/$APP/AM-updater
-
-########################################################################################
-
-function1='$(curl -Ls https://api.github.com/repos/VSCodium/vscodium/releases/latest'
-part0='{print $4}'
-part1='[""]'
-function2="grep -E tag_name | awk -F '$part1' '$part0')"
-function3='$(ls /opt/$APP/tmp)'
-function4='wget https://github.com/VSCodium/vscodium/releases/download/$v/VSCodium-linux-arm64-$v.tar.gz'
-
-echo "  v=$function1 | $function2
-  $function4
-  version=$function3" >> /opt/$APP/AM-updater
-
-########################################################################################
-
-echo '  cd ..
-  if test -f ./tmp/*tar.gz; then rm ./version
-  fi
-  echo "$version" >> ./version' >> /opt/$APP/AM-updater
-echo "  tar fx ./tmp/*.tar.gz
-  rm ./tmp/*.tar.gz
-  mv ./tmp/* ./
-  rmdir ./tmp
-fi" >> /opt/$APP/AM-updater
-chmod a+x /opt/$APP/AM-updater
+# ICON
+mkdir -p icons
+wget https://portable-linux-apps.github.io/icons/vscodium.png -O ./icons/"$APP" 2> /dev/null
 
 # LAUNCHER
-rm -f /usr/local/share/applications/$APP-AM.desktop
 echo "[Desktop Entry]
 Name=VSCodium
 Comment=Code Editing. Redefined.
 GenericName=Text Editor
 Exec=vscodium --unity-launch %F
-Icon=/opt/$APP/$APP.svg
+Icon=/opt/$APP/icons/$APP
 Type=Application
 StartupNotify=false
 StartupWMClass=VSCodium
@@ -92,7 +78,4 @@ X-AppImage-Version=1.59.1-1629418630.glibc2.17
 [Desktop Action new-empty-window]
 Name=New Empty Window
 Exec=vscodium --new-window %F
-Icon=/opt/$APP/$APP.svg" >> /usr/local/share/applications/$APP-AM.desktop
-
-# ICON
-wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP/$APP.svg
+Icon=/opt/$APP/icons/$APP" > /usr/local/share/applications/"$APP"-AM.desktop
