Update AM-SAMPLE-Firefox-webapp

diff --git a/templates/AM-SAMPLE-Firefox-webapp b/templates/AM-SAMPLE-Firefox-webapp
--- a/templates/AM-SAMPLE-Firefox-webapp
+++ b/templates/AM-SAMPLE-Firefox-webapp
@@ -1,4 +1,10 @@
-#!/bin/sh
+#!/usr/bin/env bash
+
+for name in "firefox"
+do
+  [[ $(which $name 2>/dev/null) ]] || { echo "" && echo -e 'ERROR: "'$name'" not found in $PATH, exiting.';deps=1; }
+done
+[[ $deps -ne 1 ]] || { echo -e "\nInstall the above and try again\n";exit 1; }
 
 APP=SAMPLE-webapp
 APPNAME="GIVEMEANAME"
