Add files via upload

diff --git a/programs/x86_64/avidemux-nightly b/programs/x86_64/avidemux-nightly
--- a/programs/x86_64/avidemux-nightly
+++ b/programs/x86_64/avidemux-nightly
@@ -1,68 +1,55 @@
 #!/bin/sh
 
+# AM INSTALL SCRIPT VERSION 3.5
+set -u
 APP=avidemux-nightly
 SITE="https://www.avidemux.org"
 
-# CREATE THE FOLDER
-mkdir /opt/$APP
-cd /opt/$APP
+# CREATE DIRECTORIES AND ADD REMOVER
+[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
+printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
+printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
+chmod a+x ../remove || exit 1
 
-# ADD THE REMOVER
-echo '#!/bin/sh' >> /opt/$APP/remove
-echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
-chmod a+x /opt/$APP/remove
-
-# DOWNLOAD THE ARCHIVE
-mkdir tmp
-cd ./tmp
-
-version=$(echo https://www.avidemux.org/nightly/appImage4/$(curl -Ls https://www.avidemux.org/nightly/appImage4/ | grep .app | grep -i mb | grep -o -P "(?<='./).*(?='>)" | tail -1))
-wget $version
-echo "$version" >> /opt/$APP/version
+# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
+version="https://www.avidemux.org/nightly/appImage4/$(curl -Ls https://www.avidemux.org/nightly/appImage4/ | grep .app | grep -i mb | grep -o -P "(?<='./).*(?='>)" | tail -1)"
+wget "$version" || exit 1
+# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
 cd ..
-mv ./tmp/*.app ./$APP
-chmod a+x /opt/$APP/$APP
-rmdir ./tmp
+mv ./tmp/* ./"$APP"
+rm -R -f ./tmp || exit 1
+echo "$version" > ./version
+chmod a+x ./"$APP" || exit 1
 
-# LINK
-cat >> /usr/local/bin/$APP << 'EOF'
-#!/bin/sh
-APP=avidemux-nightly
-export QT_QPA_PLATFORMTHEME=$QT_QPA_PLATFORMTHEME
-export QT_STYLE_OVERRIDE=$QT_STYLE_OVERRIDE
-export QT_FONT_DPI=96
-/opt/$APP/$APP
-EOF
-chmod a+x /usr/local/bin/$APP
+# LINK TO PATH
+ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"
 
 # SCRIPT TO UPDATE THE PROGRAM
-cat >> /opt/$APP/AM-updater << 'EOF'
-#!/usr/bin/env bash
+cat >> ./AM-updater << 'EOF'
+#!/bin/sh
+set -u
 APP=avidemux-nightly
-version0=$(cat /opt/$APP/version)
-version=$(echo https://www.avidemux.org/nightly/appImage4/$(curl -Ls https://www.avidemux.org/nightly/appImage4/ | grep .app | grep -i mb | grep -o -P "(?<='./).*(?='>)" | tail -1))
-if [ $version = $version0 ]; then
-  echo "Update not needed!"
-else
-  notify-send "A new version of $APP is available, please wait"
-  mkdir /opt/$APP/tmp
-  cd /opt/$APP/tmp
-  wget $version
-  if ls . | grep -i app; then
+SITE="https://www.avidemux.org"
+version0=$(cat "/opt/$APP/version")
+version="https://www.avidemux.org/nightly/appImage4/$(curl -Ls https://www.avidemux.org/nightly/appImage4/ | grep .app | grep -i mb | grep -o -P "(?<='./).*(?='>)" | tail -1)"
+[ -n "$version" ] || { echo "Error getting link"; exit 1; }
+if [ "$version" != "$version0" ] || [ -e /opt/"$APP"/*.zsync ]; then
+	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
+	wget "$version" || exit 1
 	cd ..
-  	if test -f ./tmp/*.app; then rm ./version
-  	fi
-  	echo $version >> ./version
-  	mv --backup=t ./tmp/*.app ./$APP
-  	chmod a+x /opt/$APP/$APP
-  	rm -R -f ./tmp ./*~
-  fi
-  notify-send "$APP is updated!"
+	mv --backup=t ./tmp/* ./"$APP"
+	chmod a+x ./"$APP" || exit 1
+	echo "$version" > ./version
+	rm -R -f ./*zs-old ./*.part ./tmp ./*~
+	notify-send "$APP is updated!"
+else
+	echo "Update not needed!"
 fi
 EOF
-chmod a+x /opt/$APP/AM-updater
+chmod a+x ./AM-updater || exit 1
 
 # LAUNCHER & ICON
+wget "https://raw.githubusercontent.com/mean00/avidemux2/master/avidemux_icon.png" -O ./icons/"$APP"
 echo "[Desktop Entry]
 Name=Avidemux
 GenericName=Video Editor
@@ -72,32 +59,4 @@ Icon=/opt/$APP/icons/$APP
 Terminal=false
 Type=Application
 Categories=AudioVideo;AudioVideoEditing;Video;
-MimeType=video/mpeg;video/x-mpeg;video/mp4;video/x-m4v;video/quicktime;video/3gp;video/mkv;video/x-matroska;video/webm;video/flv;video/x-flv;video/dv;video/x-msvideo;video/x-ms-wmv;video/x-ms-asf;video/x-anim;" >> /usr/share/applications/AM-$APP.desktop
-
-mkdir icons
-wget https://raw.githubusercontent.com/mean00/avidemux2/master/avidemux_icon.png -O /opt/$APP/icons/$APP
-
-# ROLLBACK SCRIPT
-cat >> /opt/$APP/$APP-rollback << 'EOF'
-#!/usr/bin/env bash
-
-APP=avidemux-nightly
-rm -f ./rollback-args ./AM-rollback
-printf "%s\n" $(curl -Ls https://www.avidemux.org/nightly/appImage4/ | grep .app | grep -i mb | grep -o -P "(?<='./).*(?='>)" ) >> "./rollback-args" &&
-echo -e "-----------------------------------------------------------------------\nYou have chosen to roll back $APP.\nRollback will be done from https://www.avidemux.org\n-----------------------------------------------------------------------"
-printf "Select a version from this menu (read carefully) or press CTRL+C to abort:\n-----------------------------------------------------------------------\n"; sleep 1;
-select d in $(cat "./rollback-args"); do test -n "$d" && break; echo ">>> Invalid Selection"; done
-wget -q --show-progress https://www.avidemux.org/nightly/appImage4/$d
-chmod a+x ./$d
-mv ./$d ./$APP
-rm -f ./version
-echo $d >> ./version
-rm -f ./rollback-args
-echo -e "\nROLLBACK SUCCESSFUL!"
-exit
-EOF
-chmod a+x /opt/$APP/$APP-rollback
-
-
-
-
+MimeType=video/mpeg;video/x-mpeg;video/mp4;video/x-m4v;video/quicktime;video/3gp;video/mkv;video/x-matroska;video/webm;video/flv;video/x-flv;video/dv;video/x-msvideo;video/x-ms-wmv;video/x-ms-asf;video/x-anim;" > /usr/local/share/applications/"$APP"-AM.desktop
