Update 26 portable apps

diff --git a/programs/x86_64/brave-beta b/programs/x86_64/brave-beta
--- a/programs/x86_64/brave-beta
+++ b/programs/x86_64/brave-beta
@@ -1,57 +1,56 @@
 #!/bin/sh
 
+# AM INSTALL SCRIPT VERSION 3. 
+set -u
 APP=brave-beta
+SITE="brave/brave-browser"
 
-# CREATING THE FOLDER
-mkdir /opt/$APP
-cd /opt/$APP;
+# CREATE DIRECTORIES AND ADD REMOVER
+[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
+printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
+printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
+chmod a+x ../remove || exit 1
 
-# ADD THE REMOVER
-echo '#!/bin/sh' >> /opt/$APP/remove
-echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
-chmod a+x /opt/$APP/remove
-
-mkdir tmp;
-cd tmp;
-
-# DOWNLOADING THE DEPENDENCIES
-version=$(curl -Ls https://api.github.com/repos/brave/brave-browser/releases?per_page=100 | grep browser_download_url | grep linux-amd64.zip | cut -d '"' -f 4 | grep -v sha | grep nightly | head -1)
-wget $version
-unzip -qq ./*.zip
-rm -f ./*.zip
+# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
+version=$(curl -Ls https://api.github.com/repos/brave/brave-browser/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -vi "i386|i686|aarch64|arm64|armv7l" | grep -i "beta.*linux-amd64.zip" | head -1)
+wget "$version" || exit 1
+[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
+[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
+[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
 cd ..
-echo $version >> ./version
-mv ./tmp/* ./
-rm -R -f ./tmp
+if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
+rm -R -f ./tmp || exit 1
+echo "$version" > ./version
 
-# LINK
-ln -s /opt/$APP/brave /usr/local/bin/$APP
+# LINK TO PATH
+ln -s "/opt/$APP/brave" "/usr/local/bin/$APP"
 
 # SCRIPT TO UPDATE THE PROGRAM
-cat >> /opt/$APP/AM-updater << 'EOF'
-#!/usr/bin/env bash
+cat >> ./AM-updater << 'EOF'
+#!/bin/sh
+set -u
 APP=brave-beta
-
-version0=$(cat /opt/$APP/version)
-version=$(curl -Ls https://api.github.com/repos/brave/brave-browser/releases?per_page=100 | grep browser_download_url | grep linux-amd64.zip | cut -d '"' -f 4 | grep -v sha | grep nightly | head -1)
-if [[ "$version0" == "$version" ]]; then
-  echo "Update not needed, exit!"
- else
-  notify-send "A new version of $APP is available, please wait!"
-  mkdir /opt/$APP/tmp
-  cd /opt/$APP/tmp
-  wget $version
-  unzip -qq ./*.zip
-  rm -R -f ./*.zip
-  cd ..
-  rm -R -f ./version
-  mv --backup=t ./tmp/* ./
-  echo $version >> ./version
-  rm -R -f ./tmp ./*~
-  notify-send "$APP is updated!"
+SITE="brave/brave-browser"
+version0=$(cat "/opt/$APP/version")
+version=$(curl -Ls https://api.github.com/repos/brave/brave-browser/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -vi "i386|i686|aarch64|arm64|armv7l" | grep -i "beta.*linux-amd64.zip" | head -1)
+[ -n "$version" ] || { echo "Error getting link"; exit 1; }
+if [ "$version" != "$version0" ]; then
+	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
+	notify-send "A new version of $APP is available, please wait"
+	wget "$version" || exit 1
+	[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
+	[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
+	[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
+	cd ..
+	if [ -d ./tmp/* 2>/dev/null ]; then mv --backup=t ./tmp/*/* ./; else mv --backup=t ./tmp/* ./"$APP" 2>/dev/null || mv --backup=t ./tmp/* ./; fi
+	echo "$version" > ./version
+	rm -R -f ./tmp ./*~
+	notify-send "$APP is updated!"
+else
+	echo "Update not needed!"
 fi
 EOF
-chmod a+x /opt/$APP/AM-updater
+chmod a+x ./AM-updater || exit 1
 
 # LAUNCHER
 echo "[Desktop Entry]
@@ -272,6 +271,4 @@ Name[uk]=Нове вікно в режимі анонімного перегля
 Name[vi]=Cửa sổ ẩn danh mới
 Name[zh_CN]=新建隐身窗口
 Name[zh_TW]=新增無痕式視窗
-Exec=$APP --incognito" >> /usr/share/applications/AM-$APP.desktop
-
-
+Exec=$APP --incognito" > /usr/local/share/applications/"$APP"-AM.desktop
diff --git a/programs/x86_64/chrolog b/programs/x86_64/chrolog
--- a/programs/x86_64/chrolog
+++ b/programs/x86_64/chrolog
@@ -1,65 +1,65 @@
 #!/bin/sh
 
+# AM INSTALL SCRIPT VERSION 3. 
+set -u
 APP=chrolog
-REPO="Lukylix/Chrolog"
+SITE="Lukylix/Chrolog"
 
-# CREATE THE FOLDER
-mkdir /opt/$APP
-cd /opt/$APP
+# CREATE DIRECTORIES AND ADD REMOVER
+[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
+printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
+printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
+chmod a+x ../remove || exit 1
 
-# ADD THE REMOVER
-echo '#!/bin/sh' >> /opt/$APP/remove
-echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
-chmod a+x /opt/$APP/remove
-
-# DOWNLOAD THE ARCHIVE
-mkdir tmp
-cd ./tmp
-
-version=$(curl -Ls https://api.github.com/repos/$REPO/releases | grep -w -v i386 | grep -w -v i686 | grep -w -v aarch64 | grep -w -v arm64 | grep -w -v armv7l | grep browser_download_url | grep -i linux.zip | cut -d '"' -f 4 | head -1)
-wget $version
-unzip -qq ./*.zip
-echo "$version" >> /opt/$APP/version
+# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
+version=$(curl -Ls https://api.github.com/repos/Lukylix/Chrolog/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -vi "i386|i686|aarch64|arm64|armv7l" | grep -i "linux.zip" | head -1)
+wget "$version" || exit 1
+[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
+[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
+[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
 cd ..
-mv ./tmp/*/* ./
-chmod a+x /opt/$APP/$APP
-rm -R -f ./tmp
+if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
+rm -R -f ./tmp || exit 1
+echo "$version" > ./version
+chmod a+x ./$APP || exit 1
 
-# LINK
-ln -s /opt/$APP/$APP /usr/local/bin/$APP
+# LINK TO PATH
+ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"
 
 # SCRIPT TO UPDATE THE PROGRAM
-cat >> /opt/$APP/AM-updater << 'EOF'
-#!/usr/bin/env bash
+cat >> ./AM-updater << 'EOF'
+#!/bin/sh
+set -u
 APP=chrolog
-REPO="Lukylix/Chrolog"
-version0=$(cat /opt/$APP/version)
-version=$(curl -Ls https://api.github.com/repos/$REPO/releases | grep -w -v i386 | grep -w -v i686 | grep -w -v aarch64 | grep -w -v arm64 | grep -w -v armv7l | grep browser_download_url | grep -i linux.zip | cut -d '"' -f 4 | head -1)
-if [ $version = $version0 ]; then
-  echo "Update not needed!"
-else
-  notify-send "A new version of $APP is available, please wait"
-  mkdir /opt/$APP/tmp
-  cd /opt/$APP/tmp
-  wget $version
-  unzip -qq ./*.zip
-  if ls . | grep mage; then
+SITE="Lukylix/Chrolog"
+version0=$(cat "/opt/$APP/version")
+version=$(curl -Ls https://api.github.com/repos/Lukylix/Chrolog/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -vi "i386|i686|aarch64|arm64|armv7l" | grep -i "linux.zip" | head -1)
+[ -n "$version" ] || { echo "Error getting link"; exit 1; }
+if [ "$version" != "$version0" ]; then
+	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
+	notify-send "A new version of $APP is available, please wait"
+	wget "$version" || exit 1
+	[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
+	[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
+	[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
 	cd ..
-  	if test -f ./tmp/*zip; then rm ./version
-  	fi
-  	echo $version >> ./version
-  	mv --backup=t ./tmp/*/* ./
-  	chmod a+x /opt/$APP/$APP
-  	rm -R -f ./tmp ./*~
-  fi
-  notify-send "$APP is updated!"
+	if [ -d ./tmp/* 2>/dev/null ]; then mv --backup=t ./tmp/*/* ./; else mv --backup=t ./tmp/* ./"$APP" 2>/dev/null || mv --backup=t ./tmp/* ./; fi
+	chmod a+x ./"$APP" || exit 1
+	echo "$version" > ./version
+	rm -R -f ./tmp ./*~
+	notify-send "$APP is updated!"
+else
+	echo "Update not needed!"
 fi
 EOF
-chmod a+x /opt/$APP/AM-updater
+chmod a+x ./AM-updater || exit 1
 
-# LAUNCHER & ICON
-cat >> /usr/share/applications/AM-$APP.desktop << 'EOF'
-[Desktop Entry]
+# ICON
+mkdir -p icons
+mv ./resources/resources/*.svg ./icons/"$APP" 2> /dev/null
+
+# LAUNCHER
+echo "[Desktop Entry]
 Version=1.0
 Type=Application
 Name=Chrolog
@@ -68,12 +68,4 @@ Exec=chrolog
 Icon=/opt/chrolog/icons/chrolog
 Categories=Utility;
 Terminal=true
-StartupNotify=true
-EOF
-
-mkdir icons
-mv ./resources/resources/*.svg ./icons/$APP
-
-
-
-
+StartupNotify=true" > /usr/local/share/applications/"$APP"-AM.desktop
diff --git a/programs/x86_64/cosmonium b/programs/x86_64/cosmonium
--- a/programs/x86_64/cosmonium
+++ b/programs/x86_64/cosmonium
@@ -1,63 +1,64 @@
 #!/bin/sh
 
+# AM INSTALL SCRIPT VERSION 3. 
+set -u
 APP=cosmonium
-REPO="cosmonium/cosmonium"
+SITE="cosmonium/cosmonium"
 
-# CREATE THE FOLDER
-mkdir /opt/$APP
-cd /opt/$APP
+# CREATE DIRECTORIES AND ADD REMOVER
+[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
+printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
+printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
+chmod a+x ../remove || exit 1
 
-# ADD THE REMOVER
-echo '#!/bin/sh' >> /opt/$APP/remove
-echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
-chmod a+x /opt/$APP/remove
-
-# DOWNLOAD THE ARCHIVE
-mkdir tmp
-cd ./tmp
-
-version=$(curl -Ls https://api.github.com/repos/$REPO/releases | grep -w -v i386 | grep -w -v i686 | grep -w -v aarch64 | grep -w -v arm64 | grep -w -v armv7l | grep browser_download_url | grep -i linux  | grep -i "x86_64.tar.gz" | cut -d '"' -f 4 | head -1)
-wget $version
-echo "$version" >> /opt/$APP/version
+# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
+version=$(curl -Ls https://api.github.com/repos/cosmonium/cosmonium/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -vi "i386|i686|aarch64|arm64|armv7l" | grep -i "linux.*x86_64.tar.gz" | head -1)
+wget "$version" || exit 1
+[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
+[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
+[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
 cd ..
-tar fx tmp/*tar.gz -C ./tmp/; mv tmp/*/* .
-rm -R -f ./tmp
+if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
+rm -R -f ./tmp || exit 1
+echo "$version" > ./version
+chmod a+x ./$APP || exit 1
 
-# LINK
-echo '#!/bin/sh
-APP='$APP'
-cd /opt/$APP
-./$APP $@' >> /usr/local/bin/$APP
-chmod a+x /usr/local/bin/$APP
+# LINK TO PATH
+ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"
 
 # SCRIPT TO UPDATE THE PROGRAM
-cat >> /opt/$APP/AM-updater << 'EOF'
-#!/usr/bin/env bash
+cat >> ./AM-updater << 'EOF'
+#!/bin/sh
+set -u
 APP=cosmonium
-REPO="cosmonium/cosmonium"
-version0=$(cat /opt/$APP/version)
-version=$(curl -Ls https://api.github.com/repos/$REPO/releases | grep -w -v i386 | grep -w -v i686 | grep -w -v aarch64 | grep -w -v arm64 | grep -w -v armv7l | grep browser_download_url | grep -i linux  | grep -i "x86_64.tar.gz" | cut -d '"' -f 4 | head -1)
-if [ $version = $version0 ]; then
-  echo "Update not needed!"
+SITE="cosmonium/cosmonium"
+version0=$(cat "/opt/$APP/version")
+version=$(curl -Ls https://api.github.com/repos/cosmonium/cosmonium/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -vi "i386|i686|aarch64|arm64|armv7l" | grep -i "linux.*x86_64.tar.gz" | head -1)
+[ -n "$version" ] || { echo "Error getting link"; exit 1; }
+if [ "$version" != "$version0" ]; then
+	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
+	notify-send "A new version of $APP is available, please wait"
+	wget "$version" || exit 1
+	[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
+	[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
+	[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
+	cd ..
+	if [ -d ./tmp/* 2>/dev/null ]; then mv --backup=t ./tmp/*/* ./; else mv --backup=t ./tmp/* ./"$APP" 2>/dev/null || mv --backup=t ./tmp/* ./; fi
+	chmod a+x ./"$APP" || exit 1
+	echo "$version" > ./version
+	rm -R -f ./tmp ./*~
+	notify-send "$APP is updated!"
 else
-  notify-send "A new version of $APP is available, please wait"
-  mkdir /opt/$APP/tmp
-  cd /opt/$APP/tmp
-  wget $version
-  cd ..
-  tar fx tmp/*tar.gz -C ./tmp/; mv --backup=t tmp/*/* .
-  rm ./version
-  echo $version >> ./version
-  rm -R -f ./tmp ./*~
-  notify-send "$APP is updated!"
+	echo "Update not needed!"
 fi
 EOF
-chmod a+x /opt/$APP/AM-updater
+chmod a+x ./AM-updater || exit 1
 
-# LAUNCHER & ICON
-mkdir icons
-wget https://raw.githubusercontent.com/cosmonium/cosmonium/develop/textures/cosmonium-128.png -O ./icons/$APP 2>/dev/null
+# ICON
+mkdir -p icons
+wget https://raw.githubusercontent.com/cosmonium/cosmonium/develop/textures/cosmonium-128.png -O ./icons/"$APP" 2> /dev/null
 
+# LAUNCHER
 echo "[Desktop Entry]
 Version=1.0
 Type=Application
@@ -67,8 +68,4 @@ Terminal=false
 Name=Cosmonium
 GenericName=Space Simulator
 Comment=3D astronomy and space exploration program
-Categories=Astronomy;Education;Science;" >> /usr/share/applications/AM-$APP.desktop
-
-
-
-
+Categories=Astronomy;Education;Science;" > /usr/local/share/applications/"$APP"-AM.desktop
diff --git a/programs/x86_64/telegram b/programs/x86_64/telegram
--- a/programs/x86_64/telegram
+++ b/programs/x86_64/telegram
@@ -1,30 +1,62 @@
 #!/bin/sh
 
+# AM INSTALL SCRIPT VERSION 3. 
+set -u
 APP=telegram
-REPO="telegramdesktop/tdesktop"
+SITE="telegramdesktop/tdesktop"
 
-# CREATE THE FOLDER
-mkdir /opt/$APP
-cd /opt/$APP
+# CREATE DIRECTORIES AND ADD REMOVER
+[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
+printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
+printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
+chmod a+x ../remove || exit 1
 
-# ADD THE REMOVER
-echo '#!/bin/sh' >> /opt/$APP/remove
-echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
-chmod a+x /opt/$APP/remove
-
-# DOWNLOAD THE ARCHIVE
-mkdir tmp
-cd ./tmp
-
-version=$(curl -Ls https://api.github.com/repos/$REPO/releases | grep -w -v i386 | grep -w -v i686 | grep -w -v aarch64 | grep -w -v arm64 | grep -w -v armv7l | grep browser_download_url | grep -i "tar.xz" | cut -d '"' -f 4 | head -1)
-wget $version
-echo "$version" >> /opt/$APP/version
+# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
+version=$(curl -Ls https://api.github.com/repos/telegramdesktop/tdesktop/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -vi "i386|i686|aarch64|arm64|armv7l" | grep -i "tar.xz" | head -1)
+wget "$version" || exit 1
+[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
+[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
+[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
 cd ..
-tar xf ./tmp/*tar.xz -C ./tmp/ && mv ./tmp/*/* .
-rm -R -f ./tmp
+if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
+rm -R -f ./tmp || exit 1
+echo "$version" > ./version
+chmod a+x ./Telegram || exit 1
 
-# LINK
-ln -s /opt/$APP/Telegram /usr/local/bin/$APP
+# LINK TO PATH
+ln -s "/opt/$APP/Telegram" "/usr/local/bin/$APP"
+
+# SCRIPT TO UPDATE THE PROGRAM
+cat >> ./AM-updater << 'EOF'
+#!/bin/sh
+set -u
+APP=telegram
+SITE="telegramdesktop/tdesktop"
+version0=$(cat "/opt/$APP/version")
+version=$(curl -Ls https://api.github.com/repos/telegramdesktop/tdesktop/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -vi "i386|i686|aarch64|arm64|armv7l" | grep -i "tar.xz" | head -1)
+[ -n "$version" ] || { echo "Error getting link"; exit 1; }
+if [ "$version" != "$version0" ]; then
+	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
+	notify-send "A new version of $APP is available, please wait"
+	wget "$version" || exit 1
+	[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
+	[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
+	[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
+	cd ..
+	if [ -d ./tmp/* 2>/dev/null ]; then mv --backup=t ./tmp/*/* ./; else mv --backup=t ./tmp/* ./"$APP" 2>/dev/null || mv --backup=t ./tmp/* ./; fi
+	chmod a+x ./Telegram || exit 1
+	echo "$version" > ./version
+	rm -R -f ./tmp ./*~
+	notify-send "$APP is updated!"
+else
+	echo "Update not needed!"
+fi
+EOF
+chmod a+x ./AM-updater || exit 1
+
+# ICON
+mkdir -p icons
+wget https://web.telegram.org/k/assets/img/apple-touch-icon.png -O ./icons/"$APP" 2> /dev/null
 
 # LAUNCHER
 echo "[Desktop Entry]
@@ -40,12 +72,4 @@ Type=Application
 Categories=Chat;Network;InstantMessaging;Qt;
 MimeType=x-scheme-handler/tg;
 Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
-X-GNOME-UsesNotifications=true" >> /usr/share/applications/AM-$APP.desktop
-
-# ICON
-mkdir icons
-wget https://web.telegram.org/k/assets/img/apple-touch-icon.png -O ./icons/$APP  2> /dev/null
-
-
-
-
+X-GNOME-UsesNotifications=true" > /usr/local/share/applications/"$APP"-AM.desktop
