Unify braves

diff --git a/programs/x86_64/brave-nightly b/programs/x86_64/brave-nightly
--- a/programs/x86_64/brave-nightly
+++ b/programs/x86_64/brave-nightly
@@ -1,9 +1,10 @@
 #!/bin/sh
 
-# AM INSTALL SCRIPT VERSION 3. 
+# AM INSTALL SCRIPT VERSION 3.5
 set -u
 APP=brave-nightly
-SITE="brave/brave-browser"
+SITE1=$(curl -Ls https://api.github.com/repos/brave/brave-browser/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*nightly.*linux-amd64.zip$" | head -1)
+SITE2=$(curl -Ls https://api.github.com/repos/srevinsaju/Brave-AppImage/releases?per_page=100 | sed 's/[()",{} ]/\n/g' | grep -oi "https.*nightly.*appimage$" | head -1)
 
 # CREATE DIRECTORIES AND ADD REMOVER
 [ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
@@ -11,264 +12,103 @@ printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../r
 printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
 chmod a+x ../remove || exit 1
 
-# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
-version=$(curl -Ls https://api.github.com/repos/brave/brave-browser/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -vi "i386|i686|aarch64|arm64|armv7l" | grep -i "nightly.*linux-amd64.zip" | head -1)
-wget "$version" || exit 1
-[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
-[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
-[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
-cd ..
-if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
-rm -R -f ./tmp || exit 1
-echo "$version" > ./version
+# CHOOSE A VERSION
+read -r -p "
+ Choose which version of Brave to use:
+ 
+ 1. Brave Nightly
+	Official portable build of Brave, nightly version
+	Source: https://github.com/brave/brave-browser
 
-# LINK TO PATH
-ln -s "/opt/$APP/brave" "/usr/local/bin/$APP"
+ 2. Brave Nightly AppImage
+	Unofficial AppImage made by turning the portable build into an AppImage
+	It can be sandboxed with 'am --sandbox brave' or 'appman --sandbox brave'
+	Source: https://github.com/srevinsaju/Brave-AppImage
+
+ Which version you choose (type a number and press ENTER)?: " RESPONSE
+case "$RESPONSE" in
+	1)
+	UPDATER=1
+	version="$SITE1"
+	wget "$version" || exit 1;;
+
+	2)
+	UPDATER=2
+	version="$SITE2"
+	wget "$version" || exit 1;;
+
+	*) ../remove && echo "Not a valid number, aborting" && exit 1;;
+esac
+
+# PREPARE THE APP, $version is also used for updates
+if [ -e ./*zip ]; then
+	unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
+	chmod a+x ./brave || exit 1
+	ln -s "/opt/$APP/brave" "/usr/local/bin/$APP" # LINK TO PATH
+else
+	mv ./*mage ./"$APP"
+	chmod a+x ./"$APP" || exit 1
+	ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP" # LINK TO PATH
+fi
+cd ..
+mv ./tmp/* ./ && rm -R -f ./tmp || exit 1
+echo "$version" > ./version
 
 # SCRIPT TO UPDATE THE PROGRAM
 cat >> ./AM-updater << 'EOF'
 #!/bin/sh
 set -u
 APP=brave-nightly
-SITE="brave/brave-browser"
+#SITE1=$(curl -Ls https://api.github.com/repos/brave/brave-browser/releases| sed 's/[()",{} ]/\n/g' | grep -oi "https.*nightly.*linux-amd64.zip$" | head -1)
+#SITE2=$(curl -Ls https://api.github.com/repos/srevinsaju/Brave-AppImage/releases?per_page=100 | sed 's/[()",{} ]/\n/g' | grep -oi "https.*nightly.*appimage$" | head -1)
 version0=$(cat "/opt/$APP/version")
-version=$(curl -Ls https://api.github.com/repos/brave/brave-browser/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -vi "i386|i686|aarch64|arm64|armv7l" | grep -i "nightly.*linux-amd64.zip" | head -1)
+version="REPLACETHIS"
 [ -n "$version" ] || { echo "Error getting link"; exit 1; }
 if [ "$version" != "$version0" ]; then
 	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
 	notify-send "A new version of $APP is available, please wait"
 	wget "$version" || exit 1
-	[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
-	[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
-	[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
+	if [ -e ./*zip ]; then
+		unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
+		chmod a+x ./brave || exit 1
+	else
+		mv ./*mage ./"$APP"
+		chmod a+x ./"$APP" || exit 1
+	fi
 	cd ..
-	if [ -d ./tmp/* 2>/dev/null ]; then mv --backup=t ./tmp/*/* ./; else mv --backup=t ./tmp/* ./"$APP" 2>/dev/null || mv --backup=t ./tmp/* ./; fi
+	mv --backup=t ./tmp/* ./ && rm -R -f ./tmp ./*~ || exit 1
 	echo "$version" > ./version
-	rm -R -f ./tmp ./*~
 	notify-send "$APP is updated!"
 else
 	echo "Update not needed!"
 fi
 EOF
+[ "$UPDATER" = 1 ] && { sed -i 's|REPLACETHIS|$SITE1|g; s|#SITE1|SITE1|g' ./AM-updater || exit 1; }
+[ "$UPDATER" = 2 ] && { sed -i 's|REPLACETHIS|$SITE2|g; s|#SITE2|SITE2|g' ./AM-updater || exit 1; }
 chmod a+x ./AM-updater || exit 1
 
-# LAUNCHER
-echo "[Desktop Entry]
-Version=1.0
-Name=Brave Web Browser (Nightly)
-# Only KDE 4 seems to use GenericName, so we reuse the KDE strings.
-# From Ubuntu's language-pack-kde-XX-base packages, version 9.04-20090413.
-GenericName=Web Browser
-GenericName[ar]=متصفح الشبكة
-GenericName[bg]=Уеб браузър
-GenericName[ca]=Navegador web
-GenericName[cs]=WWW prohlížeč
-GenericName[da]=Browser
-GenericName[de]=Web-Browser
-GenericName[el]=Περιηγητής ιστού
-GenericName[en_GB]=Web Browser
-GenericName[es]=Navegador web
-GenericName[et]=Veebibrauser
-GenericName[fi]=WWW-selain
-GenericName[fr]=Navigateur Web
-GenericName[gu]=વેબ બ્રાઉઝર
-GenericName[he]=דפדפן אינטרנט
-GenericName[hi]=वेब ब्राउज़र
-GenericName[hu]=Webböngésző
-GenericName[it]=Browser Web
-GenericName[ja]=ウェブブラウザ
-GenericName[kn]=ಜಾಲ ವೀಕ್ಷಕ
-GenericName[ko]=웹 브라우저
-GenericName[lt]=Žiniatinklio naršyklė
-GenericName[lv]=Tīmekļa pārlūks
-GenericName[ml]=വെബ് ബ്രൌസര്‍
-GenericName[mr]=वेब ब्राऊजर
-GenericName[nb]=Nettleser
-GenericName[nl]=Webbrowser
-GenericName[pl]=Przeglądarka WWW
-GenericName[pt]=Navegador Web
-GenericName[pt_BR]=Navegador da Internet
-GenericName[ro]=Navigator de Internet
-GenericName[ru]=Веб-браузер
-GenericName[sl]=Spletni brskalnik
-GenericName[sv]=Webbläsare
-GenericName[ta]=இணைய உலாவி
-GenericName[th]=เว็บเบราว์เซอร์
-GenericName[tr]=Web Tarayıcı
-GenericName[uk]=Навігатор Тенет
-GenericName[zh_CN]=网页浏览器
-GenericName[zh_HK]=網頁瀏覽器
-GenericName[zh_TW]=網頁瀏覽器
-# Not translated in KDE, from Epiphany 2.26.1-0ubuntu1.
-GenericName[bn]=ওয়েব ব্রাউজার
-GenericName[fil]=Web Browser
-GenericName[hr]=Web preglednik
-GenericName[id]=Browser Web
-GenericName[or]=ଓ୍ବେବ ବ୍ରାଉଜର
-GenericName[sk]=WWW prehliadač
-GenericName[sr]=Интернет прегледник
-GenericName[te]=మహాతల అన్వేషి
-GenericName[vi]=Bộ duyệt Web
-# Gnome and KDE 3 uses Comment.
-Comment=Access the Internet
-Comment[ar]=الدخول إلى الإنترنت
-Comment[bg]=Достъп до интернет
-Comment[bn]=ইন্টারনেটটি অ্যাক্সেস করুন
-Comment[ca]=Accedeix a Internet
-Comment[cs]=Přístup k internetu
-Comment[da]=Få adgang til internettet
-Comment[de]=Internetzugriff
-Comment[el]=Πρόσβαση στο Διαδίκτυο
-Comment[en_GB]=Access the Internet
-Comment[es]=Accede a Internet.
-Comment[et]=Pääs Internetti
-Comment[fi]=Käytä internetiä
-Comment[fil]=I-access ang Internet
-Comment[fr]=Accéder à Internet
-Comment[gu]=ઇંટરનેટ ઍક્સેસ કરો
-Comment[he]=גישה אל האינטרנט
-Comment[hi]=इंटरनेट तक पहुंच स्थापित करें
-Comment[hr]=Pristup Internetu
-Comment[hu]=Internetelérés
-Comment[id]=Akses Internet
-Comment[it]=Accesso a Internet
-Comment[ja]=インターネットにアクセス
-Comment[kn]=ಇಂಟರ್ನೆಟ್ ಅನ್ನು ಪ್ರವೇಶಿಸಿ
-Comment[ko]=인터넷 연결
-Comment[lt]=Interneto prieiga
-Comment[lv]=Piekļūt internetam
-Comment[ml]=ഇന്റര്‍‌നെറ്റ് ആക്‌സസ് ചെയ്യുക
-Comment[mr]=इंटरनेटमध्ये प्रवेश करा
-Comment[nb]=Gå til Internett
-Comment[nl]=Verbinding maken met internet
-Comment[or]=ଇଣ୍ଟର୍ନେଟ୍ ପ୍ରବେଶ କରନ୍ତୁ
-Comment[pl]=Skorzystaj z internetu
-Comment[pt]=Aceder à Internet
-Comment[pt_BR]=Acessar a internet
-Comment[ro]=Accesaţi Internetul
-Comment[ru]=Доступ в Интернет
-Comment[sk]=Prístup do siete Internet
-Comment[sl]=Dostop do interneta
-Comment[sr]=Приступите Интернету
-Comment[sv]=Gå ut på Internet
-Comment[ta]=இணையத்தை அணுகுதல்
-Comment[te]=ఇంటర్నెట్‌ను ఆక్సెస్ చెయ్యండి
-Comment[th]=เข้าถึงอินเทอร์เน็ต
-Comment[tr]=İnternet'e erişin
-Comment[uk]=Доступ до Інтернету
-Comment[vi]=Truy cập Internet
-Comment[zh_CN]=访问互联网
-Comment[zh_HK]=連線到網際網路
-Comment[zh_TW]=連線到網際網路
-Exec=$APP %U
-StartupNotify=true
-Terminal=false
-Icon=/opt/$APP/product_logo_128_nightly.png
-Type=Application
-Categories=Network;WebBrowser;
-MimeType=application/pdf;application/rdf+xml;application/rss+xml;application/xhtml+xml;application/xhtml_xml;application/xml;image/gif;image/jpeg;image/png;image/webp;text/html;text/xml;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ipfs;x-scheme-handler/ipns;
-Actions=new-window;new-private-window;
-[Desktop Action new-window]
-Name=New Window
-Name[am]=አዲስ መስኮት
-Name[ar]=نافذة جديدة
-Name[bg]=Нов прозорец
-Name[bn]=নতুন উইন্ডো
-Name[ca]=Finestra nova
-Name[cs]=Nové okno
-Name[da]=Nyt vindue
-Name[de]=Neues Fenster
-Name[el]=Νέο Παράθυρο
-Name[en_GB]=New Window
-Name[es]=Nueva ventana
-Name[et]=Uus aken
-Name[fa]=پنجره جدید
-Name[fi]=Uusi ikkuna
-Name[fil]=New Window
-Name[fr]=Nouvelle fenêtre
-Name[gu]=નવી વિંડો
-Name[hi]=नई विंडो
-Name[hr]=Novi prozor
-Name[hu]=Új ablak
-Name[id]=Jendela Baru
-Name[it]=Nuova finestra
-Name[iw]=חלון חדש
-Name[ja]=新規ウインドウ
-Name[kn]=ಹೊಸ ವಿಂಡೊ
-Name[ko]=새 창
-Name[lt]=Naujas langas
-Name[lv]=Jauns logs
-Name[ml]=പുതിയ വിന്‍ഡോ
-Name[mr]=नवीन विंडो
-Name[nl]=Nieuw venster
-Name[no]=Nytt vindu
-Name[pl]=Nowe okno
-Name[pt]=Nova janela
-Name[pt_BR]=Nova janela
-Name[ro]=Fereastră nouă
-Name[ru]=Новое окно
-Name[sk]=Nové okno
-Name[sl]=Novo okno
-Name[sr]=Нови прозор
-Name[sv]=Nytt fönster
-Name[sw]=Dirisha Jipya
-Name[ta]=புதிய சாளரம்
-Name[te]=క్రొత్త విండో
-Name[th]=หน้าต่างใหม่
-Name[tr]=Yeni Pencere
-Name[uk]=Нове вікно
-Name[vi]=Cửa sổ Mới
-Name[zh_CN]=新建窗口
-Name[zh_TW]=開新視窗
-Exec=$APP
-[Desktop Action new-private-window]
-Name=New Incognito Window
-Name[ar]=نافذة جديدة للتصفح المتخفي
-Name[bg]=Нов прозорец „инкогнито“
-Name[bn]=নতুন ছদ্মবেশী উইন্ডো
-Name[ca]=Finestra d'incògnit nova
-Name[cs]=Nové anonymní okno
-Name[da]=Nyt inkognitovindue
-Name[de]=Neues Inkognito-Fenster
-Name[el]=Νέο παράθυρο για ανώνυμη περιήγηση
-Name[en_GB]=New Incognito window
-Name[es]=Nueva ventana de incógnito
-Name[et]=Uus inkognito aken
-Name[fa]=پنجره جدید حالت ناشناس
-Name[fi]=Uusi incognito-ikkuna
-Name[fil]=Bagong Incognito window
-Name[fr]=Nouvelle fenêtre de navigation privée
-Name[gu]=નવી છુપી વિંડો
-Name[hi]=नई गुप्त विंडो
-Name[hr]=Novi anoniman prozor
-Name[hu]=Új Inkognitóablak
-Name[id]=Jendela Penyamaran baru
-Name[it]=Nuova finestra di navigazione in incognito
-Name[iw]=חלון חדש לגלישה בסתר
-Name[ja]=新しいシークレット ウィンドウ
-Name[kn]=ಹೊಸ ಅಜ್ಞಾತ ವಿಂಡೋ
-Name[ko]=새 시크릿 창
-Name[lt]=Naujas inkognito langas
-Name[lv]=Jauns inkognito režīma logs
-Name[ml]=പുതിയ വേഷ പ്രച്ഛന്ന വിന്‍ഡോ
-Name[mr]=नवीन गुप्त विंडो
-Name[nl]=Nieuw incognitovenster
-Name[no]=Nytt inkognitovindu
-Name[pl]=Nowe okno incognito
-Name[pt]=Nova janela de navegação anónima
-Name[pt_BR]=Nova janela anônima
-Name[ro]=Fereastră nouă incognito
-Name[ru]=Новое окно в режиме инкогнито
-Name[sk]=Nové okno inkognito
-Name[sl]=Novo okno brez beleženja zgodovine
-Name[sr]=Нови прозор за прегледање без архивирања
-Name[sv]=Nytt inkognitofönster
-Name[ta]=புதிய மறைநிலைச் சாளரம்
-Name[te]=క్రొత్త అజ్ఞాత విండో
-Name[th]=หน้าต่างใหม่ที่ไม่ระบุตัวตน
-Name[tr]=Yeni Gizli pencere
-Name[uk]=Нове вікно в режимі анонімного перегляду
-Name[vi]=Cửa sổ ẩn danh mới
-Name[zh_CN]=新建隐身窗口
-Name[zh_TW]=新增無痕式視窗
-Exec=$APP --incognito" > /usr/local/share/applications/"$APP"-AM.desktop
+# LAUNCHER & ICON
+if [ "$UPDATER" = "1" ]; then
+	DESKTOP="https://raw.githubusercontent.com/srevinsaju/Brave-AppImage/master/AppDir-Nightly/brave-browser-nightly.desktop"
+	wget "$DESKTOP" -O ./"$APP".desktop 2>/dev/null || exit 1
+	mv ./product*logo*128*.png ./DirIcon
+else
+	./"$APP" --appimage-extract *.desktop 1>/dev/null && mv ./squashfs-root/*.desktop ./"$APP".desktop
+	./"$APP" --appimage-extract .DirIcon 1>/dev/null && mv ./squashfs-root/.DirIcon ./DirIcon
+	COUNT=0
+	while [ "$COUNT" -lt 10 ]; do # Tries to get the actual icon/desktop if it is a symlink to another symlink
+		if [ -L ./"$APP".desktop ]; then
+			LINKPATH=$(readlink ./"$APP".desktop)
+			./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./"$APP".desktop
+		fi
+		if [ -L ./DirIcon ]; then
+			LINKPATH=$(readlink ./DirIcon)
+			./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./DirIcon
+		fi
+		[ ! -L ./"$APP".desktop ] && [ ! -L ./DirIcon ] && break
+		COUNT=$((COUNT + 1))
+	done
+	rm -R -f ./squashfs-root
+fi
+sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g" ./"$APP".desktop
+mv ./"$APP".desktop /usr/local/share/applications/"$APP"-AM.desktop && mv ./DirIcon ./icons/"$APP" 1>/dev/null
