Add files via upload

diff --git a/programs/x86_64/bridge b/programs/x86_64/bridge
--- a/programs/x86_64/bridge
+++ b/programs/x86_64/bridge
@@ -1,86 +1,74 @@
 #!/bin/sh
 
+# AM INSTALL SCRIPT VERSION 3.5
+set -u
 APP=bridge
 SITE="https://quixel.com"
 
-# CREATE THE FOLDER
-mkdir /opt/$APP
-cd /opt/$APP
+# CREATE DIRECTORIES AND ADD REMOVER
+[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
+printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
+printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
+chmod a+x ../remove || exit 1
 
-# ADD THE REMOVER
-echo '#!/bin/sh' >> /opt/$APP/remove
-echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
-chmod a+x /opt/$APP/remove
-
-# DOWNLOAD THE ARCHIVE
-mkdir tmp
-cd ./tmp
-
-version=$(echo "https://d2shgxa8i058x8.cloudfront.net/bridge/linux/Bridge.AppImage")
-wget $version
-echo "$version" >> /opt/$APP/version
+# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
+version=$(wget -q https://repology.org/project/bridge/versions -O - | grep -i "new.*version" | head -1 | tr '><' '\n' | grep "^[0-9]")
+wget "https://d2shgxa8i058x8.cloudfront.net/bridge/linux/Bridge.AppImage" || exit 1
+#wget "$version.zsync" 2> /dev/null # Comment out this line if you want to use zsync
+# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
 cd ..
-mv ./tmp/*mage ./$APP
-chmod a+x /opt/$APP/$APP
-rmdir ./tmp
+mv ./tmp/*mage ./"$APP"
+mv ./tmp/*.zsync ./"$APP".zsync 2>/dev/null
+rm -R -f ./tmp || exit 1
+echo "$version" > ./version
+chmod a+x ./"$APP" || exit 1
 
-# LINK
-ln -s /opt/$APP/$APP /usr/local/bin/$APP
+# LINK TO PATH
+ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"
+
+# SCRIPT TO UPDATE THE PROGRAM
+cat >> ./AM-updater << 'EOF'
+#!/bin/sh
+set -u
+APP=bridge
+SITE="https://quixel.com"
+version0=$(cat "/opt/$APP/version")
+version=$(wget -q https://repology.org/project/bridge/versions -O - | grep -i "new.*version" | head -1 | tr '><' '\n' | grep "^[0-9]")
+[ -n "$version" ] || { echo "Error getting link"; exit 1; }
+if [ "$version" != "$version0" ] || [ -e /opt/"$APP"/*.zsync ]; then
+	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
+	[ -e ../*.zsync ] || notify-send "A new version of $APP is available, please wait"
+	[ -e ../*.zsync ] && wget "$version.zsync" 2>/dev/null || { wget "https://d2shgxa8i058x8.cloudfront.net/bridge/linux/Bridge.AppImage" || exit 1; }
+	# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
+	cd ..
+	mv ./tmp/*.zsync ./"$APP".zsync 2>/dev/null || mv --backup=t ./tmp/*mage ./"$APP"
+	[ -e ./*.zsync ] && { zsync ./"$APP".zsync || notify-send -u critical "zsync failed to update $APP"; }
+	chmod a+x ./"$APP" || exit 1
+	echo "$version" > ./version
+	rm -R -f ./*zs-old ./*.part ./tmp ./*~
+	notify-send "$APP is updated!"
+else
+	echo "Update not needed!"
+fi
+EOF
+chmod a+x ./AM-updater || exit 1
 
 # LAUNCHER & ICON
-app=$(echo $APP | cut -c -3)
-cd /opt/$APP
-./$APP --appimage-extract *.desktop 1>/dev/null
-./$APP --appimage-extract share/applications/*.desktop 1>/dev/null
-./$APP --appimage-extract usr/share/applications/*.desktop 1>/dev/null
-mv squashfs-root/*.desktop ./$APP.desktop 2> /dev/null
-mv squashfs-root/share/applications/*.desktop ./$APP.desktop 2> /dev/null
-mv squashfs-root/usr/share/applications/*.desktop ./$APP.desktop 2> /dev/null
-if [ ! -e ./$APP.desktop ]; then 
-	rm ./$APP.desktop; ./$APP --appimage-extract usr/share/applications/*$app*.desktop 
-	mv squashfs-root/usr/share/applications/*.desktop ./$APP.desktop 2> /dev/null
-fi
-if [ ! -e ./$APP.desktop ]; then 
-	rm ./$APP.desktop; ./$APP --appimage-extract share/applications/*$app*.desktop 1>/dev/null
-	mv squashfs-root/share/applications/*.desktop ./$APP.desktop 2> /dev/null
-fi
-CHANGEEXEC=$(cat ./$APP.desktop | grep Exec= | tr ' ' '\n' | tr '=' '\n' | tr '/' '\n' | grep $app | head -1)
-sed -i "s#$CHANGEEXEC#$APP#g" ./$APP.desktop 2> /dev/null
-sed -i "s#AppRun#$APP#g" ./$APP.desktop 2> /dev/null
-sed -i "s#Exec=/bin/#Exec=#g" ./$APP.desktop 2> /dev/null
-sed -i "s#Exec=/usr/bin/#Exec=#g" ./$APP.desktop 2> /dev/null
-CHANGEICON=$(cat ./$APP.desktop | grep Icon= | head -1)
-sed -i "s#$CHANGEICON#Icon=/opt/$APP/icons/$APP#g" ./$APP.desktop 2> /dev/null
-
-mkdir icons
-./$APP --appimage-extract *.png 2>&1 | grep -v "squashfs-root"; mv ./squashfs-root/*$app* ./icons/$APP 2>/dev/null
-./$APP --appimage-extract *.svg 2>&1 | grep -v "squashfs-root"; mv ./squashfs-root/*$app* ./icons/$APP 2>/dev/null
-./$APP --appimage-extract share/icons/*/*/* 1>/dev/null
-./$APP --appimage-extract usr/share/icons/*/*/* 1>/dev/null
-./$APP --appimage-extract share/icons/*/*/*/* 1>/dev/null
-./$APP --appimage-extract usr/share/icons/*/*/*/* 1>/dev/null
-mv ./squashfs-root/share/icons/hicolor/22x22/apps/*$app* ./icons/$APP 2>/dev/null
-mv ./squashfs-root/share/icons/hicolor/24x24/apps/*$app* ./icons/$APP 2>/dev/null
-mv ./squashfs-root/share/icons/hicolor/32x32/apps/*$app* ./icons/$APP 2>/dev/null
-mv ./squashfs-root/share/icons/hicolor/48x48/apps/*$app* ./icons/$APP 2>/dev/null
-mv ./squashfs-root/share/icons/hicolor/64x64/apps/*$app* ./icons/$APP 2>/dev/null
-mv ./squashfs-root/share/icons/hicolor/128x128/apps/*$app* ./icons/$APP 2>/dev/null
-mv ./squashfs-root/share/icons/hicolor/256x256/apps/*$app* ./icons/$APP 2>/dev/null
-mv ./squashfs-root/share/icons/hicolor/512x512/apps/*$app* ./icons/$APP 2>/dev/null
-mv ./squashfs-root/share/icons/hicolor/scalable/apps/*$app* ./icons/$APP 2>/dev/null
-mv ./squashfs-root/usr/share/icons/hicolor/22x22/apps/*$app* ./icons/$APP 2>/dev/null
-mv ./squashfs-root/usr/share/icons/hicolor/24x24/apps/*$app* ./icons/$APP 2>/dev/null
-mv ./squashfs-root/usr/share/icons/hicolor/32x32/apps/*$app* ./icons/$APP 2>/dev/null
-mv ./squashfs-root/usr/share/icons/hicolor/48x48/apps/*$app* ./icons/$APP 2>/dev/null
-mv ./squashfs-root/usr/share/icons/hicolor/64x64/apps/*$app* ./icons/$APP 2>/dev/null
-mv ./squashfs-root/usr/share/icons/hicolor/128x128/apps/*$app* ./icons/$APP 2>/dev/null
-mv ./squashfs-root/usr/share/icons/hicolor/256x256/apps/*$app* ./icons/$APP 2>/dev/null
-mv ./squashfs-root/usr/share/icons/hicolor/512x512/apps/*$app* ./icons/$APP 2>/dev/null
-mv ./squashfs-root/usr/share/icons/hicolor/scalable/apps/*$app* ./icons/$APP 2>/dev/null
-
-rm -R -f /opt/$APP/squashfs-root
-mv ./$APP.desktop /usr/share/applications/AM-$APP.desktop 2> /dev/null
-
-
-
-
+./"$APP" --appimage-extract *.desktop 1>/dev/null && mv ./squashfs-root/*.desktop ./"$APP".desktop
+./"$APP" --appimage-extract .DirIcon 1>/dev/null && mv ./squashfs-root/.DirIcon ./DirIcon
+COUNT=0
+while [ "$COUNT" -lt 10 ]; do # Tries to get the actual icon/desktop if it is a symlink to another symlink
+	if [ -L ./"$APP".desktop ]; then
+		LINKPATH="$(readlink ./"$APP".desktop | sed 's|^\./||' 2>/dev/null)"
+		./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./"$APP".desktop
+	fi
+	if [ -L ./DirIcon ]; then
+		LINKPATH="$(readlink ./DirIcon | sed 's|^\./||' 2>/dev/null)"
+		./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./DirIcon
+	fi
+	[ ! -L ./"$APP".desktop ] && [ ! -L ./DirIcon ] && break
+	COUNT=$((COUNT + 1))
+done
+sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g" ./"$APP".desktop
+mv ./"$APP".desktop /usr/local/share/applications/"$APP"-AM.desktop && mv ./DirIcon ./icons/"$APP" 1>/dev/null
+rm -R -f ./squashfs-root
diff --git a/programs/x86_64/code b/programs/x86_64/code
--- a/programs/x86_64/code
+++ b/programs/x86_64/code
@@ -1,74 +1,79 @@
 #!/bin/sh
 
+# AM INSTALL SCRIPT VERSION 3.5
+set -u
 APP=code
-SITE="https://code.visualstudio.com/"
+SITE="https://code.visualstudio.com"
 
-# CREATE THE FOLDER
-mkdir /opt/$APP
-cd /opt/$APP
+# CREATE DIRECTORIES AND ADD REMOVER
+[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
+printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
+printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
+chmod a+x ../remove || exit 1
 
-# ADD THE REMOVER
-echo '#!/bin/sh' >> /opt/$APP/remove
-echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
-chmod a+x /opt/$APP/remove
-
-# DOWNLOAD THE ARCHIVE
-mkdir tmp
-cd ./tmp
-
-version=$(echo $(curl -Ls https://aur.archlinux.org/packages/visual-studio-code-bin | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep -i "x64" | grep -w -v aarch64 | grep -w -v arm64 | grep -w -v armv7l | grep -w -v ".asc" | grep -w -v "archlinux.org" | head -1))
-wget $version
-echo "$version" >> /opt/$APP/version
+# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
+version=$(curl -Ls https://api.github.com/repos/microsoft/vscode/releases/latest | sed 's/[()",{} ]/\n/g' | grep -i "tag" | head -1)
+wget "https://code.visualstudio.com/sha/download?build=stable&os=linux-x64" --trust-server-names || exit 1
+[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
+[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
+[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
 cd ..
-tar fx ./tmp/stable -C ./tmp/ && mv ./tmp/VS*/* . && cp ./resources/app/resources/linux/code.png . && wget https://aur.archlinux.org/cgit/aur.git/plain/code.desktop?h=visual-studio-code-bin -O AM-$APP.desktop 2> /dev/null
-rm -R -f ./tmp
+if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
+rm -R -f ./tmp || exit 1
+echo "$version" > ./version
+chmod a+x ./$APP || exit 1
 
-# LINK
-ln -s /opt/$APP/$APP /usr/local/bin/$APP
+# LINK TO PATH
+ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"
 
 # SCRIPT TO UPDATE THE PROGRAM
-cat >> /opt/$APP/AM-updater << 'EOF'
-#!/usr/bin/env bash
+cat >> ./AM-updater << 'EOF'
+#!/bin/sh
+set -u
 APP=code
-version0=$(cat /opt/$APP/version)
-version=$(echo $(curl -Ls https://aur.archlinux.org/packages/visual-studio-code-bin | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep -i "x64" | grep -w -v aarch64 | grep -w -v arm64 | grep -w -v armv7l | grep -w -v ".asc" | grep -w -v "archlinux.org" | head -1))
-if [ $version = $version0 ]; then
-  echo "Update not needed!"
+SITE="https://code.visualstudio.com"
+version0=$(cat "/opt/$APP/version")
+version=$(curl -Ls https://api.github.com/repos/microsoft/vscode/releases/latest | sed 's/[()",{} ]/\n/g' | grep -i "tag" | head -1)
+[ -n "$version" ] || { echo "Error getting link"; exit 1; }
+if [ "$version" != "$version0" ]; then
+	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
+	notify-send "A new version of $APP is available, please wait"
+	wget "https://code.visualstudio.com/sha/download?build=stable&os=linux-x64" --trust-server-names || exit 1
+	[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
+	[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
+	[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
+	cd ..
+	if [ -d ./tmp/* 2>/dev/null ]; then mv --backup=t ./tmp/*/* ./; else mv --backup=t ./tmp/* ./"$APP" 2>/dev/null || mv --backup=t ./tmp/* ./; fi
+	chmod a+x ./"$APP" || exit 1
+	echo "$version" > ./version
+	rm -R -f ./tmp ./*~
+	notify-send "$APP is updated!"
 else
-  notify-send "A new version of $APP is available, please wait"
-  mkdir /opt/$APP/tmp
-  cd /opt/$APP/tmp
-  wget $version
-  cd ..
-  tar fx ./tmp/stable -C ../tmp/ && mv ./tmp/VS*/* . && cp ./resources/app/resources/linux/code.png . && wget https://aur.archlinux.org/cgit/aur.git/plain/code.desktop?h=visual-studio-code-bin -O AM-$APP.desktop 2> /dev/null
-  rm ./version
-  echo $version >> ./version
-  rm -R -f ./tmp ./*~
-  notify-send "$APP is updated!"
+	echo "Update not needed!"
 fi
 EOF
-chmod a+x /opt/$APP/AM-updater
+chmod a+x ./AM-updater || exit 1
 
-# LAUNCHER & ICON
-app=$(echo $APP | cut -c -3)
-cd /opt/$APP
-mv ./*.desktop ./$APP.desktop 2>/dev/null
-CHANGEEXEC=$(cat ./$APP.desktop | grep Exec= | tr ' ' '\n' | tr '=' '\n' | tr '/' '\n' | grep $app | head -1)
-sed -i "s#$CHANGEEXEC#$APP#g" ./$APP.desktop 2> /dev/null
-sed -i "s#Exec=/bin/#Exec=#g" ./$APP.desktop 2> /dev/null
-sed -i "s#Exec=/usr/bin/#Exec=#g" ./$APP.desktop 2> /dev/null
-CHANGEICON=$(cat ./$APP.desktop | grep Icon= | head -1)
-sed -i "s#$CHANGEICON#Icon=/opt/$APP/icons/$APP#g" ./$APP.desktop 2> /dev/null
+# ICON
+mkdir -p icons
+cp ./resources/app/resources/linux/code.png -O ./icons/"$APP" 2> /dev/null
 
-mkdir icons
-mv ./*.svg ./icons/$APP 2>/dev/null
-mv ./*.png ./icons/$APP 2>/dev/null
-mv ./*$app*.png ./icons/$APP 2>/dev/null
-mv ./*128*.png ./icons/$APP 2>/dev/null
-mv ./*256*.png ./icons/$APP 2>/dev/null
+# LAUNCHER
+echo "[Desktop Entry]
+Name=Visual Studio Code
+Comment=Code Editing. Refined.
+GenericName=Text Editor
+Exec=$APP %F
+Icon=/opt/$APP/icons/$APP
+Type=Application
+StartupNotify=false
+StartupWMClass=Code
+Categories=TextEditor;Development;IDE;
+MimeType=text/plain;inode/directory;application/x-code-workspace;
+Actions=new-empty-window;
+Keywords=vscode;
 
-mv ./$APP.desktop /usr/share/applications/AM-$APP.desktop 2> /dev/null
-
-
-
-
+[Desktop Action new-empty-window]
+Name=New Empty Window
+Exec=$APP --new-window %F
+Icon=/opt/$APP/icons/$APP" > /usr/local/share/applications/"$APP"-AM.desktop
diff --git a/programs/x86_64/conty-wine b/programs/x86_64/conty-wine
--- a/programs/x86_64/conty-wine
+++ b/programs/x86_64/conty-wine
@@ -1,51 +1,56 @@
 #!/bin/sh
 
+# AM INSTALL SCRIPT VERSION 3.5
+set -u
 APP=conty-wine
-REPO="Kron4ek/Conty"
-version=$(curl -Ls https://api.github.com/repos/$REPO/releases | grep -w -v zsync | grep browser_download_url | grep -i "conty_wine.sh" | cut -d '"' -f 4 | head -1)
+SITE="Kron4ek/Conty"
 
-# CREATE THE FOLDER
-mkdir /opt/$APP
-cd /opt/$APP
+# CREATE DIRECTORIES AND ADD REMOVER
+[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
+printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
+printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
+chmod a+x ../remove || exit 1
 
-# ADD THE REMOVER
-echo '#!/bin/sh' >> /opt/$APP/remove
-echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
-chmod a+x /opt/$APP/remove
-
-# DOWNLOAD THE APPIMAGE
-mkdir tmp
-wget $version -O $APP
-cd tmp
-wget $version.zsync 2> /dev/null
+# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
+version=$(curl -Ls https://api.github.com/repos/Kron4ek/Conty/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*sh" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | grep -i "wine" | head -1)
+wget "$version" || exit 1
+wget "$version.zsync" 2> /dev/null # Comment out this line if you want to use zsync
+# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
 cd ..
-chmod a+x /opt/$APP/$APP
-mv ./tmp/*.zsync ./$APP.zsync 2> /dev/null
-rmdir ./tmp
-echo $version >> ./version
+mv ./tmp/*sh ./"$APP"
+mv ./tmp/*.zsync ./"$APP".zsync 2>/dev/null
+rm -R -f ./tmp || exit 1
+echo "$version" > ./version
+chmod a+x ./"$APP" || exit 1
 
-# LINK
-ln -s /opt/$APP/$APP /usr/local/bin/$APP
+# LINK TO PATH
+ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"
 
 # SCRIPT TO UPDATE THE PROGRAM
-cat >> /opt/$APP/AM-updater << 'EOF'
+cat >> ./AM-updater << 'EOF'
 #!/bin/sh
+set -u
 APP=conty-wine
-REPO="Kron4ek/Conty"
-version=$(curl -Ls https://api.github.com/repos/$REPO/releases | grep -w -v zsync | grep browser_download_url | grep -i "conty_wine.sh" | cut -d '"' -f 4 | head -1)
-cd /opt/$APP
-mkdir tmp
-cd ./tmp
-wget $version.zsync 2> /dev/null
-cd ..
-mv ./tmp/*.zsync ./$APP.zsync
-rmdir ./tmp
-zsync /opt/$APP/$APP.zsync
-rm -R -f /opt/$APP/*zs-old /opt/$APP/*.part
-chmod a+x /opt/$APP/$APP
+SITE="Kron4ek/Conty"
+version0=$(cat "/opt/$APP/version")
+version=$(curl -Ls https://api.github.com/repos/Kron4ek/Conty/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*sh" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | grep -i "wine" | head -1)
+[ -n "$version" ] || { echo "Error getting link"; exit 1; }
+if [ "$version" != "$version0" ] || [ -e /opt/"$APP"/*.zsync ]; then
+	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
+	[ -e ../*.zsync ] || notify-send "A new version of $APP is available, please wait"
+	[ -e ../*.zsync ] && wget "$version.zsync" 2>/dev/null || { wget "$version" || exit 1; }
+	# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
+	cd ..
+	mv ./tmp/*.zsync ./"$APP".zsync 2>/dev/null || mv --backup=t ./tmp/*sh ./"$APP"
+	[ -e ./*.zsync ] && { zsync ./"$APP".zsync || notify-send -u critical "zsync failed to update $APP"; }
+	chmod a+x ./"$APP" || exit 1
+	echo "$version" > ./version
+	rm -R -f ./*zs-old ./*.part ./tmp ./*~
+	notify-send "$APP is updated!"
+else
+	echo "Update not needed!"
+fi
 EOF
-chmod a+x /opt/$APP/AM-updater
-
-
+chmod a+x ./AM-updater || exit 1
 
 
