Update conty (mutiple choices script) (#2409)
* Delete programs/x86_64/conty-lite

* Delete programs/x86_64/conty-wine

* Update conty

* Update x86_64-apps

* Update x86_64-portable

diff --git a/programs/x86_64/conty b/programs/x86_64/conty
--- a/programs/x86_64/conty
+++ b/programs/x86_64/conty
@@ -12,15 +12,44 @@ printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../r
 chmod a+x ../remove || exit 1
 
 # DOWNLOAD AND PREPARE THE APP, $version is also used for updates
-version=$(curl -Ls https://api.github.com/repos/Kron4ek/Conty/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*sh" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | grep -v "lite\|wine" | head -1)
-wget "$version" || exit 1
-wget "$version.zsync" 2> /dev/null # Comment out this line if you want to use zsync
-# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
+read -r -p "
+ Choose which version of Conty to use:
+
+ 1. WINE (or BASE), it includes only WINE and its dependencies
+
+ 2. LITE, same as WINE, plus Wine-GE, Steam, Lutris, PlayOnLinux,
+    GameHub, Minigalaxy, Legendary, Bottles, MultiMC, MangoHud,
+    Gamescope, RetroArch, PPSSPP, PCSX2, DuckStation, OBS Studio
+    and OpenJDK
+
+ 3. FULL, same as LITE, plus base-devel, gcc, mingw-w64-gcc, meson,
+    cmake, jre-openjdk, multimc5, Firefox and qBittorrent
+
+ Learn more at https://github.com/Kron4ek/Conty
+
+ Which version you choose (type a number and press ENTER)?" response
+RELEASE=""
+if echo "$response" | grep -q "^1"; then
+	RELEASE="conty_wine"
+elif echo "$response" | grep -q "^2"; then
+	RELEASE="conty_lite"
+elif echo "$response" | grep -q "^3"; then
+	RELEASE="conty"
+fi
+[ -z "$RELEASE" ] && exit 0
+
+version=$(curl -Ls https://api.github.com/repos/Kron4ek/Conty/releases | sed 's/[()",{} ]/\n/g' | grep -io "https.*download.*$RELEASE.sh$" | head -1)
+if [ -z "$version" ]; then
+	printf "\n 💀 ERROR: it seems that upstream removed %b, please retry\n" "$RELEASE" && exit 1
+else
+	wget "$version" || exit 1
+fi
 cd ..
 mv ./tmp/*sh ./"$APP"
 mv ./tmp/*.zsync ./"$APP".zsync 2>/dev/null
 rm -R -f ./tmp || exit 1
 echo "$version" > ./version
+wget "$version.zsync" 2> /dev/null
 chmod a+x ./"$APP" || exit 1
 
 # LINK TO PATH
@@ -33,7 +62,7 @@ set -u
 APP=conty
 SITE="Kron4ek/Conty"
 version0=$(cat "/opt/$APP/version")
-version=$(curl -Ls https://api.github.com/repos/Kron4ek/Conty/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*sh" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | grep -v "lite\|wine" | head -1)
+version=$(curl -Ls https://api.github.com/repos/Kron4ek/Conty/releases | sed 's/[()",{} ]/\n/g' | grep -io "https.*download.*REPLACETHIS.sh$" | head -1)
 [ -n "$version" ] || { echo "Error getting link"; exit 1; }
 if [ "$version" != "$version0" ] || [ -e /opt/"$APP"/*.zsync ]; then
 	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
@@ -52,5 +81,4 @@ else
 fi
 EOF
 chmod a+x ./AM-updater || exit 1
-
-
+sed -i "s#REPLACETHIS#$RELEASE#g" /opt/"$APP"/AM-updater
