Add files via upload

diff --git a/programs/x86_64/fastcompmgr b/programs/x86_64/fastcompmgr
--- a/programs/x86_64/fastcompmgr
+++ b/programs/x86_64/fastcompmgr
@@ -1,52 +1,48 @@
 #!/bin/sh
 
+# AM INSTALL SCRIPT VERSION 3. 
+set -u
 APP=fastcompmgr
 SITE="tycho-kirchner/fastcompmgr"
 
-# CREATE DIRECTORIES
-if [ -z "$APP" ]; then exit 1; fi
-mkdir -p "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
-
-# ADD THE REMOVER
-echo "#!/bin/sh
-rm -f /usr/local/bin/$APP
-rm -R -f /opt/$APP" > "/opt/$APP/remove"
+# CREATE DIRECTORIES AND ADD REMOVER
+[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
+echo "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > "/opt/$APP/remove"
 chmod a+x "/opt/$APP/remove"
 
-# DOWNLOAD AND PREPARE THE APP
-# $version is also used for updates
-
+# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
 version=$(curl -Ls https://api.github.com/repos/"$SITE"/releases | jq '.' | sed 's/[()",{}]/ /g; s/ /\n/g' | grep -o 'https.*fastcompmgr$' | head -1)
-wget "$version"
-echo "$version" > "/opt/$APP/version"
+wget "$version" || exit 1
 cd ..
-mv --backup=t ./tmp/* ./"$APP"
-rm -R -f ./tmp
-chmod a+x "/opt/$APP/$APP"
+mv ./tmp/"$APP" ./
+rm -R -f ./tmp || exit 1
+echo "$version" > ./version
+chmod a+x "/opt/$APP/$APP" || exit 1
 
-# LINK
+# LINK TO PATH
 ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"
 
 # SCRIPT TO UPDATE THE PROGRAM
 cat >> "/opt/$APP/AM-updater" << 'EOF'
 #!/bin/sh
+set -u
 APP=fastcompmgr
 SITE="tycho-kirchner/fastcompmgr"
-version0=$(cat /opt/$APP/version)
+version0=$(cat "/opt/$APP/version")
 version=$(curl -Ls https://api.github.com/repos/"$SITE"/releases | jq '.' | sed 's/[()",{}]/ /g; s/ /\n/g' | grep -o 'https.*fastcompmgr$' | head -1)
-if [ "$version" = "$version0" ]; then
-	echo "Update not needed!" && exit 0
-else
+[ -n "$version" ] || { echo "Error getting link"; exit 1; }
+if [ "$version" != "$version0" ]; then
+	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
 	notify-send "A new version of $APP is available, please wait"
-	mkdir "/opt/$APP/tmp"
-	cd "/opt/$APP/tmp" || exit 1
-	wget "$version"
+	wget "$version" || exit 1
 	cd ..
-	mv --backup=t ./tmp/* ./"$APP"
+	mv --backup=t ./tmp/"$APP" ./
+	chmod a+x "/opt/$APP/$APP" || exit 1
 	echo "$version" > ./version
 	rm -R -f ./tmp ./*~
-	chmod a+x "/opt/$APP/$APP"
 	notify-send "$APP is updated!"
+	exit 0
 fi
+echo "Update not needed!"
 EOF
 chmod a+x "/opt/$APP/AM-updater"
