Move gtk3 AppImages back from "am-extras" to "AM" (#2408)
* Move gtk3 AppImages back from "am-extras" to "AM"

Multiple choice scripts with first SITE reference or SITE1 for "latest" (if exists) and SITE2 for https://github.com/ivan-hc/GNOME3-appimages as a fallback, if the first is empty

* Update x86_64-apps

* Update gedit

* Update galculator

diff --git a/programs/x86_64/gedit b/programs/x86_64/gedit
--- a/programs/x86_64/gedit
+++ b/programs/x86_64/gedit
@@ -3,7 +3,7 @@
 # AM INSTALL SCRIPT VERSION 3.5
 set -u
 APP=gedit
-SITE="ivan-hc/Gedit-appimage"
+SITE1="ivan-hc/Gedit-appimage" SITE2="ivan-hc/GNOME3-appimages"
 
 # CREATE DIRECTORIES AND ADD REMOVER
 [ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
@@ -12,10 +12,32 @@ printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
 chmod a+x ../remove || exit 1
 
 # DOWNLOAD AND PREPARE THE APP, $version is also used for updates
-version=$(curl -Ls https://api.github.com/repos/ivan-hc/Gedit-appimage/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | head -1)
-wget "$version" || exit 1
-# Keep this space in sync with other installation scripts
-# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
+[ -n "$SITE1" ] && read -r -p "
+ Choose which version of $APP AppImage to use:
+
+ 1. Latest build.
+
+    Source: https://github.com/$SITE1
+
+ 2. Legacy, old GTK implementation.
+
+    Source: https://github.com/$SITE2
+
+ Which version you choose (type a number and press ENTER)?" response
+RELEASE=""
+if [ -n "$SITE1" ] && echo "$response" | grep -q "^1"; then
+	RELEASE="$SITE1"
+elif [ -z "$SITE1" ] || echo "$response" | grep -q "^2"; then
+	RELEASE="$SITE2"
+fi
+[ -z "$RELEASE" ] && exit 0
+
+version=$(curl -Ls https://api.github.com/repos/"$RELEASE"/releases | sed 's/[()",{} ]/\n/g' | grep -io 'https.*x86_64.*mage$' | grep -i "$APP" | head -1)
+if [ -z "$version" ]; then
+	printf "\n 💀 ERROR: it seems that upstream removed %b, please retry\n" "$RELEASE" && exit 1
+else
+	wget "$version" || exit 1
+fi
 cd ..
 mv ./tmp/*mage ./"$APP"
 # Keep this space in sync with other installation scripts
@@ -31,9 +53,9 @@ cat >> ./AM-updater << 'EOF'
 #!/bin/sh
 set -u
 APP=gedit
-SITE="ivan-hc/Gedit-appimage"
+SITE="REPLACETHIS"
 version0=$(cat "/opt/$APP/version")
-version=$(curl -Ls https://api.github.com/repos/ivan-hc/Gedit-appimage/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | head -1)
+version=$(curl -Ls https://api.github.com/repos/REPLACETHIS/releases | sed 's/[()",{} ]/\n/g' | grep -io 'https.*x86_64.*mage$' | grep -i "$APP" | head -1)
 [ -n "$version" ] || { echo "Error getting link"; exit 1; }
 if command -v appimageupdatetool >/dev/null 2>&1; then
 	cd "/opt/$APP" || exit 1
@@ -55,6 +77,7 @@ else
 fi
 EOF
 chmod a+x ./AM-updater || exit 1
+sed -i "s#REPLACETHIS#$RELEASE#g" /opt/"$APP"/AM-updater
 
 # LAUNCHER & ICON
 ./"$APP" --appimage-extract *.desktop 1>/dev/null && mv ./squashfs-root/*.desktop ./"$APP".desktop
@@ -72,6 +95,6 @@ while [ "$COUNT" -lt 10 ]; do # Tries to get the actual icon/desktop if it is a 
 	[ ! -L ./"$APP".desktop ] && [ ! -L ./DirIcon ] && break
 	COUNT=$((COUNT + 1))
 done
-sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g" ./"$APP".desktop
+sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g; s# --no-sandbox##g" ./"$APP".desktop
 mv ./"$APP".desktop /usr/local/share/applications/"$APP"-AM.desktop && mv ./DirIcon ./icons/"$APP" 1>/dev/null
 rm -R -f ./squashfs-root
