Made godot and uad-ng two multichoose scripts (#2376)
* Delete programs/x86_64/uad-ng-appimage

* Delete programs/x86_64/godot-appimage

* Made godot and uad-ng two multichoose scripts

Each will install both the official portable build and the AppImage

diff --git a/programs/x86_64/godot b/programs/x86_64/godot
--- a/programs/x86_64/godot
+++ b/programs/x86_64/godot
@@ -1,9 +1,9 @@
 #!/bin/sh
 
-# AM INSTALL SCRIPT VERSION 3. 
+# AM INSTALL SCRIPT VERSION 3.5
 set -u
 APP=godot
-SITE="godotengine/godot"
+SITE="godotengine/godot" SITE2="pkgforge-dev/Godot-AppImage"
 
 # CREATE DIRECTORIES AND ADD REMOVER
 [ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
@@ -11,71 +11,150 @@ printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../r
 printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
 chmod a+x ../remove || exit 1
 
-# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
-version=$(curl -Ls https://api.github.com/repos/godotengine/godot/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | grep -i "linux.x86_64.zip" | head -1)
-wget "$version" || exit 1
-[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
-[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
-[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
-cd ..
-if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
-rm -R -f ./tmp || exit 1
-echo "$version" > ./version
-chmod a+x ./$APP || exit 1
+# DOWNLOAD AND PREPARE THE APP
+read -r -p "
+ Choose a package format:
 
-# LINK TO PATH
-ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"
+ 1. Official portable package.
 
-# SCRIPT TO UPDATE THE PROGRAM
-cat >> ./AM-updater << 'EOF'
-#!/bin/sh
-set -u
-APP=godot
-SITE="godotengine/godot"
-version0=$(cat "/opt/$APP/version")
-version=$(curl -Ls https://api.github.com/repos/godotengine/godot/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | grep -i "linux.x86_64.zip" | head -1)
-[ -n "$version" ] || { echo "Error getting link"; exit 1; }
-if [ "$version" != "$version0" ]; then
-	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
-	notify-send "A new version of $APP is available, please wait"
+    Source: https://github.com/godotengine/godot
+
+ 2. Unofficial AppImage.
+
+    Source: https://github.com/pkgforge-dev/Godot-AppImage
+
+ Which version you choose (type a number and press ENTER)?" response
+RELEASE=""
+
+if echo "$response" | grep -q "^1"; then
+	RELEASE="PORTABLE"
+	version=$(curl -Ls https://api.github.com/repos/godotengine/godot/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | grep -i "linux.x86_64.zip" | head -1)
 	wget "$version" || exit 1
 	[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
 	[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
 	[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
 	cd ..
-	if [ -d ./tmp/* 2>/dev/null ]; then mv --backup=t ./tmp/*/* ./; else mv --backup=t ./tmp/* ./"$APP" 2>/dev/null || mv --backup=t ./tmp/* ./; fi
-	chmod a+x ./"$APP" || exit 1
-	echo "$version" > ./version
-	rm -R -f ./tmp ./*~
-	notify-send "$APP is updated!"
-else
-	echo "Update not needed!"
+	mv ./tmp/*/* ./ 2>/dev/null || mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./
+elif echo "$response" | grep -q "^2"; then
+	RELEASE="APPIMAGE"
+	version=$(curl -Ls https://api.github.com/repos/pkgforge-dev/Godot-AppImage/releases/latest | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | head -1)
+	wget "$version" || exit 1
+	cd ..
+	mv ./tmp/*mage ./"$APP"
 fi
-EOF
-chmod a+x ./AM-updater || exit 1
+[ -z "$RELEASE" ] && exit 0
+rm -R -f ./tmp || exit 1
+echo "$version" > ./version
+chmod a+x ./"$APP" || exit 1
 
-# ICON
-mkdir -p icons
-curl -s -Lo ./icons/"$APP" https://portable-linux-apps.github.io/icons/godot.png
+# LINK TO PATH
+ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"
 
-# LAUNCHER
-echo "[Desktop Entry]
-Name=Godot Engine
-GenericName=Libre game engine
-GenericName[el]=Ελεύθερη μηχανή παιχνιδιού
-GenericName[fr]=Moteur de jeu libre
-GenericName[nl]=Libre game-engine
-GenericName[zh_CN]=自由的游戏引擎
-Comment=Multi-platform 2D and 3D game engine with a feature-rich editor
-Comment[el]=2D και 3D μηχανή παιχνιδιού πολλαπλών πλατφορμών με επεξεργαστή πλούσιο σε χαρακτηριστικά
-Comment[fr]=Moteur de jeu 2D et 3D multiplateforme avec un éditeur riche en fonctionnalités
-Comment[nl]=Multi-platform 2D- en 3d-game-engine met een veelzijdige editor
-Comment[zh_CN]=多平台 2D 和 3D 游戏引擎，带有功能丰富的编辑器
-Exec=godot %f
-Icon=/opt/$APP/icons/$APP
-Terminal=false
-PrefersNonDefaultGPU=true
-Type=Application
-MimeType=application/x-godot-project;
-Categories=Development;IDE;
-StartupWMClass=Godot" > /usr/local/share/applications/"$APP"-AM.desktop
+if [ "$RELEASE" = APPIMAGE ]; then
+	# SCRIPT TO UPDATE THE PROGRAM
+	cat <<-'HEREDOC' >> ./AM-updater
+	#!/bin/sh
+	set -u
+	APP=godot
+	SITE="pkgforge-dev/Godot-AppImage"
+	version0=$(cat "/opt/$APP/version")
+	version=$(curl -Ls https://api.github.com/repos/pkgforge-dev/Godot-AppImage/releases/latest | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | head -1)
+	[ -n "$version" ] || { echo "Error getting link"; exit 1; }
+	if command -v appimageupdatetool >/dev/null 2>&1; then
+	   cd "/opt/$APP" || exit 1
+	   appimageupdatetool -Or ./"$APP" && chmod a+x ./"$APP" && echo "$version" > ./version && exit 0
+	fi
+	if [ "$version" != "$version0" ]; then
+	   mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
+	   notify-send "A new version of $APP is available, please wait"
+	   wget "$version" || exit 1
+	   # Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
+	   cd ..
+	   mv --backup=t ./tmp/*mage ./"$APP"
+	   chmod a+x ./"$APP" || exit 1
+	   echo "$version" > ./version
+	   rm -R -f ./*zs-old ./*.part ./tmp ./*~
+	   notify-send "$APP is updated!"
+	else
+	   echo "Update not needed!"
+	fi
+	HEREDOC
+	chmod a+x ./AM-updater || exit 1
+
+	# LAUNCHER & ICON
+	./"$APP" --appimage-extract *.desktop 1>/dev/null && mv ./squashfs-root/*.desktop ./"$APP".desktop
+	./"$APP" --appimage-extract .DirIcon 1>/dev/null && mv ./squashfs-root/.DirIcon ./DirIcon
+	COUNT=0
+	while [ "$COUNT" -lt 10 ]; do # Tries to get the actual icon/desktop if it is a symlink to another symlink
+		if [ -L ./"$APP".desktop ]; then
+			LINKPATH="$(readlink ./"$APP".desktop | sed 's|^\./||' 2>/dev/null)"
+			./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./"$APP".desktop
+		fi
+		if [ -L ./DirIcon ]; then
+			LINKPATH="$(readlink ./DirIcon | sed 's|^\./||' 2>/dev/null)"
+			./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./DirIcon
+		fi
+		[ ! -L ./"$APP".desktop ] && [ ! -L ./DirIcon ] && break
+		COUNT=$((COUNT + 1))
+	done
+	sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g; s# --no-sandbox##g" ./"$APP".desktop
+	mv ./"$APP".desktop /usr/local/share/applications/"$APP"-AM.desktop && mv ./DirIcon ./icons/"$APP" 1>/dev/null
+	rm -R -f ./squashfs-root
+else
+	# SCRIPT TO UPDATE THE PROGRAM
+	cat <<-'HEREDOC' >> ./AM-updater
+	#!/bin/sh
+	set -u
+	APP=godot
+	SITE="godotengine/godot"
+	version0=$(cat "/opt/$APP/version")
+	version=$(curl -Ls https://api.github.com/repos/godotengine/godot/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | grep -i "linux.x86_64.zip" | head -1)
+	[ -n "$version" ] || { echo "Error getting link"; exit 1; }
+	if [ "$version" != "$version0" ]; then
+	   mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
+	   notify-send "A new version of $APP is available, please wait"
+	   wget "$version" || exit 1
+	   [ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
+	   [ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
+	   [ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
+	   cd ..
+	   mv ./tmp/*/* ./ 2>/dev/null || mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./
+	   chmod a+x ./"$APP" || exit 1
+	   echo "$version" > ./version
+	   rm -R -f ./tmp ./*~
+	   notify-send "$APP is updated!"
+	else
+	   echo "Update not needed!"
+	fi
+	HEREDOC
+	chmod a+x ./AM-updater || exit 1
+
+	# ICON
+	mkdir -p icons
+	curl -s -Lo ./icons/"$APP" https://portable-linux-apps.github.io/icons/"$APP".png
+
+	# LAUNCHER
+	rm -f /usr/local/share/applications/"$APP"-AM.desktop
+	cat <<-HEREDOC >> /usr/local/share/applications/"$APP"-AM.desktop
+	[Desktop Entry]
+	Name=Godot Engine
+	GenericName=Libre game engine
+	GenericName[el]=Ελεύθερη μηχανή παιχνιδιού
+	GenericName[fr]=Moteur de jeu libre
+	GenericName[nl]=Libre game-engine
+	GenericName[zh_CN]=自由的游戏引擎
+	Comment=Multi-platform 2D and 3D game engine with a feature-rich editor
+	Comment[el]=2D και 3D μηχανή παιχνιδιού πολλαπλών πλατφορμών με επεξεργαστή πλούσιο σε χαρακτηριστικά
+	Comment[fr]=Moteur de jeu 2D et 3D multiplateforme avec un éditeur riche en fonctionnalités
+	Comment[nl]=Multi-platform 2D- en 3d-game-engine met een veelzijdige editor
+	Comment[zh_CN]=多平台 2D 和 3D 游戏引擎，带有功能丰富的编辑器
+	Exec=godot %f
+	Icon=/opt/$APP/icons/$APP
+	Terminal=false
+	PrefersNonDefaultGPU=true
+	Type=Application
+	MimeType=application/x-godot-project;
+	Categories=Development;IDE;
+	StartupWMClass=Godot
+	HEREDOC
+fi
