Add files via upload

diff --git a/programs/x86_64/i3lock-color b/programs/x86_64/i3lock-color
--- a/programs/x86_64/i3lock-color
+++ b/programs/x86_64/i3lock-color
@@ -1,29 +1,25 @@
 #!/bin/sh
 
+# AM INSTALL SCRIPT VERSION 3.5
+set -u
 APP=i3lock-color
 SITE="Raymo111/i3lock-color"
 
-# CREATE DIRECTORIES
-if [ -z "$APP" ]; then exit 1; fi
-mkdir -p "/opt/$APP/tmp" "/opt/$APP/pam" && cd "/opt/$APP/tmp" || exit 1
+# CREATE DIRECTORIES AND ADD REMOVER
+[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/pam" && cd "/opt/$APP/tmp" || exit 1
+printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/i3lock\nrm -R -f /opt/$APP" > ../remove
+#printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
+chmod a+x ../remove || exit 1
 
-# ADD THE REMOVER
-echo "#!/bin/sh
-rm -f /usr/local/bin/i3lock
-rm -R -f /opt/$APP" > "/opt/$APP/remove"
-chmod a+x "/opt/$APP/remove"
-
-# DOWNLOAD AND PREPARE THE APP
-# $version is also used for updates
-
-version=$(curl -Ls https://api.github.com/repos/"$SITE"/releases | sed 's/[()",{}]/ /g; s/ /\n/g' | grep -o 'https.*i3lock$' | head -1)
-wget "$version"
-echo "$version" > "/opt/$APP/version"
+# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
+version=$(curl -Ls https://api.github.com/repos/"$SITE"/releases | sed 's/[()",{} ]/\n/g' | grep -o 'https.*i3lock$' | head -1)
+wget "$version" || exit 1
 cd ..
-mv --backup=t ./tmp/i3lock ./
-rm -R -f ./tmp
-chmod a+x "/opt/$APP/i3lock"
-cat >> "/opt/$APP/pam/i3lock" << 'EOF'
+mv ./tmp/* ./ || exit 1
+rm -R -f ./tmp || exit 1
+echo "$version" > ./version
+chmod a+x ./i3lock || exit 1
+cat >> ./pam/i3lock << 'EOF'
 #
 # PAM configuration file for the i3lock-color screen locker. By default, it includes
 # the 'system-local-login' configuration file (see /etc/pam.d/system-local-login)
@@ -35,38 +31,40 @@ cat >> "/opt/$APP/pam/i3lock" << 'EOF'
 auth include login # For Debian
 EOF
 
-# LINK
-cat >> "/usr/local/bin/i3lock" << 'EOF'
+# LINK TO PATH
+cat >> /usr/local/bin/i3lock << 'EOF'
 #!/bin/sh
 APP=i3lock-color
-cat /etc/pam.d/i3lock >/dev/null 2>&1 && /opt/"$APP"/i3lock "$@" || (
+cat /etc/pam.d/i3lock >/dev/null 2>&1 && "/opt/$APP/i3lock" "$@" || (
 echo "You need to copy the i3lock pam file to /etc/pam.d for i3lock to work
 That is: cp /opt/$APP/pam/i3lock /etc/pam.d/i3lock
 MAKE SURE TO READ THE PAM FILE FIRST as it has to be configured for your distro.
 If you are still getting this error there might be something wrong with i3lock." \
 && notify-send -u critical "Error i3lock: launch from terminal to see instructions" )
 EOF
-chmod a+x "/usr/local/bin/i3lock"
+chmod a+x /usr/local/bin/i3lock
 
 # SCRIPT TO UPDATE THE PROGRAM
-cat >> "/opt/$APP/AM-updater" << 'EOF'
+cat >> ./AM-updater << 'EOF'
 #!/bin/sh
+set -u
 APP=i3lock-color
 SITE="Raymo111/i3lock-color"
-version0=$(cat /opt/$APP/version)
-version=$(curl -Ls https://api.github.com/repos/"$SITE"/releases | sed 's/[()",{}]/ /g; s/ /\n/g' | grep -o 'https.*i3lock$' | head -1)
-if [ "$version" = "$version0" ]; then
-	echo "Update not needed!" && exit 0
-else
-	notify-send "A new version of $APP is available, please wait"
+version0=$(cat "/opt/$APP/version")
+version=$(curl -Ls https://api.github.com/repos/"$SITE"/releases | sed 's/[()",{} ]/\n/g' | grep -o 'https.*i3lock$' | head -1)
+[ -n "$version" ] || { echo "Error getting link"; exit 1; }
+if [ "$version" != "$version0" ]; then
 	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
-	wget "$version"
+	notify-send "A new version of $APP is available, please wait"
+	wget "$version" || exit 1
 	cd ..
-	mv --backup=t ./tmp/i3lock ./
+	mv ./tmp/* ./ || exit 1
+	chmod a+x ./i3lock || exit 1
 	echo "$version" > ./version
 	rm -R -f ./tmp ./*~
-	chmod a+x "/opt/$APP/$APP"
 	notify-send "$APP is updated!"
+else
+	echo "Update not needed!"
 fi
 EOF
-chmod a+x "/opt/$APP/AM-updater"
+chmod a+x ./AM-updater || exit 1
