Update kdeutils

diff --git a/programs/x86_64/kwalletmanager5 b/programs/x86_64/kwalletmanager5
--- a/programs/x86_64/kwalletmanager5
+++ b/programs/x86_64/kwalletmanager5
@@ -1,88 +1,80 @@
 #!/bin/sh
 
+# AM INSTALL SCRIPT VERSION 3.5
+set -u
 APP=kdeutils
-REPO="ivan-hc/KDE-utils-appimage"
+SITE="ivan-hc/KDE-utils-appimage"
 
-# CREATE THE FOLDER
-mkdir /opt/$APP
-cd /opt/$APP
+# CREATE DIRECTORIES AND ADD REMOVER
+[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
+printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
+printf '\n%s' "rm -f /usr/local/share/applications/$APP-*-AM.desktop" >> ../remove
+chmod a+x ../remove || exit 1
 
-# ADD THE REMOVER
-echo '#!/bin/sh' >> /opt/$APP/remove
-echo "rm -R -f /usr/share/applications/AM-$APP*.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
-chmod a+x /opt/$APP/remove
-
-# DOWNLOAD THE ARCHIVE
-mkdir tmp
-cd ./tmp
-
-version=$(curl -Ls https://api.github.com/repos/$REPO/releases | grep -w -v i386 | grep -w -v i686 | grep -w -v aarch64 | grep -w -v arm64 | grep -w -v armv7l | grep browser_download_url | grep -i appimage | cut -d '"' -f 4 | head -1)
-wget $version
-echo "$version" >> /opt/$APP/version
+# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
+version=$(curl -Ls https://api.github.com/repos/ivan-hc/KDE-utils-appimage/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -vi "i386|i686|aarch64|arm64|armv7l" | head -1)
+wget "$version" || exit 1
+#wget "$version.zsync" 2> /dev/null # Comment out this line if you want to use zsync
+# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
 cd ..
-mv ./tmp/*mage ./$APP
-chmod a+x /opt/$APP/$APP
-rmdir ./tmp
+mv ./tmp/*mage ./"$APP"
+mv ./tmp/*.zsync ./"$APP".zsync 2>/dev/null
+rm -R -f ./tmp || exit 1
+echo "$version" > ./version
+chmod a+x ./"$APP" || exit 1
 
-# LINK
-ln -s /opt/$APP/$APP /usr/local/bin/$APP
+# LINK TO PATH
+ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"
 
 # SCRIPT TO UPDATE THE PROGRAM
-cat >> /opt/$APP/AM-updater << 'EOF'
-#!/usr/bin/env bash
+cat >> ./AM-updater << 'EOF'
+#!/bin/sh
+set -u
 APP=kdeutils
-REPO="ivan-hc/KDE-utils-appimage"
-version0=$(cat /opt/$APP/version)
-version=$(curl -Ls https://api.github.com/repos/$REPO/releases | grep -w -v i386 | grep -w -v i686 | grep -w -v aarch64 | grep -w -v arm64 | grep -w -v armv7l | grep browser_download_url | grep -i appimage | cut -d '"' -f 4 | head -1)
-if [ $version = $version0 ]; then
-  echo "Update not needed!"
-else
-  notify-send "A new version of $APP is available, please wait"
-  mkdir /opt/$APP/tmp
-  cd /opt/$APP/tmp
-  wget $version
-  if ls . | grep mage; then
+SITE="ivan-hc/KDE-utils-appimage"
+version0=$(cat "/opt/$APP/version")
+version=$(curl -Ls https://api.github.com/repos/ivan-hc/KDE-utils-appimage/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -vi "i386|i686|aarch64|arm64|armv7l" | head -1)
+[ -n "$version" ] || { echo "Error getting link"; exit 1; }
+if [ "$version" != "$version0" ] || [ -e /opt/"$APP"/*.zsync ]; then
+	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
+	[ -e ../*.zsync ] || notify-send "A new version of $APP is available, please wait"
+	[ -e ../*.zsync ] && wget "$version.zsync" 2>/dev/null || { wget "$version" || exit 1; }
+	# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
 	cd ..
-  	if test -f ./tmp/*mage; then rm ./version
-  	fi
-  	echo $version >> ./version
-  	mv --backup=t ./tmp/*mage ./$APP
-  	chmod a+x /opt/$APP/$APP
-  	rm -R -f ./tmp ./*~
-  fi
-  notify-send "$APP is updated!"
+	mv ./tmp/*.zsync ./"$APP".zsync 2>/dev/null || mv --backup=t ./tmp/*mage ./"$APP"
+	[ -e ./*.zsync ] && { zsync ./"$APP".zsync || notify-send -u critical "zsync failed to update $APP"; }
+	chmod a+x ./"$APP" || exit 1
+	echo "$version" > ./version
+	rm -R -f ./*zs-old ./*.part ./tmp ./*~
+	notify-send "$APP is updated!"
+else
+	echo "Update not needed!"
 fi
 EOF
-chmod a+x /opt/$APP/AM-updater
+chmod a+x ./AM-updater || exit 1
 
 # LAUNCHERS AND ICONS
-mkdir icons
 ./kdeutils --appimage-extract > /dev/null
-cp ./squashfs-root/usr/share/icons/hicolor/22x22/apps/* /opt/$APP/icons/ 2>/dev/null
-cp ./squashfs-root/usr/share/icons/hicolor/24x24/apps/* /opt/$APP/icons/ 2>/dev/null
-cp ./squashfs-root/usr/share/icons/hicolor/32x32/apps/* /opt/$APP/icons/ 2>/dev/null
-cp ./squashfs-root/usr/share/icons/hicolor/48x48/apps/* /opt/$APP/icons/ 2>/dev/null
-cp ./squashfs-root/usr/share/icons/hicolor/64x64/apps/* /opt/$APP/icons/ 2>/dev/null
-cp ./squashfs-root/usr/share/icons/hicolor/128x128/apps/* /opt/$APP/icons/ 2>/dev/null
-cp ./squashfs-root/usr/share/icons/hicolor/256x256/apps/* /opt/$APP/icons/ 2>/dev/null
-cp ./squashfs-root/usr/share/icons/hicolor/512x512/apps/* /opt/$APP/icons/ 2>/dev/null
-cp ./squashfs-root/usr/share/icons/hicolor/scalable/apps/* /opt/$APP/icons/ 2>/dev/null
-cd /opt/$APP/icons
-for file in *.png; do mv -- "$file" "${file%%.png}"; done
+cp ./squashfs-root/usr/share/icons/hicolor/22x22/apps/* /opt/"$APP"/icons/ 2>/dev/null
+cp ./squashfs-root/usr/share/icons/hicolor/24x24/apps/* /opt/"$APP"/icons/ 2>/dev/null
+cp ./squashfs-root/usr/share/icons/hicolor/32x32/apps/* /opt/"$APP"/icons/ 2>/dev/null
+cp ./squashfs-root/usr/share/icons/hicolor/48x48/apps/* /opt/"$APP"/icons/ 2>/dev/null
+cp ./squashfs-root/usr/share/icons/hicolor/64x64/apps/* /opt/"$APP"/icons/ 2>/dev/null
+cp ./squashfs-root/usr/share/icons/hicolor/128x128/apps/* /opt/"$APP"/icons/ 2>/dev/null
+cp ./squashfs-root/usr/share/icons/hicolor/256x256/apps/* /opt/"$APP"/icons/ 2>/dev/null
+cp ./squashfs-root/usr/share/icons/hicolor/512x512/apps/* /opt/"$APP"/icons/ 2>/dev/null
+cp ./squashfs-root/usr/share/icons/hicolor/scalable/apps/* /opt/"$APP"/icons/ 2>/dev/null
+cd /opt/"$APP"/icons
+for file in *.png; do mv -- "$file" "${file%%.png}" 2> /dev/null; done
 cd ..
 
-mkdir /opt/$APP/launchers
-cp ./squashfs-root/usr/share/applications/* /opt/$APP/launchers/ 2>/dev/null
-cd /opt/$APP/launchers
-for file in *; do mv ./$file ./AM-$APP-$file
-done
-sed -i "s#Exec=#Exec=/opt/kdeutils/kdeutils #g" /opt/$APP/launchers/*.desktop
-sed -i "s#Icon=#Icon=/opt/kdeutils/icons/#g" /opt/$APP/launchers/*.desktop
-cp /opt/$APP/launchers/*.desktop /usr/share/applications/
+mkdir /opt/"$APP"/launchers
+cp ./squashfs-root/usr/share/applications/* /opt/"$APP"/launchers/ 2>/dev/null
+cd /opt/"$APP"/launchers
+for f in *; do mv "$f" "$APP-${f%.desktop}-AM.desktop"; done
+sed -i "s#Exec=#Exec=/opt/kdeutils/kdeutils #g" /opt/"$APP"/launchers/*.desktop 2> /dev/null
+sed -i "s#Icon=#Icon=/opt/kdeutils/icons/#g" /opt/"$APP"/launchers/*.desktop 2> /dev/null
+cp /opt/"$APP"/launchers/*.desktop /usr/share/applications/  2> /dev/null
 
-rm -R -f /opt/$APP/launchers
-rm -R -f /opt/$APP/squashfs-root
-
-
-
-
+rm -R -f /opt/"$APP"/launchers
+rm -R -f /opt/"$APP"/squashfs-root
