Update mpv and obs-studio, use new multiple choice scripts

diff --git a/programs/x86_64/mpv b/programs/x86_64/mpv
--- a/programs/x86_64/mpv
+++ b/programs/x86_64/mpv
@@ -1,17 +1,17 @@
 #!/bin/sh
 
 # AM INSTALL SCRIPT VERSION 3.5
+set -u
 APP=mpv
-SITE1="pkgforge-dev/mpv-AppImage"
-SITE2="ivan-hc/MPV-appimage"
+SITE1="pkgforge-dev/mpv-AppImage" SITE2="ivan-hc/MPV-appimage"
 
 # CREATE DIRECTORIES AND ADD REMOVER
 [ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
-printf "#!/bin/sh\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
+printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
 printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
 chmod a+x ../remove || exit 1
 
-# CHOOSE A VERSION
+# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
 read -r -p "
  Choose which version of mpv AppImage to use:
 
@@ -25,25 +25,28 @@ read -r -p "
     Source: https://github.com/ivan-hc/MPV-appimage
 
  Which version you choose (type a number and press ENTER)?" response
-case "$response" in
-	1) rm -f /opt/"$APP"/version
-	UPDATER=1
-	version=$(curl -Ls https://api.github.com/repos/"$SITE1"/releases | sed 's/[()",{} ]/\n/g' | grep -io 'https.*mpv.*86_64.*mage$' | head -1)
-	wget "$version"
-	echo "$version" >> /opt/$APP/version;;
-	2) rm -f /opt/"$APP"/version
-	version=$(curl -Ls https://api.github.com/repos/"$SITE2"/releases | sed 's/[()",{} ]/\n/g' | grep -io 'https.*continuous.*mpv.*86_64.*mage$' | head -1)
-	UPDATER=2
-	wget "$version"
-	echo "$version" >> /opt/$APP/version;;
-	*) /opt/"$APP"/remove && exit;;
-esac
+RELEASE=""
+if echo "$response" | grep -q "^1"; then
+	RELEASE="$SITE1"
+elif echo "$response" | grep -q "^2"; then
+	RELEASE="$SITE2"
+fi
+[ -z "$RELEASE" ] && exit 0
+
+version=$(curl -Ls https://api.github.com/repos/"$RELEASE"/releases | sed 's/[()",{} ]/\n/g' | grep -io 'https.*mpv.*86_64.*mage$' | grep -i "$APP\|continuous" | head -1)
+if [ -z "$version" ]; then
+	printf "\n 💀 ERROR: it seems that upstream removed %b, please retry\n" "$RELEASE" && exit 1
+else
+	wget "$version" || exit 1
+fi
 cd ..
 mv ./tmp/*mage ./"$APP"
+# Keep this space in sync with other installation scripts
 rm -R -f ./tmp || exit 1
+echo "$version" > ./version
 chmod a+x ./"$APP" || exit 1
 
-# LINK
+# LINK TO PATH
 ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"
 
 # SCRIPT TO UPDATE THE PROGRAM
@@ -51,9 +54,9 @@ cat >> ./AM-updater << 'EOF'
 #!/bin/sh
 set -u
 APP=mpv
-if [ -z "$APP" ]; then exit 1; fi
+SITE="REPLACETHIS"
 version0=$(cat "/opt/$APP/version")
-version=$(curl -Ls https://api.github.com/repos/$SITE/releases | sed 's/[()",{} ]/\n/g' | grep -io 'https.*mpv.*86_64.*mage$' | head -1)
+version=$(curl -Ls https://api.github.com/repos/REPLACETHIS/releases | sed 's/[()",{} ]/\n/g' | grep -io 'https.*mpv.*86_64.*mage$' | grep -i "$APP\|continuous" | head -1)
 [ -n "$version" ] || { echo "Error getting link"; exit 1; }
 if command -v appimageupdatetool >/dev/null 2>&1; then
 	cd "/opt/$APP" || exit 1
@@ -74,12 +77,8 @@ else
 	echo "Update not needed!"
 fi
 EOF
-if [ "$UPDATER" = "1" ]; then
-	sed -i 's#$SITE#pkgforge-dev/mpv-AppImage#g' /opt/"$APP"/AM-updater
-elif [ "$UPDATER" = "2" ]; then
-	sed -i 's#$SITE#ivan-hc/MPV-appimage#g' /opt/"$APP"/AM-updater
-fi
 chmod a+x ./AM-updater || exit 1
+sed -i "s#REPLACETHIS#$RELEASE#g" /opt/"$APP"/AM-updater
 
 # LAUNCHER & ICON
 ./"$APP" --appimage-extract *.desktop 1>/dev/null && mv ./squashfs-root/*.desktop ./"$APP".desktop
@@ -87,11 +86,11 @@ chmod a+x ./AM-updater || exit 1
 COUNT=0
 while [ "$COUNT" -lt 10 ]; do # Tries to get the actual icon/desktop if it is a symlink to another symlink
 	if [ -L ./"$APP".desktop ]; then
-		LINKPATH=$(readlink ./"$APP".desktop)
+		LINKPATH="$(readlink ./"$APP".desktop | sed 's|^\./||' 2>/dev/null)"
 		./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./"$APP".desktop
 	fi
 	if [ -L ./DirIcon ]; then
-		LINKPATH=$(readlink ./DirIcon)
+		LINKPATH="$(readlink ./DirIcon | sed 's|^\./||' 2>/dev/null)"
 		./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./DirIcon
 	fi
 	[ ! -L ./"$APP".desktop ] && [ ! -L ./DirIcon ] && break
