Update node and platform-tools (check if commands already exist)

diff --git a/programs/x86_64/node b/programs/x86_64/node
--- a/programs/x86_64/node
+++ b/programs/x86_64/node
@@ -25,7 +25,11 @@ chmod a+x ./bin/"$APP" || exit 1
 
 # LINK TO PATH
 for m in $APP $METAPKG; do
-	ln -s /opt/"$APP"/bin/"$m" /usr/local/bin/"$m" 2>/dev/null
+	if command -v "$m" >/dev/null 2>&1; then
+		printf "\n 💀 ERROR, the command \"%b\" already exists\n" "$m" && /opt/"$APP"/remove && exit 1
+	else
+		ln -s /opt/"$APP"/bin/"$m" /usr/local/bin/"$m" 2>/dev/null
+	fi
 done
 
 # SCRIPT TO UPDATE THE PROGRAM
diff --git a/programs/x86_64/platform-tools b/programs/x86_64/platform-tools
--- a/programs/x86_64/platform-tools
+++ b/programs/x86_64/platform-tools
@@ -25,7 +25,11 @@ for m in $METAPKG; do [ -f ./"$m" ] && chmod a+x ./"$m" 2>/dev/null || exit 1; d
 
 # LINK TO PATH
 for m in $METAPKG; do
-	[ -f /opt/"$APP"/"$m" ] && ln -s /opt/"$APP"/"$m" /usr/local/bin/"$m" 2>/dev/null
+	if command -v "$m" >/dev/null 2>&1; then
+		printf "\n 💀 ERROR, the command \"%b\" already exists\n" "$m" && /opt/"$APP"/remove && exit 1
+	else
+		ln -s /opt/"$APP"/bin/"$m" /usr/local/bin/"$m" 2>/dev/null
+	fi
 done
 
 # SCRIPT TO UPDATE THE PROGRAM
