Add files via upload

diff --git a/programs/x86_64/openarena b/programs/x86_64/openarena
--- a/programs/x86_64/openarena
+++ b/programs/x86_64/openarena
@@ -1,90 +1,74 @@
 #!/bin/sh
 
+# AM INSTALL SCRIPT VERSION 3.5
+set -u
 APP=openarena
+SITE="http://openarena.ws"
 
-CATEGORIES="Game"
-ICONURL="https://upload.wikimedia.org/wikipedia/commons/f/f0/Openarena-logo.svg"
+# CREATE DIRECTORIES AND ADD REMOVER
+[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
+printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
+printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
+chmod a+x ../remove || exit 1
 
-URL=https://aur.archlinux.org/packages/openarena
-COMMENT="A violent, sexy, multiplayer first person shooter based on the ioquake3 engine"
-APPNAME=OpenArena
-
-# CREATE THE FOLDER
-mkdir /opt/$APP
-cd /opt/$APP
-
-# ADD THE REMOVER
-echo '#!/bin/sh' >> /opt/$APP/remove
-echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/games/$APP" >> /opt/$APP/remove
-chmod a+x /opt/$APP/remove
-
-# DOWNLOAD THE ZIP ARCHIVE
-mkdir tmp
-cd ./tmp
-
+# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
 version=$(curl -Ls https://aur.archlinux.org/packages/openarena | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep .zip | head -1)
-wget $version
-dir=$(ls . | rev | cut -c 5- | rev)
-echo "$version" >> /opt/$APP/version
-
-unzip -qq ./*.zip
-
+wget "$version" || exit 1
+[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
+[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
+[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
 cd ..
-mv ./tmp/$dir/* ./
-rm -R -f ./tmp
+if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
+rm -R -f ./tmp || exit 1
+echo "$version" > ./version
+chmod a+x ./"$APP".x86_64 || exit 1
 
-# LINK
-cat >> /usr/local/games/$APP << 'EOF'
+# LINK TO PATH
+cat >> /usr/local/bin/"$APP" << 'EOF'
 #!/bin/sh
 APP=openarena
 exec /opt/$APP/$APP.x86_64
 EOF
-chmod a+x /usr/local/games/$APP
+chmod a+x /usr/local/bin/"$APP"
 
 # SCRIPT TO UPDATE THE PROGRAM
-cat >> /opt/$APP/AM-updater << 'EOF'
-#!/usr/bin/env bash
+cat >> ./AM-updater << 'EOF'
+#!/bin/sh
+set -u
 APP=openarena
-version0=$(cat /opt/$APP/version)
-url=https://aur.archlinux.org/packages/openarena
-if curl -L -s $url | grep -ioF "$version0"; then
-  echo "Update not needed!"
+SITE="http://openarena.ws"
+version0=$(cat "/opt/$APP/version")
+version=$(curl -Ls https://aur.archlinux.org/packages/openarena | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep .zip | head -1)
+[ -n "$version" ] || { echo "Error getting link"; exit 1; }
+if [ "$version" != "$version0" ]; then
+	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
+	notify-send "A new version of $APP is available, please wait"
+	wget "$version" || exit 1
+	[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
+	[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
+	[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
+	cd ..
+	if [ -d ./tmp/* 2>/dev/null ]; then mv --backup=t ./tmp/*/* ./; else mv --backup=t ./tmp/* ./"$APP" 2>/dev/null || mv --backup=t ./tmp/* ./; fi
+	chmod a+x ./"$APP".x86_64 || exit 1
+	echo "$version" > ./version
+	rm -R -f ./tmp ./*~
+	notify-send "$APP is updated!"
 else
-  notify-send "A new version of $APP is available, please wait"
-  mkdir /opt/$APP/tmp
-  cd /opt/$APP/tmp
-  version=$(curl -Ls https://aur.archlinux.org/packages/openarena | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep .zip | head -1)
-  wget $version
-  dir=$(ls . | rev | cut -c 5- | rev)
-  unzip -qq ./*.zip
-  cd ..
-  if test -f ./tmp/*.zip; then rm ./version
-  fi
-  echo $version >> ./version
-  mv --backup=t ./tmp/$dir/* ./
-  chmod a+x /opt/$APP/$APP
-  rm -R -f ./tmp ./*~
-  notify-send "$APP is updated!"
+	echo "Update not needed!"
 fi
 EOF
-sed -i s/FILENAMEEXTENTION/$FILENAMEEXTENTION/g /opt/$APP/AM-updater
-chmod a+x /opt/$APP/AM-updater
+chmod a+x ./AM-updater || exit 1
+
+# ICON
+mkdir -p icons
+wget https://portable-linux-apps.github.io/icons/openarena.png -O ./icons/"$APP" 2> /dev/null
 
 # LAUNCHER
-rm -f /usr/share/applications/AM-$APP.desktop
 echo "[Desktop Entry]
-Name=$APPNAME
+Name=OpenArena
 Exec=$APP
+Comment=A violent, sexy, multiplayer first person shooter based on the ioquake3 engine
 Icon=/opt/$APP/icons/$APP
 Type=Application
 Terminal=false
-Categories=$CATEGORIES;
-Comment=$COMMENT" >> /usr/share/applications/AM-$APP.desktop
-
-# ICON
-mkdir ./icons
-wget $ICONURL -O /opt/$APP/icons/$APP
-
-
-
-
+Categories=Game;" > /usr/local/share/applications/"$APP"-AM.desktop
