Fix recoll

diff --git a/programs/x86_64/recoll b/programs/x86_64/recoll
--- a/programs/x86_64/recoll
+++ b/programs/x86_64/recoll
@@ -12,10 +12,13 @@ printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
 chmod a+x ../remove || exit 1
 
 # DOWNLOAD AND PREPARE THE APP, $version is also used for updates
-version=$(wget -q "$SITE" -O - | grep -oP 'Recoll-\K[0-9.]+(?=-x86_64\.AppImage)' | head -1)
-wget -O "$APP" "https://www.recoll.org/downloads/appimages/Recoll-x86_64.AppImage" || exit 1
+version=$(wget -q https://repology.org/project/recoll/versions -O - | grep -i "new.*version" | head -1 | tr '><' '\n' | grep "^[0-9]")
+wget "$(echo "https://www.recoll.org/downloads/appimages/$(curl -Ls https://www.recoll.org/downloads/appimages/ | tr '"' '\n' | grep "[0-9].*x86_64.*mage$" | tail -1)")" || exit 1
+#wget "$version.zsync" 2> /dev/null # Comment out this line if you want to use zsync
+# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
 cd ..
-mv ./tmp/"$APP" ./"$APP"
+mv ./tmp/*mage ./"$APP"
+mv ./tmp/*.zsync ./"$APP".zsync 2>/dev/null
 rm -R -f ./tmp || exit 1
 echo "$version" > ./version
 chmod a+x ./"$APP" || exit 1
@@ -30,20 +33,22 @@ set -u
 APP=recoll
 SITE="https://www.recoll.org"
 version0=$(cat "/opt/$APP/version")
-version=$(wget -q "$SITE" -O - | grep -oP 'Recoll-\K[0-9.]+(?=-x86_64\.AppImage)' | head -1)
-[ -n "$version" ] || { echo "Error getting version"; exit 1; }
-if [ "$version" != "$version0" ]; then
-    mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
-    notify-send "A new version of $APP is available, please wait"
-    wget -O "$APP" "https://www.recoll.org/downloads/appimages/Recoll-x86_64.AppImage" || exit 1
-    cd ..
-    mv --backup=t ./tmp/"$APP" ./"$APP"
-    chmod a+x ./"$APP" || exit 1
-    echo "$version" > ./version
-    rm -R -f ./tmp ./*~
-    notify-send "$APP is updated!"
+version=$(wget -q https://repology.org/project/recoll/versions -O - | grep -i "new.*version" | head -1 | tr '><' '\n' | grep "^[0-9]")
+[ -n "$version" ] || { echo "Error getting link"; exit 1; }
+if [ "$version" != "$version0" ] || [ -e /opt/"$APP"/*.zsync ]; then
+	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
+	[ -e ../*.zsync ] || notify-send "A new version of $APP is available, please wait"
+	[ -e ../*.zsync ] && wget "$version.zsync" 2>/dev/null || { wget "$(echo "https://www.recoll.org/downloads/appimages/$(curl -Ls https://www.recoll.org/downloads/appimages/ | tr '"' '\n' | grep "[0-9].*x86_64.*mage$" | tail -1)")" || exit 1; }
+	# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
+	cd ..
+	mv ./tmp/*.zsync ./"$APP".zsync 2>/dev/null || mv --backup=t ./tmp/*mage ./"$APP"
+	[ -e ./*.zsync ] && { zsync ./"$APP".zsync || notify-send -u critical "zsync failed to update $APP"; }
+	chmod a+x ./"$APP" || exit 1
+	echo "$version" > ./version
+	rm -R -f ./*zs-old ./*.part ./tmp ./*~
+	notify-send "$APP is updated!"
 else
-    echo "Update not needed!"
+	echo "Update not needed!"
 fi
 EOF
 chmod a+x ./AM-updater || exit 1
@@ -53,16 +58,16 @@ chmod a+x ./AM-updater || exit 1
 ./"$APP" --appimage-extract .DirIcon 1>/dev/null && mv ./squashfs-root/.DirIcon ./DirIcon
 COUNT=0
 while [ "$COUNT" -lt 10 ]; do # Tries to get the actual icon/desktop if it is a symlink to another symlink
-    if [ -L ./"$APP".desktop ]; then
-        LINKPATH="$(readlink ./"$APP".desktop | sed 's|^\./||' 2>/dev/null)"
-        ./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./"$APP".desktop
-    fi
-    if [ -L ./DirIcon ]; then
-        LINKPATH="$(readlink ./DirIcon | sed 's|^\./||' 2>/dev/null)"
-        ./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./DirIcon
-    fi
-    [ ! -L ./"$APP".desktop ] && [ ! -L ./DirIcon ] && break
-    COUNT=$((COUNT + 1))
+	if [ -L ./"$APP".desktop ]; then
+		LINKPATH="$(readlink ./"$APP".desktop | sed 's|^\./||' 2>/dev/null)"
+		./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./"$APP".desktop
+	fi
+	if [ -L ./DirIcon ]; then
+		LINKPATH="$(readlink ./DirIcon | sed 's|^\./||' 2>/dev/null)"
+		./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./DirIcon
+	fi
+	[ ! -L ./"$APP".desktop ] && [ ! -L ./DirIcon ] && break
+	COUNT=$((COUNT + 1))
 done
 sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g" ./"$APP".desktop
 mv ./"$APP".desktop /usr/local/share/applications/"$APP"-AM.desktop && mv ./DirIcon ./icons/"$APP" 1>/dev/null
