Add 55 new apps from AUR

diff --git a/programs/x86_64/voicevox b/programs/x86_64/voicevox
--- a/programs/x86_64/voicevox
+++ b/programs/x86_64/voicevox
@@ -1,7 +1,14 @@
 #!/bin/sh
 
-APP=iptvnator
-SITE="https://github.com/4gray/iptvnator/"
+APP=voicevox
+SITE="https://voicevox.hiroshiba.jp/"
+
+# CHECK FOR DEPENDENCY
+for name in "pzip"
+do
+  [[ $(which $name 2>/dev/null) ]] || { echo "" && echo -e 'ERROR: "'$name'" not found, required by some installation scripts.';deps=1; }
+done
+[[ $deps -ne 1 ]] || { echo -e "\nInstall the above and try again\n";exit 1; }
 
 # CREATE THE FOLDER
 mkdir /opt/$APP
@@ -16,11 +23,16 @@ chmod a+x /opt/$APP/remove
 mkdir tmp
 cd ./tmp
 
-version=$(echo $(wget -q https://aur.archlinux.org/packages/iptvnator-appimage -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep -i ".appimage" | grep -w -v arm64 | grep -w -v armv7l | grep -w -v ".asc" | grep -w -v ".zsync" | grep -w -v "archlinux.org" | head -1))
+version=$(echo $(wget -q https://aur.archlinux.org/packages/voicevox-appimage -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep -i ".appimage" | grep -w -v ".asc" | grep -w -v ".zsync" | grep 001 | grep -w -v "archlinux.org" | head -1))
+version2=$(echo $(wget -q https://aur.archlinux.org/packages/voicevox-appimage -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep -i ".appimage" | grep -w -v ".asc" | grep -w -v ".zsync" | grep 002 | grep -w -v "archlinux.org" | head -1))
+version3=$(echo $(wget -q https://aur.archlinux.org/packages/voicevox-appimage -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep -i ".appimage" | grep -w -v ".asc" | grep -w -v ".zsync" | grep 003 | grep -w -v "archlinux.org" | head -1))
 wget $version
+wget $version2
+wget $version3
+7z x ./*7z.001
 echo "$version" >> /opt/$APP/version
 cd ..
-mv ./tmp/* ./$APP
+mv ./tmp/*mage ./$APP
 chmod a+x /opt/$APP/$APP
 rmdir ./tmp
 
@@ -30,20 +42,25 @@ ln -s /opt/$APP/$APP /usr/local/bin/$APP
 # SCRIPT TO UPDATE THE PROGRAM
 cat >> /opt/$APP/AM-updater << 'EOF'
 #!/usr/bin/env bash
-APP=iptvnator
+APP=voicevox
 version0=$(cat /opt/$APP/version)
-version=$(echo $(wget -q https://aur.archlinux.org/packages/iptvnator-appimage -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep -i ".appimage" | grep -w -v arm64 | grep -w -v armv7l | grep -w -v ".asc" | grep -w -v ".zsync" | grep -w -v "archlinux.org" | head -1))
+version=$(echo $(wget -q https://aur.archlinux.org/packages/voicevox-appimage -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep -i ".appimage" | grep -w -v ".asc" | grep -w -v ".zsync" | grep -w -v "archlinux.org" | head -1))
 if [ $version = $version0 ]; then
   echo "Update not needed!"
 else
-  notify-send "A new version of $APP is available, please wait"
+  notify-send "A new version of $APP is available, about 3GB of archives will be downloaded, please wait"
   mkdir /opt/$APP/tmp
   cd /opt/$APP/tmp
+  version2=$(echo $(wget -q https://aur.archlinux.org/packages/voicevox-appimage -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep -i ".appimage" | grep -w -v ".asc" | grep -w -v ".zsync" | grep 002 | grep -w -v "archlinux.org" | head -1))
+  version3=$(echo $(wget -q https://aur.archlinux.org/packages/voicevox-appimage -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep -i ".appimage" | grep -w -v ".asc" | grep -w -v ".zsync" | grep 003 | grep -w -v "archlinux.org" | head -1))
   wget $version
+  wget $version2
+  wget $version3
+  7z x ./*7z.001
   cd ..
   rm ./version
   echo $version >> ./version
-  mv --backup=t ./tmp/* ./$APP
+  mv --backup=t ./tmp/*mage ./$APP
   chmod a+x /opt/$APP/$APP
   rm -R -f ./tmp ./*~
   notify-send "$APP is updated!"
