Update wine

diff --git a/programs/x86_64/wine b/programs/x86_64/wine
--- a/programs/x86_64/wine
+++ b/programs/x86_64/wine
@@ -43,17 +43,21 @@ if [ -z "$APP" ]; then exit 1; fi
 version0=$(cat "/opt/$APP/version")
 tag=$(echo "$version0" | tr '/' '\n' | tail -2 | head -1)
 version=$(curl -Ls https://api.github.com/repos/mmtrt/WINE_AppImage/releases | grep browser_download_url | grep -i "download/$tag/$app" | grep -i appimage | cut -d '"' -f 4 | head -1)
-mkdir "/opt/$APP/tmp"
-cd "/opt/$APP/tmp" || exit 1
-wget "$version.zsync" 2> /dev/null
-cd ..
-mv ./tmp/*.zsync ./"$APP".zsync
-rm -R -f ./tmp
-zsync "/opt/$APP/$APP.zsync"
-rm -R -f "/opt/$APP/*zs-old" "/opt/$APP/*.part"
-chmod a+x "/opt/$APP/$APP"
-if [ "$version" != "$version0" ]; then
-	echo "$version" > /opt/$APP/version
+[ -n "$version" ] || { echo "Error getting link"; exit 1; }
+if [ "$version" != "$version0" ] || [ -e /opt/"$APP"/*.zsync ]; then
+	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
+	[ -e ../*.zsync ] || notify-send "A new version of $APP is available, please wait"
+	[ -e ../*.zsync ] && wget "$version.zsync" 2>/dev/null || { wget "$version" || exit 1; }
+	# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
+	cd ..
+	mv ./tmp/*.zsync ./"$APP".zsync 2>/dev/null || mv --backup=t ./tmp/*mage ./"$APP"
+	[ -e ./*.zsync ] && { zsync ./"$APP".zsync || notify-send -u critical "zsync failed to update $APP"; }
+	chmod a+x ./"$APP" || exit 1
+	echo "$version" > ./version
+	rm -R -f ./*zs-old ./*.part ./tmp ./*~
+	notify-send "$APP is updated!"
+else
+	echo "Update not needed!"
 fi
 EOF
 chmod a+x "/opt/$APP/AM-updater"
