more tests

diff --git a/.github/workflows/test-apps.yml b/.github/workflows/test-apps.yml
--- a/.github/workflows/test-apps.yml
+++ b/.github/workflows/test-apps.yml
@@ -92,14 +92,32 @@ jobs:
         run: |
           mkdir -p results
           if timeout "$TIMEOUT"m am -i "${{ matrix.file }}"; then
+            echo ""
+            echo " Structure of the directory ${{ matrix.file }}"
+            echo ""
+            ls /opt/"${{ matrix.file }}"
+            echo ""
+            echo "-------------------------------------------------------------"
+            echo ""
+            echo " Command in \$PATH"
+            echo ""
+            command -v "${{ matrix.file }}"
+            echo ""
+            echo "-------------------------------------------------------------"
+            echo ""
+            echo " Launchers in /usr/local/share/applications"
+            echo ""
+            ls /usr/local/share/applications
+            echo ""
+            echo "-------------------------------------------------------------"
             am -R "${{ matrix.file }}" && echo "${{ matrix.file }}" > results/results-${{ matrix.file }}
-          else
-            if [[ $? -eq 124 ]]; then
-              echo "### :boom: Timeout $TIMEOUT minutes reached ${{ matrix.file }}!" >> $GITHUB_STEP_SUMMARY
             else
-              echo "### :skull: FAIL: ${{ matrix.file }}" >> $GITHUB_STEP_SUMMARY
-            fi
-            exit 1
+              if [[ $? -eq 124 ]]; then
+                echo "### :boom: Timeout $TIMEOUT minutes reached ${{ matrix.file }}!" >> $GITHUB_STEP_SUMMARY
+              else
+                echo "### :skull: FAIL: ${{ matrix.file }}" >> $GITHUB_STEP_SUMMARY
+              fi
+              exit 1
           fi
 
       - name: "Upload Test Results ⬆️"
