Update test-apps.yml

diff --git a/.github/workflows/test-apps.yml b/.github/workflows/test-apps.yml
--- a/.github/workflows/test-apps.yml
+++ b/.github/workflows/test-apps.yml
@@ -231,7 +231,7 @@ jobs:
       - name: "Install dependencies 📦️"
         run: |
           sudo apt-get -y update 2> /dev/null || apt-get -y update
-          sudo apt-get -y install wget curl torsocks zsync 2> /dev/null || apt-get -y install git wget curl torsocks zsync
+          sudo apt-get -y install wget curl torsocks zsync 2> /dev/null || apt-get -y install wget curl torsocks zsync
           sudo systemctl enable tor.service || systemctl enable tor.service
           sudo systemctl restart tor.service || systemctl restart tor.service
 
@@ -245,12 +245,30 @@ jobs:
         run: |
           set -uo pipefail
           mkdir -p results
-          script_content=$(curl -Ls https://raw.githubusercontent.com/ivan-hc/AM/main/programs/x86_64/"${{ matrix.file }}")
+
+          #script_content=$(curl -Ls https://raw.githubusercontent.com/ivan-hc/AM/main/programs/x86_64/"${{ matrix.file }}")
           pure_arg=$(echo "${{ matrix.file }}" | sed 's/\-appimage$//g' | sed 's:.*/::')
+
           if timeout "$TIMEOUT"m echo y | am -i "${{ matrix.file }}" --debug 2>&1 | tee -a results/log-"${{ matrix.file }}"; then
-            if [[ "$pure_arg" =~ (bat-extras|code$|kvrt|libfuse2|libreoffice|microsoft-edge*|mpv|node$|npm|oras|suyu|swift|wine) ]]; then
-              echo "App not installed, this is a Known error related to GitHub Actions" | tee -a results/log-"${{ matrix.file }}"
+
+            # Blacklist some applications
+            if [[ "$pure_arg" =~ (bat-extras|code$|microsoft-edge*|node$|npm|oras) ]]; then
+
+              echo "This app is blacklisted due to known errors related to GitHub Actions" | tee -a results/log-"${{ matrix.file }}"
+
             else
+
+              # Check if the app needs interaction to be installed
+              if [[ "$pure_arg" =~ (libreoffice|mpv|wine) ]]; then
+                echo 1 | am -i "${{ matrix.file }}" --debug 2>&1
+                LASTDIR=$(ls -td /opt/* | head -1 | sed 's:.*/::')
+                if ! test -f /opt/"$LASTDIR"/remove; then
+                  sudo systemctl restart tor.service || systemctl restart tor.service
+                  echo 1 | torsocks am -i "${{ matrix.file }}" --debug 2>&1
+                fi
+              fi
+
+              # Force installation if first attempt is not success
               LASTDIR=$(ls -td /opt/* | head -1 | sed 's:.*/::')
               if ! test -f /opt/"$LASTDIR"/remove; then
                 sudo systemctl restart tor.service || systemctl restart tor.service
@@ -262,23 +280,28 @@ jobs:
                   LASTDIR=$(ls -td /opt/* | head -1 | sed 's:.*/::')
                 fi
               fi
-              echo ""
+
+              printf "\n-------------------------------------------------------------\n\n"
+
+              # Check structure of directories in /opt
               echo " Structure of the directory in /opt"
               echo ""
               if test -f /opt/"$LASTDIR"/remove; then
                  ls /opt/"$LASTDIR" | tee -a results/log-"${{ matrix.file }}"
               else
-                 ls /WTF | tee -a results/log-"${{ matrix.file }}"
+                 exit 1
               fi
-              echo ""
-              echo "-------------------------------------------------------------"
-              echo ""
+
+              printf "\n-------------------------------------------------------------\n\n"
+
+              # Check the command in /usr/local/bin
               echo " Command in \$PATH"
               echo ""
-              command -v "$pure_arg" | tee -a results/log-"${{ matrix.file }}" || ls /usr/local/bin | tee -a results/log-"${{ matrix.file }}"
-              echo ""
-              echo "-------------------------------------------------------------"
-              echo ""
+              command -v "$pure_arg" | tee -a results/log-"${{ matrix.file }}" || command -v "$LASTDIR" | tee -a results/log-"${{ matrix.file }}" || ls /usr/local/bin | tee -a results/log-"${{ matrix.file }}"
+
+              printf "\n-------------------------------------------------------------\n\n"
+
+              # Check launchers in /usr/local/share/applications
               echo " Launchers in /usr/local/share/applications" | tee -a results/log-"${{ matrix.file }}"
               echo ""
               if test -f /usr/local/share/applications/*AM.desktop 2>/dev/null; then
@@ -286,11 +309,16 @@ jobs:
               else
                  ls /usr/local/share/applications | tee -a results/log-"${{ matrix.file }}"
               fi
-              echo ""
-              echo "-------------------------------------------------------------"
-              am -R "${{ matrix.file }}" && echo "${{ matrix.file }}" >> results/ok-${{ matrix.file }} || echo "${{ matrix.file }}" >> results/log-${{ matrix.file }}
+
+              printf "\n-------------------------------------------------------------\n\n"
+
+              # Remove the application
+              am -R "$LASTDIR" && echo "${{ matrix.file }}" >> results/ok-${{ matrix.file }} || echo "${{ matrix.file }}" >> results/log-${{ matrix.file }}
+
             fi
           else
+
+            # Determine timeout
             if [[ $? -eq 124 ]]; then
                echo "### 💥 ${{ matrix.file }} timeout!" >> $GITHUB_STEP_SUMMARY
                echo "Installation timeout in 50 minutes" >> results/log-"${{ matrix.file }}"
