Update test-apps.yml
- prevent failed.list to be created or pushed, to continue testing failed workflows at a later time

diff --git a/.github/workflows/test-apps.yml b/.github/workflows/test-apps.yml
--- a/.github/workflows/test-apps.yml
+++ b/.github/workflows/test-apps.yml
@@ -77,9 +77,11 @@ jobs:
           if [[ "${{ github.event.inputs.reset_stats }}" != "true" ]]; then
             echo "Preserving test files..."
             mkdir -p backup
-            cp -r tested.list failed.list logs backup/ 2>/dev/null || true
+            #cp -r tested.list failed.list logs backup/ 2>/dev/null || true
+            cp -r tested.list logs backup/ 2>/dev/null || true
             git reset --hard origin/main
-            mv backup/tested.list backup/failed.list backup/logs . 2>/dev/null || true
+            #mv backup/tested.list backup/failed.list backup/logs . 2>/dev/null || true
+            mv backup/tested.list backup/logs . 2>/dev/null || true
             rm -rf backup
             git add .
             git commit -m "update results"
@@ -157,19 +159,19 @@ jobs:
       - name: "Count tested & failed 📊"
         run: |
           tested=$(wc -l < tested.list 2>/dev/null || echo 0)
-          failed=$(wc -l < failed.list 2>/dev/null || echo 0)
+          #failed=$(wc -l < failed.list 2>/dev/null || echo 0)
           echo "x86_64: $x64Count"
           echo "i686: $i68Count"
           echo "aarch64: $a64Count"
           echo "🏁 Tested: $tested"
-          echo "❌ Failed: $failed"
+          #echo "❌ Failed: $failed"
           echo "### 🎬 apps" >> $GITHUB_STEP_SUMMARY
           echo "$x64Count x86_64" >> $GITHUB_STEP_SUMMARY
           echo "$i68Count i686" >> $GITHUB_STEP_SUMMARY
           echo "$a64Count aarch64" >> $GITHUB_STEP_SUMMARY
           echo "### 🔨 tests" >> $GITHUB_STEP_SUMMARY
           echo " 🏁 $tested" >> $GITHUB_STEP_SUMMARY
-          echo " ❌ $failed" >> $GITHUB_STEP_SUMMARY
+          #echo " ❌ $failed" >> $GITHUB_STEP_SUMMARY
 
   generate-matrix:
     name: "matrix 🌀"
@@ -374,9 +376,10 @@ jobs:
             mkdir -p logs
             cp results/ko-* logs/
             fail=$(wc -l < fail.list)
-            cat fail.list >> failed.list
-            sort -u failed.list -o failed.list
-            git add failed.list logs
+            #cat fail.list >> failed.list
+            #sort -u failed.list -o failed.list
+            #git add failed.list logs
+            git add logs
           else
             echo "Nothing failed? Great!"
           fi
@@ -404,7 +407,7 @@ jobs:
         if: always()
         run: |
           tested=$(wc -l < tested.list 2>/dev/null || echo 0)
-          failed=$(wc -l < failed.list 2>/dev/null || echo 0)
+          #failed=$(wc -l < failed.list 2>/dev/null || echo 0)
           fail=$(wc -l < fail.list 2>/dev/null || echo "0")
           count=$(find programs/x86_64/ -type f | wc -l)
           remaining=$((count - tested - failed - fail))
@@ -413,7 +416,7 @@ jobs:
           fi
           echo "### 🏁 $tested tested" >> $GITHUB_STEP_SUMMARY
           echo "## 🛅 $remaining to test" >> $GITHUB_STEP_SUMMARY
-          echo "😱 $failed fails listed" >> $GITHUB_STEP_SUMMARY
+          #echo "😱 $failed fails listed" >> $GITHUB_STEP_SUMMARY
           echo ":x: $fail failed now" >> $GITHUB_STEP_SUMMARY
           if [[ -f fail.list ]]; then
             echo "💀" >> $GITHUB_STEP_SUMMARY
